### ISSUE TITLE
[Admin manual] Document occ commands with maintenance mode suggestions

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/documentation#10063]
Some commands are available and safe during maintenance mode, others, due to Events being dispatched / apps not being loaded/ etc might not be.

Extend the section on occ commands inhttps://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html to document the specific behavior on whether a command is safe or unsafe.

**Comment by kesselb** [comment]
https://github.com/nextcloud/documentation/pull/10208
https://github.com/nextcloud/documentation/pull/10244
