### ISSUE TITLE
Documentation: behaviour with empty LDAP user-attributes undocumented

### ISSUE THREAD

**Issue by victorbw** [nextcloud/documentation#1010]
As mentioned here [#12582](https://github.com/nextcloud/server/issues/12582), there's no documentation about what happens when LDAP user-attributes are left empty:

![grafik](https://user-images.githubusercontent.com/8447071/49514573-ba585700-f894-11e8-981d-0ff4be0668e0.png)

Sugestion for somewhere in the top chapter of LDAP-documentation:

**Note**

When a LDAP object's name or surname is left empty, Nextcloud will treat it as an empty object, therefore no results from this user or AD-Object will be shown to avoid gathering of technical accounts.

//optional: picture

![grafik](https://user-images.githubusercontent.com/8447071/49514579-bcbab100-f894-11e8-9156-d8492c118754.png)

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by MorrisJobke** [comment]
Fix is in #1057
