### ISSUE TITLE
Connecting to WebDAV via `net use` requires `WebClient` service on Windows

### ISSUE THREAD

**Issue by Matthionine** [nextcloud/documentation#10207]
I had a somewhat difficult to troubleshoot issue:

Connecting to a nextcloud instance in Windows explorer using 'Computer' > 'Map Network Drive' worked. However, Windows had troubles to reestablish the connection at startup. For that reason, I tried to set it up via the Task Scheduler using `net use`. Which worked sometimes but not always.
Finally, I figured out that it does not work if the `WebClient` service is not running. Apparently, the `WebClient` service is started automatically in the background if mapping a WebDAV drive in Windows exploerer, but reconnecting during startup or when using `net use`.

Therefore, in my opinion the `WebClient` should be mentioned in the documentation. (See pull request  #10062 )

**Comment by tflidd** [comment]
Closed with https://github.com/nextcloud/documentation/pull/10062
