### ISSUE TITLE
Debian Bookworm provides MariaDB 10.11.2 but Nextcloud appears to only support versions up to 10.6?

### ISSUE THREAD

**Issue by chriscroome** [nextcloud/documentation#10350]
The Nextcloud system requirements for [version 26](https://docs.nextcloud.com/server/26/admin_manual/installation/system_requirements.html) include:

> **MariaDB 10.3/10.4/10.5/10.6** (recommended)

Debian Bookworm provides [version 10.11.2](https://packages.debian.org/bookworm/mariadb-server), if this version is compatible with any versions of Nextcloud would it be possible to update the documentation to reflect this?

**Comment by tflidd** [comment]
There are plenty of releases: https://mariadb.com/kb/en/mariadb-server-release-dates/
Not sure who tests it (and the named version are perhaps the ones NC runs automated tests), in the best case the versions don't change a lot and you can use the whole 10.x branch (preferably the long-term stable release).

**Comment by joshtrichards** [comment]
This request should probably start at https://github.com/nextcloud/server rather than here since the docs can only follow testing (and any development).

https://mariadb.com/kb/en/upgrading-from-mariadb-10-6-to-mariadb-10-11/#incompatible-changes-between-106-and-1011

https://mariadb.com/kb/en/changes-improvements-in-mariadb-1011/#new-features-improvements

**Comment by solracsf** [comment]
At this time, only 10.6 is tested.
10.11 LTS will be tested since https://github.com/nextcloud/server/pull/41003/files is merged.

**Comment by danepowell** [comment]
https://github.com/nextcloud/server/pull/41003 was just merged, implying that MariaDB 10.11 should be supported, though docs do not yet reflect this.

**Comment by solracsf** [comment]
It was merged 11h ago... 😉 
Please be patient, let some test run on it, and PR will pop up 👍 

_Note: I'm running a instance on 10.11 since Nextcloud 26, no problems._
