### ISSUE TITLE
_website_ typos

### ISSUE THREAD

**Issue by r2evans** [nextcloud/documentation#10478]
I could not find an Issues page for the website, please transfer if you can!

The PG key for new versions is out of whack. For 26.0.2, the text reads `nextcloud-25.0.5.tar.bz2.asc` and links to `nextcloud-26.0.2.tar.bz2.asc`; with 26.0.1, the text reads (again) `nextcloud-25.0.5.tar.bz2.asc` and links to `nextcloud-26.0.1.tar.bz2.asc`; similar issues for ***all other versions***, showing 25.0.5 but linking to the correct version.

![image](https://github.com/nextcloud/documentation/assets/5815808/93c2057b-26ba-434b-a267-b83e0fe2b1ff)

**Comment by joshtrichards** [comment]
Looks like this has been fixed!
