### ISSUE TITLE
"Transfer ownership" help page leads user to the wrong screen

### ISSUE THREAD

**Issue by dpoon** [nextcloud/documentation#10503]
According to https://docs.nextcloud.com/server/19/user_manual/files/transfer_ownership.html the first step for transferring file ownership is to go to *Settings* > *Personal* > *Sharing* > *Files*.

This is misleading, because:

- In the NextCloud files app, there are two user interfaces named "Settings": one in the bottom-left corner, and another in the top-right menu.  The latter is the relevant one in this case.
- There is no *Settings* > *Personal*.  There is *Settings* > *Personal info*, which is altogether wrong.  The instructions should say *Settings* > *Sharing*.

**Comment by ChristophWurst** [comment]
How about *Personal settings*?

![image](https://github.com/nextcloud/documentation/assets/1374172/f8239501-5e36-42b6-bea7-fe512dc34c31)
