### ISSUE TITLE
Update RHEL/CentOS docs to use PHP 7.1+

### ISSUE THREAD

**Issue by J0WI** [nextcloud/documentation#1058]
PHP 7.0 is EOL:
https://docs.nextcloud.com/server/stable/admin_manual/installation/php_70_installation.html

**Comment by MorrisJobke** [comment]
cc @hanserasmus @michag86

**Comment by michag86** [comment]
There are packages for 7.2 available at the software collections. I will update my systems in the next weeks if all packages are available. Maybe I can update the docs if I will find the time to do it.

**Comment by skjnldsv** [comment]
@michag86 thanks a lot :)
