### ISSUE TITLE
Instructions for installing Collabora Server docker are wrong regarding escaping dots.

### ISSUE THREAD

**Issue by cody42** [nextcloud/documentation#10641]
The instructions regarding the installtion of Collabora Server docker tell that dots in the domain need to be escaped using two backslashes.

According to the [documenation of the docker image collabora/code](https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html#setting-the-application-configuration-dynamically-via-environment-variables), double escaping apparently only was necessary for older versions of the image.

I verified on my system, that it office integration works with a s single backslash for escaping dots, but does not work with double backslash for escaping.

The following command is no longer correct:
```docker pull collabora/code
docker run -t -d -p 127.0.0.1:9980:9980 \
    -e 'domain=cloud\\.example\\.com' \
    --restart always \
    --cap-add MKNOD \
    collabora/code
```

The correct version is now:
```docker pull collabora/code
docker run -t -d -p 127.0.0.1:9980:9980 \
    -e 'domain=cloud\.example\.com' \
    --restart always \
    --cap-add MKNOD \
    collabora/code
```

The documentation should be updated accordingly, maybe with a note regarding older image versions.

**Comment by joshtrichards** [comment]
Good catch!

Can you do me a favor? Click on the `Edit on GitHub` button (in the upper right of the respective documentation page) and make the edits you're suggesting? 

Afterwards, from the same screen, you can submit them as a pull request (PR). 

That'll nudge this change along - and the community will benefit from your contributions sooner.
