### ISSUE TITLE
sharing options occ command missing in documentation

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#1068]
In the occ list command, there is one to clean remote storages. This point is completely missing in the docs (https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html):
```

 sharing
  sharing:cleanup-remote-storages     Cleanup shared storage entries that have no matching entry in the shares_external table
```

**Comment by MorrisJobke** [comment]
cc @MariusBluem

**Comment by MariusBluem** [comment]
I will take care of it.
