### ISSUE TITLE
Versions does not delete old files

### ISSUE THREAD

**Issue by WelliSolutions** [nextcloud/documentation#10790]
Affected documentation: https://docs.nextcloud.com/server/22/admin_manual/configuration_files/file_versioning.html

> The Versions app never uses more than 50% of the user’s currently available free space. If the stored versions exceed this limit, Nextcloud deletes the oldest file versions until it meets the disk space limit again.

I ran out of disk space, because I didn't have a quota set. So I gave all users a quota and hoped that Versions would delete the disk space to meet its 50% limit. However, nothing happened. My disk is still full.

In order for Versions to clean up the disk space, I needed to disable it and enable it again.

**Comment by joshtrichards** [comment]
Based on the description of the behavior you experienced, my best guess is that the background job was not active in your environment for some reason:

https://docs.nextcloud.com/server/26/admin_manual/configuration_files/file_versioning.html#background-job
