### ISSUE TITLE
Point "latest version" links to specific page

### ISSUE THREAD

**Issue by uusijani** [nextcloud/documentation#1085]
As discussed in [#915](https://github.com/nextcloud/documentation/issues/915) and [#517](https://github.com/nextcloud/documentation/issues/517), Google seems to prefer old versions' documentation at the expense of newer ones for some reason. The issue was partly mitigated by the fix for [#958](https://github.com/nextcloud/documentation/issues/958), which added prominent links to the latest version on top of old pages.

But these links currently point to the manual root. Ideally, I'd like these links to point directly to the latest version of the specific manual page I'm viewing, if available.

For instance, [a search for nextcloud occ](https://www.google.com/search?client=ubuntu&channel=fs&q=nextcloud+occ&ie=utf-8&oe=utf-8) (for me at least) currently yields the [manual page for version 9](https://docs.nextcloud.com/server/9/admin_manual/configuration_server/occ_command.html) as the top result. The "latest version" link at the top then takes me to [the server manual introduction](https://docs.nextcloud.com/server/stable/admin_manual/). This means it's still easier for me to navigate to the latest version of the "Using the occ command" page by manually replacing the version number in the current URL with 'stable' (or the latest release number) than to follow the "latest version" link and try to find the page there.

Producing specific links is probably more laborious than the generic top-level-pointing link. For instance, there may no longer be a corresponding page in the stable version. Detecting such cases should be automatable I think, but there may be other issues that aren't.

This will be much less of an issue once the SEO issue is resolved, but I think direct links would still remain useful, as people can still come up with search terms that search engines think correspond to old documentation better than the latest.

**Comment by skjnldsv** [comment]
Don't you think we shouold just wait for google to update evrything?
We could also declare the old ones as outdated to google?
Or remove them from the google robots?

Plenty of ways to make sure eople don't land there again :)

**Comment by uusijani** [comment]
@skjnldsv The points you raise are about SEO, and (from what I linked to above) I believe those issues are already being worked on. In case I was unclear, I'm _not_ arguing for my idea to _supplant_ the SEO work currently in progress, but to _augment_ it.

Obviously, if #915 gets implemented as requested, my issue becomes moot, but from reading the comments there I understand it's not so cut and dried that it will.

**Comment by tflidd** [comment]
It was also mentioned in this newer report: https://github.com/nextcloud/documentation/issues/1825

It was fixed in the meantime.
