### ISSUE TITLE
Document Mail summary feature

### ISSUE THREAD

**Issue by hamza221** [nextcloud/documentation#10917]
Document https://github.com/nextcloud/mail/issues/8508

**Comment by hamza221** [comment]
@ChristophWurst what should be included in the User docs, I couldn't think of anything

**Comment by hamza221** [comment]
Reopening to tack the missing user docs

**Comment by ChristophWurst** [comment]
Good point. There probably is nothing for the user to do. The summary shows automatically. It should be self-explanatory. There is no interaction possible with the feature.
