### ISSUE TITLE
new OCS API documentation - link leads to blank page

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/documentation#10923]
[OCS API documentation section](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/index.html) suggests:
> To browse the new OCS API documentation please go [here](https://docs.nextcloud.com/server/latest/developer_manual/_static/openapi.html)

Though that leads to a rather empty/blank page:
https://docs.nextcloud.com/server/latest/developer_manual/_static/openapi.html

![image](https://github.com/nextcloud/documentation/assets/7018928/4bde7ff8-e088-45ec-9fc5-ddc40e485317)

**Comment by joshtrichards** [comment]
Looks fixed. Is it working for you now?

**Comment by gerbrent** [comment]
seems to 👍🏻
