### ISSUE TITLE
Fail to activate LDAP in Nextcloud 26

### ISSUE THREAD

**Issue by wrondon-nextcloud** [nextcloud/documentation#11043]
Good afternoon,

Install **Nextcloud 26.0.2** I need to integrate it with LDAP but when installing php-ldap it does not allow activating the LDAP user and group backend (**This app cannot be installed because the following dependencies are not fulfilled: The library ldap is not available**).

Rocky 8 operating system
PHP 8.0.30
Apache/2.4.37 (rocky)

I appreciate any help

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
