### ISSUE TITLE
Adding admins to group levels

### ISSUE THREAD

**Issue by Amyvic500** [nextcloud/documentation#11041]
Ok here i am trying to add an admin to a group, this main group houses subgroups, which they can't not have access to the other subgroups but the admin for the main group see all the subgroups activities. is this possible with nextcloud and how can i do that?

**Comment by kesselb** [comment]
/
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue, I would like to ask you to raise your question at https://help.nextcloud.com
