### ISSUE TITLE
docs.nextcloud.com is offline or unresponsive

### ISSUE THREAD

**Issue by sunjam** [nextcloud/documentation#11070]
Unresponsive and not working for users in various locations.  See https://www.isitdownrightnow.com/docs.nextcloud.com.html

Thanks.

**Comment by BobbieERay** [comment]
Still down

**Comment by Fasihi-Rad** [comment]
Still down :(

**Comment by joshtrichards** [comment]
Cc: @nextcloud/infrastructure
