### ISSUE TITLE
Order of pages wrong?

### ISSUE THREAD

**Issue by LEDfan** [nextcloud/documentation#112]
Hi

A user has a problem with the documentation (https://help.nextcloud.com/t/installation-wizard-but-how/2059) and I confirm it's a bit weird. 

So we have this page which explains the installation wizard https://docs.nextcloud.com/server/9/admin_manual/installation/installation_wizard.html , but like the user says, there is nothing about the installation of Nextlcoud before this page. (Like downloading the tarball, extracting etc). I think this is caused because the `Preferred Linux Installation Method` page was removed. (Since we don't provide packages). 
Thus  the prefered way of installing Nextcloud is actually (for now) the manual installation https://docs.nextcloud.com/server/9/admin_manual/installation/source_installation.html .

Shouldn't this page (about the manual installation) be moved before the installation wizard, and before the pages about `installation apps`? Maybe this page should be renamed too?

To be clear with the order of the pages I mean the order they are presented on this page: https://docs.nextcloud.com/server/9/admin_manual/installation/index.html

**Comment by mar1u5** [comment]
@hagengraf What do you think?

**Comment by hagengraf** [comment]
@LEDfan @mar1u5 of course - sounds logical
