### ISSUE TITLE
Some missing pages in server configuration for newest versions

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/documentation#1122]
Just helped a user on Community forum looking for instructions how to configure SSO/SAML.  Found old ones [for 12](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/sso_configuration.html), but they seem to have disappeared for 13+? Maybe under a new heading somewhere? Searching for SSO, SAML or anything relevant only showed results for the apps available page. No config page.

**Comment by MorrisJobke** [comment]
We moved them to the portal AFAIK. cc @jospoortvliet

**Comment by gary-kim** [comment]
I was thinking about getting SSO set up on my personal instance then ran into this. I get why it was done but part of what makes Nextcloud fun for me is being able to play around with enterprise stuff at home.

I managed to figure it out but the fact that I had to go to another place to look for documentation was annoying. It's in my personal KB now so not a problem but if others want to play around with it, documentation being removed is annoying.
