### ISSUE TITLE
Link to outdated dokumentation

### ISSUE THREAD

**Issue by oe73773** [nextcloud/documentation#11263]
The documentation on "Transactional file locking" (https://docs.nextcloud.com/server/27/admin_manual/configuration_files/files_locking_transactional.html) includes a link to a external documention in "If you are on Ubuntu you can follow [this guide](https://www.techandme.se/how-to-configure-redis-cache-in-ubuntu-14-04-with-owncloud/) for a complete installation from scratch."

This Documentaion covers Ubuntu 14.04 with EOL in April, 2019. The link should be removed or replaced with a more recent version.

**Comment by tflidd** [comment]
Thanks for the hint. I have done a PR to remove this: https://github.com/nextcloud/documentation/pull/11264
and I found even more links here: https://github.com/nextcloud/documentation/pull/11265
