### ISSUE TITLE
Nginx config possible correction

### ISSUE THREAD

**Issue by pali7x** [nextcloud/documentation#11269]
Sorry if this is the wrong place for possbile correction/suggestion.

While optimizing cloudflare proxy on my nextcloud running nginx, I found the official nginx config from https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html might have one (possible) error.

    # Rule borrowed from `.htaccess` to handle Microsoft DAV clients
    location = / {
        if ( $http_user_agent ~ ^DavClnt ) {
            return 302 /remote.php/webdav/$is_args$args;
        }
    }

Based on current nextcloud's webdav api https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html

The base url for all WebDAV operations for a Nextcloud instance is /remote.php/dav.

So based on this, shouldn't the return 302 should be like this?

`return 302 /remote.php/dav/$is_args$args;`

I don't have a windows machine/vm to try on since the comment specifically mention for microsoft dav clients, but i updated my nginx config with remote.php/dav and nothing breaks so far, nor i've been using webdav for nextcloud access.

**Comment by anoymouserver** [comment]
This should still be correct as far as I can tell.

Matching `.htaccess` entry:
https://github.com/nextcloud/server/blob/137e488592ee8df08b1b811d596ca60b0422b134/.htaccess#L85-L86

Mapping in the `remote.php` itself:
https://github.com/nextcloud/server/blob/137e488592ee8df08b1b811d596ca60b0422b134/remote.php#L102

**Comment by joshtrichards** [comment]
It's the older WebDAV endpoint. If we ever retire it officially it'll disappear from the official `.htaccess` first. Then any changes would be ported over to the unofficial Nginx config example.

So it's the correct URL at the moment for that spot.

But a good eye nonetheless. :-)
