### ISSUE TITLE
e2e related documentation missing from mobile client manuals

### ISSUE THREAD

**Issue by sunjam** [nextcloud/documentation#11274]
Have tried setting up e2e encryption and cannot find any documentation in the [desktop 3 manual](https://github.com/nextcloud/desktop/issues/2433) or mobile client manuals.  I realize the devs here do not maintain those clients, but wanted to mention it here.  Thanks.

**Comment by joshtrichards** [comment]
Closing as no E2EE specific docs for mobile are necessary/planned at this time.

Also, the README for the server component has been expanded recently to include some basic setup instructions.
 
https://github.com/nextcloud/end_to_end_encryption/#end-to-end-encryption-app

**Comment by joshtrichards** [comment]
May incorporate some E2EE stuff into #11545. It'll certainly be discussed in the overview to provide the reader with some context for choosing their approach.
