### ISSUE TITLE
nextcloud flow docs: dead external links (36c3 talk)

### ISSUE THREAD

**Issue by proserver1** [nextcloud/documentation#11276]
in https://docs.nextcloud.com/server/27/developer_manual/digging_deeper/flow.html

,---------
At 36c3 blizzz gave a talk explaining Flow and [how to write actions and triggers.](https://mirror.eu.oneandone.net/projects/media.ccc.de/congress/2019/h264-sd/36c3-oio-174-eng-Building_Nextcloud_Flow_sd.mp4) You can [find the slides of their talk here.](https://nextcloud.com/wp-content/themes/next/assets/files/Building_nextcloud_flow.pdf)
`--------

both links are dead.

alternative for link 1
https://media.ccc.de/v/36c3-oio-174-building-nextcloud-flow

**Comment by tflidd** [comment]
I created a PR for your issue:
https://github.com/nextcloud/documentation/pull/11280

I used the link to the media server like you suggested (instead of a specific mirror), and for the slide notes I found a copy on the waybackmachine.
