### ISSUE TITLE
Add documentation for ransomware app

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#1132]
I haven't found a documentation about the ransomware app. Surely it detects for certain patterns, but what happens if ransomware was detected?

If there is a real infection, what is the procedure who finally enables the client again (does the admin need to authorize that?)

And if it is a false positive, what can I do?
A user actually has his problem -> https://help.nextcloud.com/t/constantly-being-warned-that-a-file-is-ransomware-that-is-neither-ransomeware-nor-even-exists-on-my-server-anymore/44999

**Comment by MorrisJobke** [comment]
I guess you are referring to https://apps.nextcloud.com/apps/ransomware_protection

Then @nickvergessen might help with that.

**Comment by nickvergessen** [comment]
I'm not sure it belongs into the normal docs, but yeah a readme should be added to the repo:
https://github.com/nextcloud/ransomware_protection/

**Comment by nickvergessen** [comment]
Explanation at https://github.com/nextcloud/ransomware_protection/#how-the-app-works
