### ISSUE TITLE
…no upgrade instructions here at all, just a lengthy list of version changes.

### ISSUE THREAD

**Issue by LanceHaverkamp** [nextcloud/documentation#11356]
I'm looking at the page called: Upgrade to Nextcloud 26

There are no upgrade instructions here, apart from one line that says “Make sure your appinfo/info.xml allows for Nextcloud 26.”, other than that one line, there are no upgrade instructions here at all, just a lengthy list of version changes.

…followup: I also looked at the upgrade guide for 25 & 27; neither of these have any instructions either--just that same one line about changing the max version number. Where are the actual instructions?

**Comment by joshtrichards** [comment]
You didn't share the URL of the page you're at, soI can only guess. It sounds like you're looking at the *Dev Manual*. Go to https://docs.nextcloud.com and select the *Admin Manual*.

In general, update instructions are covered in the *Maintenance* section.

Please direct follow-ups to the Nextcloud Help Forum - https://help.nextcloud.com
