### ISSUE TITLE
Add mjs to upgrade guide for admins

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/documentation#11429]
### Thanks for helping improve our documentation! 

* There is always room for improvement!
* All contributions (changes and change ideas) - from the largest **to the tiniest** - help make Nextcloud better and easier to use!

---

Nextcloud 27 added support for `mjs` and with Nextcloud 28, some core components started to make use of it. This was a breaking change for webserver setups without Apache2 or when not making use of `.htaccess`, since requests to those files were rewritten to `index.php`. It would be beneficial to add a hint for admins to the upgrade guide of the docs: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html 

---

#### Notes

* Please be patient: this is a large open source project that is overseen by a mixture of volunteers and non-volunteers which are all ultimately busy.
* If your suggestion is a troubleshooting scenario or one you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
  - *Then* return here to bring back your experience to help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

#### Protip: If you want to help move things along (or just help out in other ways too) here are some suggestions:
* Look for areas where you can assist - even seemingly unrelated areas - *because doing so frees up resources for your favorite topics and ideas*.
* Submit a proposed change - that attempts to addresses your issue - as a pull request.
* Participate in a discussion on some other unresolved [submitted idea ("issues")](https://github.com/nextcloud/documentation/issues) to help move it along.
* Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

**Comment by joshtrichards** [comment]
I think you meant add it here:

https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_28.html

(for the admin guide not dev guide)

Since there's already a small note about in in the NC27 upgrade guide we can probably lift that as a base:

https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

Maybe expand it a bit too - to make it clear it's applicable for those not using the .htaccess approach too?

**Comment by joshtrichards** [comment]
This proposed PR could help too... at least as long as the setup checks never end up requiring `.mjs` file support. :-)

nextcloud/server#42436

**Comment by susnux** [comment]
I do not think we need this in the 28 update guide as it was introduced in 27 and already included in the update guide, so we would copy it from 27 to 28?

See: https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html#web-server-configuration

**Comment by MichaIng** [comment]
Ah right, the admin docs are better suited. I followed the link on the old GitHub admin&dev issue which lead to the developer docs only.

Hmm, the entry for NC27 is probably a little too small/unclear, referring to Nginx config only. This was not an issue with NC27, but with NC28 this change is just mandatory for all webserver setups which do not use `.htaccess` . So IMO it still makes sense to add an entry to the NC28 page again, this time clear as a breaking change for potentially all webservers.
