### ISSUE TITLE
Code tag not wrapped

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/documentation#1148]
If we have a code tag which is too long, it does not get line wrapped.

![image](https://user-images.githubusercontent.com/5836855/51172254-20cc8e00-18b3-11e9-8cab-f65af6c14b72.png)

**Comment by MorrisJobke** [comment]
@skjnldsv Any idea? Maybe we should also fix this upstream 😉 

Or could this be done in another way, because I have seen code that was in a scrollable box .

**Comment by joshtrichards** [comment]
This looks better today:

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html?highlight=chunks#uploading-chunks

While part of the improvement is due to the addition of shell line continuation, the box is also scrollable now.

Okay to close?
