### ISSUE TITLE
Document `occ encryption:drop-legacy-filekey`

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/documentation#11539]
The `occ` command added in nextcloud/server#38080 (released in v27) needs to be documented:

> Scan the files for the legacy filekey format using RC4 and get rid of it (if master key is enabled)

---

#### Notes

* Please be patient: this is a large open source project that is overseen by a mixture of volunteers and non-volunteers which are all ultimately busy.
* If your suggestion is a troubleshooting scenario or one you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
  - *Then* return here to bring back your experience to help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

#### Protip: If you want to help move things along (or just help out in other ways too) here are some suggestions:
* Look for areas where you can assist - even seemingly unrelated areas - *because doing so frees up resources for your favorite topics and ideas*.
* Submit a proposed change - that attempts to addresses your issue - as a pull request.
* Participate in a discussion on some other unresolved [submitted idea ("issues")](https://github.com/nextcloud/documentation/issues) to help move it along.
* Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

**Comment by joshtrichards** [comment]
Cc: @come-nc

**Comment by sorbaugh** [comment]
@come-nc consensus is to reword "Encrypting files increases their size by roughly 35%" to "Encryption files generate a slight overhead in size by ~1% (35% before Nextcloud X)"

and mention the command that can migrate it for some versions^^

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html

**Comment by joshtrichards** [comment]
X = v25 (nextcloud/server#32110)

**Comment by AkechiShiro** [comment]
Thanks a lot to everyone involved !
