### ISSUE TITLE
Office Installation example with Docker says to download wrong app.

### ISSUE THREAD

**Issue by prairietree** [nextcloud/documentation#11559]
On https://docs.nextcloud.com/server/latest/admin_manual/office/example-docker.html#configure-the-app-in-nextcloud it says to Install the “Collabora Online app”. I do not see that app. I see only the "Collabora Online - Built-in CODE Server". But I believe that is the wrong app if you installed Collabora in a docker container. I believe the one we would need is called " Nextcloud Office". Is that correct? 

Thanks for your help.

**Comment by joshtrichards** [comment]
Correct. Fix in progress. Thanks for reporting!
