### ISSUE TITLE
Remove bookmarks

### ISSUE THREAD

**Issue by JSoko** [nextcloud/documentation#118]
Bookmarks is a community app. It was once shipped with core, so it should be removed from the docs, as @BernhardPosselt mentioned [here](https://help.nextcloud.com/t/bookmark-app-doesnt-accept-any-bookmarks/2251/5).

https://github.com/JSoko/nextcloud-documentation/commit/79280bc4ccff534dd9cae26fc240dd00d0966664
https://github.com/JSoko/nextcloud-documentation/commit/92068e7aa35bc37f2bad06a362aeb5df2ebed1e9

**Comment by MorrisJobke** [comment]
Fixed and backported to stable9 and stable10 :)

Thanks :)
