### ISSUE TITLE
Nextcloud 29: Dein Datenverzeichnis und deine Dateien sind wahrscheinlich vom Internet aus erreichbar. 

### ISSUE THREAD

**Issue by jliknil** [nextcloud/documentation#11830]
Good morning,
please excuse me...the bad english...
With NC29 i have an error:
Dein Datenverzeichnis und deine Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht. Es wird dringend empfohlen, deinen Webserver dahingehend zu konfigurieren, dass das Datenverzeichnis nicht mehr vom Internet aus erreichbar ist oder dass du es aus dem Document-Root-Verzeichnis des Webservers herausverschiebst.

### Thanks for helping improve our documentation! 

* There is always room for improvement!
* All contributions (changes and change ideas) - from the largest **to the tiniest** - help make Nextcloud better and easier to use!

---

For several times i use NC.
When updating from 28.0.5 -> 29.0.0. the error occurs.
With my backup, i roll back to 28.0.with no errors.
Is ist a bug?
I read a lot of ideas to solve the problem, but can't solve...
(config.php with several possibilities to change, apache2-config with changes...)
Any ideas?
Thanks 
yours Jens

---

#### Notes

* Please be patient: this is a large open source project that is overseen by a mixture of volunteers and non-volunteers which are all ultimately busy.
* If your suggestion is a troubleshooting scenario or one you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
  - *Then* return here to bring back your experience to help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

#### Protip: If you want to help move things along (or just help out in other ways too) here are some suggestions:
* Look for areas where you can assist - even seemingly unrelated areas - *because doing so frees up resources for your favorite topics and ideas*.
* Submit a proposed change - that attempts to addresses your issue - as a pull request.
* Participate in a discussion on some other unresolved [submitted idea ("issues")](https://github.com/nextcloud/documentation/issues) to help move it along.
* Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

**Comment by kesselb** [comment]
Hi,

Unclear to me if that's a bug or not. 

Please head over to https://help.nextcloud.com/ and ask for help over there.

For bugs related to Nextcloud the documentation repo is usually the wrong place.
