### ISSUE TITLE
-white icon version for icon-view elements is not necessary

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/documentation#1187]
The icon-view icons are already white and have a drop shadow, because they are made to work on any background. We shouldn’t generate -white versions for them, as they have the infamous white shadow. ;)
![icon-view icons with white shadow](https://user-images.githubusercontent.com/925062/51529473-08bbb800-1e39-11e9-861b-e2903b4a187d.png)

What do you think @nextcloud/designers?

**Comment by skjnldsv** [comment]
@jancborchardt this is a server issue then :)
Do you wish:
1. to have the icon set to dark as well (a proper invert, because seeing your screenhsot I can see that the shadow is inverted but not the main colour)
2. or to not generate white versions of those icons? :)

**Comment by jancborchardt** [comment]
> 2. or to not generate white versions of those icons? :)

This please. :) Because as said, "they are made to work on any background" (as they need to work on top of images in the slideshow), and thus we don’t need a white version at all.

Thank you! And yeah, wasn’t sure if it’s server or docs. :)
