### ISSUE TITLE
Can I or can't I change the 4 byte character database?

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [nextcloud/documentation#11914]
The documentation at https://docs.nextcloud.com/server/23/admin_manual/configuration_database/mysql_4byte_support.html says:

> 5. Set the mysql.utf8mb4 config to true in your config.php:  $ sudo -u www-data php occ config:system:set mysql.utf8mb4 --type boolean --value="true"

When I did that, I got a message that contradicts itself:

```bash
17:15:15 $ sudo -u www-data php occ config:system:set mysql.utf8mb4 --type boolean --value="true"
Nextcloud is in maintenance mode, hence the database isn't accessible.
Cannot perform any command except 'maintenance:mode --off'

System config value mysql.utf8mb4 set to boolean true
```

On one hand side, it says, I can't do anything except disabling maintenance mode, on the other hand side, it says it set the boolean to `true`. So, what is correct? If the code is not changed, the documentation should at least mention that I get a warning.

**Comment by kesselb** [comment]
Thanks for your report.

I changed the wording for 26 and 27 a while ago: https://github.com/nextcloud/server/pull/37925.
