### ISSUE TITLE
Update Android documentation

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/documentation#12]
Not sure which one is the right one to use in this case, but looking at:
https://docs.nextcloud.org/server/9/developer_manual/android_library/index.html

I would like to fix several things here:
* Remove the CLA paragraphs
* rename "junior job" to "starter issue" plus the underlying hyperlink
* change all links to Nc

Same applies for https://docs.nextcloud.org/server/9/developer_manual/android_library/library_installation.html
* change links to Nc
* add chapter describing the jitpack alternative on how to include the Nc lib as in

add
```
compile 'com.github.nextcloud:android-library:-SNAPSHOT'
```
to your ```build.gradle``` to get the latest head or refer to any fixed version you might want to use specifically.

**Comment by AndyScherzinger** [comment]
I already created a branch: https://github.com/nextcloud/documentation/tree/android/developer_manual I just need a GO :)

**Comment by mar1u5** [comment]
GO 😉

**Comment by nickvergessen** [comment]
Closing since it was merged

@AndyScherzinger does this need backporting to stable9?

**Comment by AndyScherzinger** [comment]
Don't think so, it is just for Android development :)
