### ISSUE TITLE
Undefined CSS variable --border-width-element

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#12065]
### Thanks for helping improve our documentation! 

* There is always room for improvement!
* All contributions (changes and change ideas) - from the largest **to the tiniest** - help make Nextcloud better and easier to use!

---

![image](https://github.com/user-attachments/assets/34cc6c4a-9552-43cc-9fc0-185e526ba46e)

documented at https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/css.html#element-structure-variables does not exist.
I found --border-width-input. Was this renamed?

---

#### Notes

* Please be patient: this is a large open source project that is overseen by a mixture of volunteers and non-volunteers which are all ultimately busy.
* If your suggestion is a troubleshooting scenario or one you're not 100% certain about, please post for feedback on the [Nextcloud Help Forum](https://help.nextcloud.com) first.
  - *Then* return here to bring back your experience to help improve the documentation for clarity, etc. (and link back to the forum discussion in your report!)

#### Protip: If you want to help move things along (or just help out in other ways too) here are some suggestions:
* Look for areas where you can assist - even seemingly unrelated areas - *because doing so frees up resources for your favorite topics and ideas*.
* Submit a proposed change - that attempts to addresses your issue - as a pull request.
* Participate in a discussion on some other unresolved [submitted idea ("issues")](https://github.com/nextcloud/documentation/issues) to help move it along.
* Post a comment or review on someone else's [proposed change ("pull request")](https://github.com/nextcloud/documentation/pulls) to help move it along.

**Comment by ChristophWurst** [comment]
@marcoambrosini do you know more?

**Comment by marcoambrosini** [comment]
I created --border-width-input but didn't know about these 2 undefined values
