### ISSUE TITLE
Where to run migration commands?

### ISSUE THREAD

**Issue by Peanut4287** [nextcloud/documentation#12155]
Where am I supposed to run the documented migration [commands](https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html#console-commands)?

I'm using the [Nextcloud development environment on Docker Compose](https://github.com/juliushaertl/nextcloud-docker-dev).

**Comment by hamza221** [comment]
Hello, 
For future reference please use the forum for general questions https://help.nextcloud.com/ . 
You can use it in the docker exec, in the base folder of Your instance  `/var/www/html`
by running  `occ [command name]`
