### ISSUE TITLE
Missing 'new' keyword in code sample

### ISSUE THREAD

**Issue by tjaisson** [nextcloud/documentation#1233]
In the code sample about [Public page templates](https://github.com/nextcloud/documentation/blob/master/developer_manual/app/requests/controllers.rst#public-page-templates) there is a missing 'new' at PublicTemplateResponse class creation.

**Comment by MorrisJobke** [comment]
> In the code sample about [Public page templates](https://github.com/nextcloud/documentation/blob/master/developer_manual/app/requests/controllers.rst#public-page-templates) there is a missing 'new' at PublicTemplateResponse class creation.

Could you click the little pencil icon on that linked page and hand in your request as actual changes? Because I could not spot the missing part 🙈 That would help us a lot 😃 Thanks

**Comment by tjaisson** [comment]
I submited #1234 
I hope this helps.
