### ISSUE TITLE
Missing Nextcloud User Manual PDF file

### ISSUE THREAD

**Issue by shorty-look** [nextcloud/documentation#1258]
Hello.
This link not work fine: https://docs.nextcloud.com/server/stable/Nextcloud_User_Manual.pdf
I need User Manual in a PDF file for Nextcloud 15 version
Thanks.

**Comment by skjnldsv** [comment]
@MorrisJobke @blizzz ?

**Comment by MorrisJobke** [comment]
Broken due to usage of gifs ...

**Comment by MorrisJobke** [comment]
> Broken due to usage of gifs ...

See failing tests on docs repo.

**Comment by MorrisJobke** [comment]
> See failing tests on docs repo.

https://drone.nextcloud.com/nextcloud/documentation/2047/3

PR: https://github.com/nextcloud/documentation/pull/1221

**Comment by MorrisJobke** [comment]
Let's move this over to the documentation repo.

**Comment by shorty-look** [comment]
"Access forbidden" for Nexcloud 14 User Manual too: https://docs.nextcloud.com/server/14/Nextcloud_User_Manual.pdf 
Can you fix it, please?

Thanks.

**Comment by MorrisJobke** [comment]
> "Access forbidden" for Nexcloud 14 User Manual too:

We are aware and working on it.

**Comment by shorty-look** [comment]
thank you @MorrisJobke, I just wanted to inform you that there is the same problem for version 14 as well.
;)

**Comment by MorrisJobke** [comment]
Fixed via #1266
