### ISSUE TITLE
Documentation for Calendar and Contacts

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#127]
We should have an documentation for Calendar and Contacts. Therefore, we need some stuff. Feel free to add something 😁
- [x] Contacts
  - [x] Overview (#126)
  - [x] Add / Modify / Delete and Share Adressbooks 
  - [x] Add / Modify and Delete Contacts (Pictures, Adress, Groups, ...)
  - [x] CardDAV Backend Connect (Clients)
- [ ] Calendar
  - [ ] Overview
  - [ ] Add / Modify / Delete and Share Calendars 
  - [ ] Add / Modify / Delete Events (Name, Participants, Reminders, ...)
  - [x] CalDAV Backend Connect (Clients)

cc @hagengraf

**Comment by georgehrke** [comment]
- [ ] Calendar: add link to https://davdroid.bitfire.at/faq/entry/subscribe-ics-file/ for webcal in Android

**Comment by georgehrke** [comment]
@MariusBluem Do you need help with the calendar part? :)

**Comment by MariusBluem** [comment]
Documentation is something we need to discuss in the coming weeks @georgehrke 😉
Calendar is only one part of some big unmaintained documentation parts ... I'll keep you updated 🙈

cc @hagengraf

**Comment by georgehrke** [comment]
ping @MariusBluem :P

**Comment by MariusBluem** [comment]
Yeah ... I know 😉 Next week ... we will have something for Nextcloud 12 - I promise 😜

**Comment by MariusBluem** [comment]
Fix for Contacts is in: #397

**Comment by georgehrke** [comment]
ping @MariusBluem ;)

**Comment by MorrisJobke** [comment]
What is the status here?

**Comment by MariusBluem** [comment]
Status is calendar is missing ... I have the texts and some screenshots - will the invitation thing be in 14? @georgehrke

**Comment by MorrisJobke** [comment]
> Status is calendar is missing ... I have the texts and some screenshots - will the invitation thing be in 14? @georgehrke

Yes.

**Comment by skjnldsv** [comment]
@bencomp Please go ahead! :)

**Comment by bencomp** [comment]
@MariusBluem done! Great work!

**Comment by MariusBluem** [comment]
#1221 is a PR for our calendar docs (finally). Please review this draft and give some feedback :)
