### ISSUE TITLE
NC desktop client 2.5

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#1276]
It would be great to update the desktop client documentation, since there are a lot of new features:
https://help.nextcloud.com/t/nextcloud-desktop-client-2-5-is-out-with-end-to-end-encryption-new-login-flow-and-much-more/41132

**Comment by MorrisJobke** [comment]
There was the idea to integrate it right here - currently it's build from https://github.com/nextcloud/desktop/tree/master/doc and wasn't updated for a long time there :/

**Comment by MorrisJobke** [comment]
cc @camilasan @rullzer

**Comment by MorrisJobke** [comment]
The desktop client docs for 2.5 are in https://docs.nextcloud.com/desktop/2.5/ but they still lack the details.

**Comment by tflidd** [comment]
It's just a copy&paste? It says:

> The 2.4.0 release of the Nextcloud desktop sync client has many new features and improvements.

**Comment by MorrisJobke** [comment]
> It's just a copy&paste? It says:

cc @rullzer @camilasan

**Comment by tflidd** [comment]
There was some work on the desktop client documentation. Closing here.
