### ISSUE TITLE
May need to be fixed in mount guide webdav

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/documentation#1305]
may need to be fixed in mount guide webdav:
https://docs.nextcloud.com/server/15/user_manual/files/access_webdav.html

Creating WebDAV mounts on the Linux command line
...
![Screenshot_2019-03-13_21-27-30](https://user-images.githubusercontent.com/32108411/54305037-84371b80-45d7-11e9-9c60-54a7fadb2730.png)

URL without https://
replace with

https://example.com/nextcloud/remote.php/dav/files/USERNAME/`  /home/username/nextcloud
davfs user,rw,auto 0 0

and in this place:
![Screenshot_2019-03-13_22-04-28](https://user-images.githubusercontent.com/32108411/54307191-150ff600-45dc-11e9-86e2-792ac2a1c350.png)
like variant
$PathToMountPoint $USER $PASSWORD

**Comment by MorrisJobke** [comment]
@ivarvava Could I ask you to do the changes directly under this link: https://github.com/nextcloud/documentation/edit/stable15/user_manual/files/access_webdav.rst


I guess it's then easier for us to follow up and get this in.

Thank you very much already for this. :)

**Comment by lvarnava** [comment]
Donе.

**Comment by MorrisJobke** [comment]
> Donе.

Did you also open a PR for this, because I can't find it.
