### ISSUE TITLE
Help in Users Menu for Contacts and Calendar not working

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/documentation#132]
![bildschirmfoto vom 2016-08-22 08-20-17](https://cloud.githubusercontent.com/assets/3857906/17845319/4e96c3f2-6841-11e6-9f8b-c88109b58cf8.png)

Opening [documentation Wiki on Github](https://github.com/owncloud/documentation/wiki/Using-the-Contacts-App-in-ownCloud-9.0) in the NC results into a blank screen.

Opening in a new tab can find also nothing.

**Comment by MariusBluem** [comment]
Solved. Documentation for Calendar and Contacts comes very soon ;)

**Comment by Huster-at-github** [comment]
Thanks!

Is it possible to test such bugfixes in any betas?
