### ISSUE TITLE
Nginx configuration files swapped between webroot and subfolder ?

### ISSUE THREAD

**Issue by eogan** [nextcloud/documentation#1354]
Hello,

The nginx config file for webroot installation reads:
```
# Path to the root of your installation
root /var/www/nextcloud/;
```

The nginx config file for subdir installation reads:
```
# Path to the root of your installation
root /var/www/;
```
It seems to me the two files were swapped. What do you think ?

**Comment by skjnldsv** [comment]
Hello! :)
No, this is ok. Since the subdir is `nextcloud` the root is indeed `/var/www` :wink:
