### ISSUE TITLE
Documentation wrongly states libapache2-mod-php7.2 provides certain PHP modules

### ISSUE THREAD

**Issue by msplival** [nextcloud/documentation#1358]
The documentation (https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/source_installation.rst) states that the libapache2-mod-php7.2 provides certain php modules, like bcmath, bz2, dba,  ereg, .... 

This is not true for Ubuntu Bionic install. Now, is this list required php modules wrong, or those should be also installed?

**Comment by MorrisJobke** [comment]
Good question - we need the list at the top of the page. So maybe we just remove the section from the install steps and check what modules need to be installed in 18.04 additionally now that it is not installed as a dependency anymore.
