### ISSUE TITLE
https://github.com/nextcloud/documentation/wiki is not available

### ISSUE THREAD

**Issue by nursoda** [nextcloud/documentation#1359]
There are several links to https://github.com/nextcloud/documentation/wiki (e.g. concerning alternate web servers, and from https://github.com/nextcloud/documentation itself!) but if I load that URI, I get redirected to https://github.com/nextcloud/documentation - was the wiki disabled?

**Comment by skjnldsv** [comment]
@nursoda indeed, wiki is disabled
Can you link or edit out the wrong links to the wiki? :)

**Comment by nursoda** [comment]
I would not know what to do with things like this: "The documentation Wiki is available for tips, tricks, edge cases, and anyone who wants to contribute more easily, without having to learn Git and Sphinx." - Were those documents moved somewhere? Just deleted? This sentence is from the main page https://github.com/nextcloud/documentation itself! Another I found here: https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#other-web-servers

I never forked yet but probably can. Just unsure whether to just delete links. I mean, personally I was looking for info in lighttpd (in the -now deactivated- wiki) ... So at least one should be pointed to a page that tells users that the wiki HAS been disabled since there will be many search machine results pointing to the wiki. Just deactivating it is somewhat ... unexpected.

**Comment by MorrisJobke** [comment]
cc @rullzer @jospoortvliet

**Comment by MorrisJobke** [comment]
@nickvergessen just enabled the wiki again. Unfortunately there isn't much in there. Also adding yet another place where information can be found doesn't make it more accessible. Maybe we should just change that part in the docs and add there a section with a collection of edge cases that are there with a big disclaimer. So that we don't have forums, wiki and docs.

**Comment by skjnldsv** [comment]
I think it should remain closed in favour of the docs :)

**Comment by nursoda** [comment]
OK, but I still don't know whether I should only remove all links to the wiki I encounter. What shall be done with the content referenced to (that might have been in the wiki), like "How to install on alternate web servers"?

**Comment by MorrisJobke** [comment]
> (that might have been in the wiki)

At least there was only a page about Nextcloud 10 in there with 2 bullet points.



> like "How to install on alternate web servers"?

I could not find where it was hosted - maybe somebody deleted it in the past 😢

**Comment by nursoda** [comment]
Created #1365
