### ISSUE TITLE
Incorrect spelling

### ISSUE THREAD

**Issue by cegsdesk** [nextcloud/documentation#136]
In the beginning of your description for APPS->roundcube you have "Embedd"...should be "Embed".

I've just downloaded the Nextcloud package and just beginning to look through it.  I have this thing about spotting typos...they tend to jump out at me.

I do some side work as an editor/proofreader for Twin Dreams Publishing and sometimes it's a force of habit spotting typos.

**Comment by MorrisJobke** [comment]
That is the description the app developer controls. This is a 3rdparty app and we can't change the text there. Maybe try to contact the author directly. https://apps.owncloud.com/content/show.php/roundcube?content=151523

Thanks for spotting anyway :)
