### ISSUE TITLE
We are lacking Release Notes 

### ISSUE THREAD

**Issue by blizzz** [nextcloud/documentation#141]
Currently our documention pages on Release Notes say "tbd":

https://docs.nextcloud.com/server/9/admin_manual/release_notes.html
https://docs.nextcloud.com/server/10/admin_manual/release_notes.html

Basically, what I think should/could be done, or rather is a starting point, is to go throw the PRs of server and app branches, is sum app essential changes that happened in between.

**Comment by jospoortvliet** [comment]
Need to add: https://github.com/nextcloud/server/issues/2399

**Comment by MorrisJobke** [comment]
They can be found in here: https://nextcloud.com/changelog/
