### ISSUE TITLE
Background jobs wont run - Nextcloud 15

### ISSUE THREAD

**Issue by rojz** [nextcloud/documentation#1475]
Hello,

I have updated our Nextcloud server from 14 up to 15 and after that our Background jobs stopped working. Any clue what it could be?

System: Ubuntu 16.04 LTS
PHP: 7.3.5
mysql: Ver 15.1 Distrib 10.1.40-MariaDB
Apache: 2.4.18

Error:
![Error](https://user-images.githubusercontent.com/30040797/58867910-90ed7c00-86bb-11e9-8722-f756871a91b2.png)

Crontab:
![crontab](https://user-images.githubusercontent.com/30040797/58867917-93e86c80-86bb-11e9-9b47-1e4f29a20d9e.png)

Nextcloudcron.service:
![nextcloudcron service](https://user-images.githubusercontent.com/30040797/58867944-a1055b80-86bb-11e9-9311-56793e0cd57f.png)

Nextcloudcron.timer:
![nextcloudcron timer](https://user-images.githubusercontent.com/30040797/58867959-a6fb3c80-86bb-11e9-8369-348f6054ee02.png)

I have tried to change everything but no luck.

Any ideas?

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

This repository is used for the documentation.
Open a ticket there and post your systemctl logs as well ;)
