### ISSUE TITLE
App Tutorial misses part about database.xml?

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/documentation#1479]
Dear Devs and Docs,

i tried to get into Nextcloud app developement but currently am already stuck near the beginning of the Database Section of the [Tutorial](https://docs.nextcloud.com/server/16/developer_manual/app/tutorial.html#database)

Perhaps i didnt read it correctly, but i didnt find information about the initial database.xml. Only when i took that from [here ](https://github.com/nextcloud/app-tutorial/blob/master/appinfo/database.xml) it created the initial table

Even afterwards the [next steps](https://docs.nextcloud.com/server/16/developer_manual/app/tutorial.html#database) didnt seem to fit about the namespace or the table names that should be used in `ownnotes/lib/Migration/Version000000Date20181224140601`

The thing is, i think i usually really like those step-by-step guides to get into already existing projects. Otherwise one can feel so lost :-)

Thanks in advance

**Comment by skjnldsv** [comment]
Hello!
We do not use the database.xml file anymore.
Migration path are the way to go :)
