### ISSUE TITLE
Make documentation structure compatible with permalinks

### ISSUE THREAD

**Issue by dacoex** [nextcloud/documentation#1481]
**Problem:**
* The current structure makes it very difficult to link permanently to the latest / stable version of the docs because the path changes with each new release as the VERSIONNUMBER increases:
`https://docs.nextcloud.com/server/16/user_manual/`
`https://docs.nextcloud.com/server/{VERSIONNUMBER}/user_manual/`

* Currently, it is very hard to find the translated versions, e.g. https://docs.nextcloud.com/ does not link to the German version: https://docs.nextcloud.com/server/16/benutzerhandbuch/contents.html

**Solution:**
It would be great to have a structure which allows permanent linking like many software packages do:

The ideal paths would look like:
https://docs.nextcloud.com/server/LATEST/{LANGUAGE}/user_manual/
https://docs.nextcloud.com/server/STABLE/{LANGUAGE}/user_manual/
https://docs.nextcloud.com/server/16/{LANGUAGE}/user_manual/

**Impact**
Changing the paths would allow the server admins to provide manuals which always reference the right pages in the user manual for the users on theirs servers.

**Comment by MorrisJobke** [comment]
latest and stable is already there. Latest links to the current master and stable to the current stable release of the docs.

https://docs.nextcloud.com/server/latest/admin_manual/
https://docs.nextcloud.com/server/stable/admin_manual/

**Comment by dacoex** [comment]
@MorrisJobke 

If I go on https://docs.nextcloud.com/
the 2 links you mentioned are not there.

This is why I created the issue.

**Comment by MorrisJobke** [comment]
> If I go on https://docs.nextcloud.com/
> the 2 links you mentioned are not there.

They are there once you entered any manual and use the bottom left version selector. We want to keep the landing page clean and straight forward. Those two links are more advanced ones.
