### ISSUE TITLE
Android docs miss the explanation of token / QR code based login

### ISSUE THREAD

**Issue by dacoex** [nextcloud/documentation#1483]
https://docs.nextcloud.com/android/android_app.html#connecting-to-your-nextcloud-server

**Comment by tflidd** [comment]
The code was implemented here: https://github.com/nextcloud/server/issues/429
It seems to be on the personal security page where you set up app passwords.

**Comment by dacoex** [comment]
Yes, but the documentation of the server only has a section about ios.

The for some reason separated Android app documentation does not contain a description about the QR code based process

**Comment by skjnldsv** [comment]
If you have the time, you can also add this to our docs @dacoex :)

**Comment by joshtrichards** [comment]
Those outdated dedicated Android docs are gone .

And the user manual discussed QR code setup here now:

https://docs.nextcloud.com/server/latest/user_manual/en/groupware/sync_android.html?highlight=qr#synchronizing-with-android
