### ISSUE TITLE
Memchached configuration example in documentation wrong?

### ISSUE THREAD

**Issue by hoergen** [nextcloud/documentation#1484]
Hmm I tried to configure Nextcloud on my Debian system with memcached like in the documentation https://docs.nextcloud.com/server/16/admin_manual/configuration_server/caching_configuration.html

```
'memcache.local' => '\OC\Memcache\APCu',
'memcache.distributed' => '\OC\Memcache\Memcached',
'memcached_servers' => [
     [ 'server0.example.com', 11211 ],
     [ 'server1.example.com', 11211 ],
     [ 'server2.example.com', 11211 ],
 ],
```

But only with a localhost in it

```
'memcache.local' => '\OC\Memcache\APCu',
'memcache.distributed' => '\OC\Memcache\Memcached',
'memcached_servers' => [
     [ 'localhost', 11211 ],
 ],
```

But this leads all the time to a server error

When I changed the configuration to

```
  'memcache.local' => '\OC\Memcache\Memcached',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' => array(
               array('localhost', 11211),
                    ),
```
it works fine

**Comment by skjnldsv** [comment]
> But this leads all the time to a server error

What kind of error?

**Comment by hoergen** [comment]
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the webserver log.
```

**Comment by skjnldsv** [comment]
@hoergen I will need a more detail error. Either in the data/nextcloud.log or directly from your php logs :)

**Comment by hoergen** [comment]
I try .. not easy to find the correct line ;)

**Comment by hoergen** [comment]
Hmm I tried to reproduce it, but now the configuration example in the documentation works. Maybe because I use mod_cache and there was an other error?

I will keep the documented configuration in my nextcloud and watch it. If it occurs again,  I will reopen this issue. But thank you so far 🌻

**Comment by TonyGravagno** [comment]
I've reproduced this issue and can submit a PR, but the problem is with a [single extra line](https://github.com/nextcloud/documentation/commit/41a4bd9a0af756993a0b2d74cda6a72e6caa697b#diff-48dc187eeb03371b5ad6886b33043bf060884809c1d51a3568c5d29e40e3bf13R99) that should not have been added:

```
'memcache.local' => '\OC\Memcache\APCu',
'memcache.distributed' => '\OC\Memcache\Redis',
```

With memcache.local specified, the memcache.distributed line causes the error. Just remove that one line.
