### ISSUE TITLE
Update English PIM page for Android

### ISSUE THREAD

**Issue by dacoex** [nextcloud/documentation#1492]
the English page needs to be updated to reflect token-based access & auto-discovery from the Nextcloud app (it automatically enters the server id).

Reference:
https://github.com/nextcloud/documentation/blob/master/user_manual/pim/sync_android.rst

**Comment by MorrisJobke** [comment]
cc @rullzer @ChristophWurst

**Comment by joshtrichards** [comment]
Appears now at: https://docs.nextcloud.com/server/latest/user_manual/en/groupware/sync_android.html

Fixed long ago but this issue just wasn't closed out.
