### ISSUE TITLE
SFTP is not ftp over ssh tunnel

### ISSUE THREAD

**Issue by mekineer** [nextcloud/documentation#1494]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/external_storage/sftp.html
Says: "Nextcloud’s SFTP (FTP over an SSH tunnel) "

However,

https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol
Says: “SFTP is not FTP run over SSH, but rather a new protocol designed from the ground up by the IETF ECSH working group. It is sometimes confused with Simple File Transfer Protocol.”

This was corroborated on:
https://help.nextcloud.com/t/sftp-documentation/54930

**Comment by skjnldsv** [comment]
@mekineer thanks for reporting this :)
Could you maybe change it and suggest a new pull request?

**Comment by mekineer** [comment]
When I tried to edit, github said I needed to fork.  Besides, I'm no expert on the topic.

**Comment by skjnldsv** [comment]
> github said I needed to fork

Yes, you need to fork and it will then create a pr based on the changes made on your fork :)

**Comment by mekineer** [comment]
I was unable to fork, probably because I don't know how or my browser is too old.  There is no fork button, and the "Propose File Change" button does not become active even after filling the form.  This is the change I wanted to make, replacing the first paragraph:

Nextcloud's SFTP backend supports both password and public key authentication.
SFTP is not FTP run over SSH, but rather a new protocol designed from scratch
by IETF. The SFTP protocol allows for a range of operations on remote files,
engaging the remote file system as if it were native.
