### ISSUE TITLE
App Tutorial Doc misses Migration .php filename extension

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/documentation#1500]
Following the tutorial at https://docs.nextcloud.com/server/15/developer_manual/app/tutorial.html..

..this does NOT work. No Migration is being started:
> by creating a file ownnotes/lib/Migration/VersionXXYYZZDateYYYYMMDDHHSSAA, so for example ownnotes/lib/Migration/Version000000Date20181224140601

.. while this DOES work and the table "notes_meta" is created:
> by creating a file ownnotes/lib/Migration/VersionXXYYZZDateYYYYMMDDHHSSAA**.php**, so for example ownnotes/lib/Migration/Version000000Date20181224140601**.php**

took me some time to figure that out :-(

**Comment by skjnldsv** [comment]
@githubkoma Hi!
COuld you maybe edit the documentation? :)
That would help us improve! :muscle: :hugs:
