### ISSUE TITLE
App Tutorial Doc references different table in NoteMapper.php

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/documentation#1501]
Following the tutorial on https://docs.nextcloud.com/server/15/developer_manual/app/tutorial.html#database it states for NoteMapper.php:
>     public function __construct(IDbConnection $db) {
>         parent::__construct($db, 'ownnotes_notes', Note::class);
>     }

results for me in "notes could not be loaded"

looks like that table never has been defined within the tutorial documentation?
the only table that has been instantiated within the migration-steps was "notes_meta"..

Getting a bit desperate while trying to follow this tutorial..

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
@githubkoma could you post the full error stack trace please? :)

**Comment by gladed** [comment]
Something like this:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.ownnotes_notes' doesn't exist

...nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53
...nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
...nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1015
...nextcloud/lib/private/DB/Connection.php:216
...nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
...nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php:214
...nextcloud/lib/public/AppFramework/Db/QBMapper.php:120
...nextcloud/apps/budget/tests/Integration/BudgetIntegrationTest.php:44
```

At https://docs.nextcloud.com/server/15/developer_manual/app/tutorial.html#database the tutorial tells you to create a migration step for creating `notes_meta` but it doesn't match the Entity (different fields) and Mapper (different table, `ownnotes_notes`) created later in the exact same section.

This seems to be the case in `latest` as well.

**Comment by skjnldsv** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
Yes, fix is in https://github.com/nextcloud/documentation/pull/1582 for the documentation and https://github.com/nextcloud/app-tutorial/pull/5 for the tutorial
