### ISSUE TITLE
PDF version of Admin & User manual

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/documentation#155]
Hi,
since many people going "online" only, there are many people around, who love to hold a "printed" version an "old fashion" paper in its hands to read and study! The rivaling OwnCloud project provides a pdf - version of its admin manual for "major " releases. Are there any tools scripts, etc. available to generate a pdf - version of the "online" manual ?

regards, hitam 4450

**Comment by mar1u5** [comment]
You can download generated PDFs over here already 😉 https://docs.nextcloud.com

https://docs.nextcloud.com/server/10/Nextcloud_User_Manual.pdf

**Comment by hitam4450** [comment]
Thanks for the Links !  
Will the links be available in the admin section of NC ??
reagrds, hitam4450

**Comment by hitam4450** [comment]
Hi, on all documents the OwnCloud Logo ist still there and not the NextCloud logo !

regards, hitam4450

**Comment by mar1u5** [comment]
> Will the links be available in the admin section of NC ??

We are currently linking directly to the embedded documentation of Nextcloud and there are no links to the PDFs. I don't know whether this is necessary ;) ... Feel free to open a new issue on that.

> Hi, on all documents the OwnCloud Logo is still there and not the NextCloud logo !

Please open an separate issue on that ... But I have seen that you have already done this 😉 https://github.com/nextcloud/documentation/issues/156

**Comment by Huster-at-github** [comment]
I need the version for 13 to deploy it to my users

**Comment by Huster-at-github** [comment]
It is not acceptable that users find a version 8 or 9 or whatever in their root directory.

**Comment by MariusBluem** [comment]
https://docs.nextcloud.com/server/13/Nextcloud_User_Manual.pdf
https://docs.nextcloud.com/server/13/Nextcloud_Server_Administration_Manual.pdf
