### ISSUE TITLE
Doc: Cron verifying copy paste error

### ISSUE THREAD

**Issue by lenhart** [nextcloud/documentation#1552]
After getting a notification that cron does not seem to work with the nextcloud config, I revisited the cron section here:
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/background_jobs_configuration.html#cron

The part to verify the cron setup seems to be copied from the above configuration. 
`# crontab -u www-data -e`
`*/5  *  *  *  * php -f /var/www/nextcloud/cron.php`

Should this be just the 
`php -f /var/www/nextcloud/cron.php` 
command for the check? 

Also what is it about the `crontab -u www-data -e` line commented out? A comment might be beneficial here (that this is the command to access the crontab for the www user)

Thanks for the work

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Nonetheless, as this is a simple answer, let me guide you there.
For any other questions, open it on the forums please :)

`crontab -u www-data -e` means you need to run it to access the cron table editor.
Run this, then add the `*/5 * * * * php -f /var/www/nextcloud/cron.php` at the end of the file :)

**Comment by lenhart** [comment]
Hi skjnldsv,
thank you for the clarifications. However this ticket was not really meant to get support, but to improve the docs.
I am however not sure what the right content is, otherwise I would have suggested something or opened a pull request. Sorry if I did not make this clear. My points are:

- The crontab content is displayed twice, instead of the supposedly comment to verify the setup.

- With your affirmation that the `crontab -u www-data -e` is the command to get the proper crontab file, I would suggest to either seperate this from the content to insert into the file or to exchange the `#` with a `$` or whatever is used in the documentation for commands, because right now it looks as if the command is a crontab file comment.

If this still is better located in the forums I can repost it there, but I'd rather keep things simple :-)

**Comment by skjnldsv** [comment]
> * The crontab content is displayed twice, instead of the supposedly comment to verify the setup.

What do you mean by that?  :)

> * With your affirmation that the `crontab -u www-data -e` is the command to get the proper crontab file, I would suggest to either seperate this from the content to insert into the file or to exchange the `#` with a `$` or whatever is used in the documentation for commands, because right now it looks as if the command is a crontab file comment.

Ah yes, well it's a [common habit](https://wiki.archlinux.org/index.php/Xorg#Manual_configuration) that edited files have the first line containing either the command to edit it or the path of the file.
![Capture d’écran_2019-07-07_22-44-23](https://user-images.githubusercontent.com/14975046/60773649-d19c4300-a108-11e9-8366-7bf561c068d5.png)


But I completely agree with you, any update of a potential confusing doc is a good thing to do!

**Comment by lenhart** [comment]
Hi, thanks again for the reply. I was familiar with the path comment, but have not seen the edit command included. Yet something new :-) 

And I have to admit that I now found that the section is not a duplicate at all but the last parameter to crontab is changed from -e to -l...  for reference this is the section from the docs: 

```

To run a cron job on a *nix system, every 5 minutes, under the default Web server user (often, www-data or wwwrun), you must set up the following cron job to call the cron.php script:

# crontab -u www-data -e
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php

You can verify if the cron job has been added and scheduled by executing:

# crontab -u www-data -l
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php
```

Ok, now I can reverse engineer what it does, but this might confuse more people than me.

I suggest changing the second part to something like:

````

You can verify if the cron job has been added and scheduled by executing:
# crontab -u www-data -l

The  added cron job now appears at the end of the output.

````
This still leaves me a bit unsatisfied though. Crontab does parse the format  of the entered line, but does not catch errors in the path.. for instance if someone installed the nextcloud somewhere else and forgot to modify the path or added a typo (while figuring out how to exit vim)  .. then the cronjob is verified and scheduled but still invalid.. When I read verified I thought more of executed which is not the case here.. 

Do you have any thoughts on this? Otherwise you can close the issue again, probably the forums would have been the proper place to clear my confusion - sorry about that - but maybe we can make the docs more explicit in the progress.. 
Thanks!

**Comment by skjnldsv** [comment]
Any kind of readability improvement on our docs is good :)
Could you open a pull request for this fix?

**Comment by tflidd** [comment]
The fixing PR https://github.com/nextcloud/documentation/pull/1614 was merged. Closing.
