### ISSUE TITLE
Documentation on Projects missing

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/documentation#1557]
The documentation lacks any documentation on Projects which had been introduced with Nextcloud 16.

How is the feature to be used? 
What are the limitations?
Are there any APIs available?

**Comment by skjnldsv** [comment]
Pinging Dr @juliushaertl ! :man_health_worker:

**Comment by Xuno** [comment]
[https://docs.nextcloud.com/server/16/developer_manual/app/requests/container.html](url)
**Dependency Injection and the art of Services and Containers Tutorial** - video link missed

**Comment by wiswedel** [comment]
> [https://docs.nextcloud.com/server/16/developer_manual/app/requests/container.html](url)
> **Dependency Injection and the art of Services and Containers Tutorial** - video link missed

@Xuno Did you post in the wrong issue?
