### ISSUE TITLE
NextCloud Logo Missing in Documentation

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/documentation#156]
Hi, 

on all NextCloud Version 10 PDF documents the **OwnCloud** Logo is still there and not the **NextCloud** logo !

regards, hitam4450

**Comment by mar1u5** [comment]
Branding is not ported to `stable10`. It is in `stable9` ... Seems to be forgotten 😅

**Comment by mar1u5** [comment]
Seems to be ported 😁 ...so maybe something with building? The logo-files seem to be rebranded in `stable9` **and** `stable10`. 

Could you take a look @hagengraf 😉

**Comment by hitam4450** [comment]
Sample image:

![nc10admin](https://cloud.githubusercontent.com/assets/9738727/18231075/553223b0-72ae-11e6-95dc-0e5452ba2ec8.png)

**Comment by MorrisJobke** [comment]
This was a caching issue 😢 

I fixed it and it now shows the correct icon.
