### ISSUE TITLE
Missing Nextcloud 11 section

### ISSUE THREAD

**Issue by oparoz** [nextcloud/documentation#157]
Master is now NC 11 and we need the documentation for that to show up online.

**Comment by MariusBluem** [comment]
...we have not done this for `stable10` either. I know, that this was the normal behavior before the fork, but I don't know whether this makes sense currently 😁 

cc @nextcloud/documentation

**Comment by juliushaertl** [comment]
I guess this would make sense once the drone build is able to deploy changes automatically.

**Comment by MariusBluem** [comment]
Then ... Lets do this 😉 @MorrisJobke

**Comment by MorrisJobke** [comment]
> Master is now NC 11 and we need the documentation for that to show up online.

Why? We currently only provide documentation for released versions. Do we really need this for unreleased stuff?

**Comment by MariusBluem** [comment]
> Why? We currently only provide documentation for released versions. Do we really need this for unreleased stuff?

We had it before the fork 😜 I don't think it does sense anyway 😉

**Comment by oparoz** [comment]
>Why? We currently only provide documentation for released versions. Do we really need this for unreleased stuff?

Well, the main reason is that apps are supposed to be developed against master, so if they need to add a link to the documentation of the version they work on, then they will add the version number to that link.

I guess we can also make it so that links are 404 until the documentation goes live.

**Comment by MariusBluem** [comment]
The Development aspect is something I have not thought about :grin:

**Comment by nickvergessen** [comment]
@LukasReschke can you do this, or add me to the server?

**Comment by nickvergessen** [comment]
Updated: https://docs.nextcloud.com/

**Comment by oparoz** [comment]
Thank you Sir!
