### ISSUE TITLE
Delete Android user Manual

### ISSUE THREAD

**Issue by JSoko** [nextcloud/documentation#1583]
The Android user manual has not been maintained for 3 years. 
It should be deleted here:
https://docs.nextcloud.com/android/

No documentation may be better than an absolutely outdated one.

See also:
https://help.nextcloud.com/t/where-is-the-adroid-client-manual/58378
nextcloud/android#1522
nextcloud/android#4012

**Comment by rakekniven** [comment]
@tobiasKaminsky @AndyScherzinger This should definitely be removed. Your beautiful app is at v3.19 and website is naming v1.0.0. You are lightyears ahead of it 🚀 .

**Comment by tobiasKaminsky** [comment]
On https://docs.nextcloud.com I cannot find any reference to Android.
But you are right that https://docs.nextcloud.com/android still exists.
As this is must be somewhere in documentation repo, I will transfer this issue.

**Comment by tobiasKaminsky** [comment]
🙈 I am sorry for being unclear, I meant that I do not find the link to Android manual within our docs.nextcloud.com and therefore cannot try to remove it myself and/or ping my colleagues about it.

Can you give me an hint where you find a reference to our Android manual?

**Comment by rakekniven** [comment]
> Can you give me an hint where you find a reference to our Android manual?

No, not me. @JSoko How did you get there?

**Comment by tobiasKaminsky** [comment]
> Being just curious: Did you find content on your webserver? Why not just simply remove it?

I have no access to it, let me ask @nextcloud/infrastructure if they can check.
I first wanted to have a bit more info so that they do not need to go fully blind there…

**Comment by rakekniven** [comment]
Just used some search engines to URL and I found no page linking to it.

**Comment by rakekniven** [comment]
Ping 🏓

**Comment by JSoko** [comment]
Hello,

how I got there in August 2019, I Can't remember.

But it's still online under 
https://docs.nextcloud.com/android/

Goggle still finds it if I google for 
Nextcloud Android App Manual

so, it should be removed...

Ciao,
Joachim

**Comment by tobiasKaminsky** [comment]
> I have no access to it, let me ask @nextcloud/infrastructure if they can check.

ping @nextcloud/infrastructure

**Comment by tobiasKaminsky** [comment]
Pinging also @matthieugallien @blizzz directly.

**Comment by splitt3r** [comment]
It's still linked https://docs.nextcloud.com/server/latest/user_manual/en/ there.

**Comment by tflidd** [comment]
> It's still linked https://docs.nextcloud.com/server/latest/user_manual/en/ there.

I removed the link https://github.com/nextcloud/documentation/pull/8200

**Comment by rakekniven** [comment]
This could be considered as closed, or?

**Comment by tflidd** [comment]
I didn't check all links within the documentation. But for the google search, there is no old link on the top results.

I also backported the removal of last links for the currently supported version. From my point of view, this can be closed.
