### ISSUE TITLE
WebDAV: wrong URL in Documentation?!

### ISSUE THREAD

**Issue by flyinghuman** [nextcloud/documentation#1585]
### Expected behaviour
In the Documentation it states that the WebDAV URL is
```
https://cloud.YOURDOMAIN.com/remote.php/dav/files/USERNAME/
```
WebDAV connection should work without any limitations.

### Actual behaviour
A 404 not found error is occuring

### FIX

use the correct URL (which at least worked for us):
```
https://cloud.YOURDOMAIN.com/remote.php/webdav/
```

### Server configuration
**Operating system**: Ubuntu Linux 16.04
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 7.0
**Nextcloud version:** 15.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated
**Where did you install Nextcloud from:** manual

**Comment by gary-kim** [comment]
I just tried both links you provided against Nextcloud 16.0.4 and they both seem to work? Could there something specific with your setup that could be making the first link not work?

**Comment by flyinghuman** [comment]
maybe. just noticed it and would let you know if other people have the same problems. We have a Standard manual installation, maybe we forgot something at apache configuration.

**Comment by flyinghuman** [comment]
okay so we transfered this from ownsky to nextcloud. where to look to get it right? apache config?
