### ISSUE TITLE
OCS page index is broken

### ISSUE THREAD

**Issue by laurent22** [nextcloud/documentation#1613]
I don't know enough about rst to fix it, but the index page is broken:

https://github.com/nextcloud/documentation/blob/master/developer_manual/client_apis/OCS/index.rst

It also means that on the official website there's no longer a documentation for OCS.

**Comment by Siopyy** [comment]
+1 ! The developer documentation is broken.

**Comment by skjnldsv** [comment]
@juliushaertl @julius

**Comment by skjnldsv** [comment]
Fixed
