### ISSUE TITLE
Nextcloud 15/16 Developer Manual - File not found Error

### ISSUE THREAD

**Issue by TimoKramer** [nextcloud/documentation#1622]
There is no Developer Manual available on your Documentation Website. It returns a File not found error.

**Comment by skjnldsv** [comment]
@rullzer :)

**Comment by kesselb** [comment]
Would you mind to share the direct url to the page with the broken links? It's easier to fix it then. The links at https://docs.nextcloud.com and https://nextcloud.com/developer/ are working fine over here.

**Comment by korelstar** [comment]
I can confirm that on the day this issue was created, the developer manual was not accessible due to 404 error. However, this seems to be fixed now.

**Comment by skjnldsv** [comment]
Yes, we fixed it the day of this message, sorry for not updating, :)
