### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by schiessle** [nextcloud/documentation#1642]
We have here quite some API documentation but it seems like some important parts like activities or comments are missing: https://docs.nextcloud.com/server/17/developer_manual/client_apis/index.html

**Comment by schiessle** [comment]
cc @tobiasKaminsky as discussed

**Comment by tobiasKaminsky** [comment]
Comments: https://github.com/nextcloud/server/issues/7315#issuecomment-347468998
Activity: https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md

This should be both in docs.nc.c

**Comment by jospoortvliet** [comment]
> Comments: [nextcloud/server#7315 (comment)](https://github.com/nextcloud/server/issues/7315#issuecomment-347468998)
> Activity: https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md
> 
> This should be both in docs.nc.c

Indeed, it should. Here's a simple PR:
https://github.com/nextcloud/documentation/pull/1968

Taking the comments comment into the docs and linking to the activities. pls check if I put things in the right place...

**Comment by MorrisJobke** [comment]
Fixed in #1968
