### ISSUE TITLE
WebDAV link deprecated

### ISSUE THREAD

**Issue by derschiw** [nextcloud/documentation#1647]
The current documentation under https://docs.nextcloud.com/server/17/user_manual/files/access_webdav.html lists `example.com/nextcloud/remote.php/dav/files/USERNAME/` as URL to connect to devices for WebDAV. I tried this and it didnt work.
However nextcloud itself suggests to use `https://example.com/remote.php/webdav/` as login link on the front page (which actually works, I was using Cyerduck to test). 

I'm not 100% sure, but i think this should be editet. Thanks a lot 😊

**Comment by skjnldsv** [comment]
> https://example.com/remote.php/webdav/

is for old versions, the current one is example.com/remote.php/dav/files/USERNAME
