### ISSUE TITLE
docs.nextcloud.com is painfully slow

### ISSUE THREAD

**Issue by muhlemmer** [nextcloud/documentation#1654]
I don't now if this is the place to raise this issue, but at the moment docs.nextcloud.com loads painfully slow and even times out from time to time. Yesterday and the whole last week it worked fine from the same laptop and internet connection. Other pages on the web are working fine too.

I tried the following to check if it is not me:

1. The issue remains when I disable IPv6, in order to force the browser direct to IPv4.
2. The site responds the same from both Firefox and Konqueror
3. The site responds the same from my mobile phone, using 4G (so different network as the laptop)
4. I'm in Romania, so I've enabled a VPN to Germany. VPN throuput seems OK, global internet works. docs.nextcloud.com still giving issues.

**Edit:** nexcloud.com main site works fine too.

**Comment by skjnldsv** [comment]
It's back
