### ISSUE TITLE
docs.nextcloud.com is again painfully slow 

### ISSUE THREAD

**Issue by JSoko** [nextcloud/documentation#1658]
Somtimes load very slow, sometimes doesn't load with "ERR_CONNECTION_TIMED_OUT", giving a very bad userexpirience...

![grafik](https://user-images.githubusercontent.com/5583290/66456462-01434a00-ea6e-11e9-9e9d-c3431d3aad89.png)
![grafik](https://user-images.githubusercontent.com/5583290/66456541-3780c980-ea6e-11e9-975e-6fde8501a4f7.png)

**Comment by skjnldsv** [comment]
cc @rullzer @blizzz

**Comment by tflidd** [comment]
for me it's nearly 30s, it seems some resources can't be loaded via https and the browser uses a non-encrypted fall-back:
![grafik](https://user-images.githubusercontent.com/8111200/66492348-8d786000-eab4-11e9-8ded-40dc98a2bdb9.png)

**Comment by coliff** [comment]
I'm in Japan and getting slow access and occasional time-outs to this site too.

**Comment by tflidd** [comment]
This is an old topic. Current loading times for the main page are below 1s. Closing this, please open a new topic when problem comes back.
