### ISSUE TITLE
Update RHEL 8 Install Documentation

### ISSUE THREAD

**Issue by E-Fail** [nextcloud/documentation#1660]
Now RHEL 8 is Nextcloud recomended (https://docs.nextcloud.com/server/17/admin_manual/installation/system_requirements.html) but the docs only show an example for Centos 7 (https://docs.nextcloud.com/server/17/admin_manual/installation/source_installation.html). 

The Package names have changed, imagick is not in the RHEL Repos etc. An Update would be nice

**Comment by juliushaertl** [comment]
@wiswedel Maybe you know ... is there a recommended way to get imagick and redis on CentOS8/RHEL8?

We could just recommend https://rpms.remirepo.net/enterprise/8/ but it is of course no official package.

**Comment by wiswedel** [comment]
> We could just recommend https://rpms.remirepo.net/enterprise/8/ but it is of course no official package.

I'd say remirepo is a broadly respected (even if non-official) repo which is safe to use.

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/documentation/pull/1757
