### ISSUE TITLE
Oauth2 missing permission/security warning

### ISSUE THREAD

**Issue by Rotzbua** [nextcloud/documentation#1683]
## Problem

The oauth2 documentation does not state which permissions are granted to an external service.
It just mention "connecting" and do not warn about possible security and data leaks.

> Nextcloud allows connecting external services (for example Moodle) to your Nextcloud.

## Solution

* Add a list of permissions.
* Add a security warning.

## Current documentation

https://docs.nextcloud.com/server/17/admin_manual/configuration_server/oauth2.html

**Comment by skjnldsv** [comment]
cc @rullzer @ChristophWurst
