### ISSUE TITLE
release schedule

### ISSUE THREAD

**Issue by TP75** [nextcloud/documentation#1684]
Please update your schedules and dates ...

[NC 16 Docs » Maintenance and release schedule](https://docs.nextcloud.com/server/16/admin_manual/release_schedule.html#maintenance-and-release-schedule)

Change from:

  | release date | end of life | latest version | next version
-- | -- | -- | -- | --
16 | 2019-04-25 | 2020-04 | 16.0.3 (2019-07-09) | 16.0.4 (2019-08-15)
15 | 2018-12-10 | 2019-12 | 15.0.10 (2019-07-09) | 15.0.11 (2019-08-15)
14 | 2018-09-10 | 2019-09 | 14.0.13 (2019-07-04) | 14.0.14 (2019-08-15)

to the more current:

  | release date | end of life | latest version | next version
-- | -- | -- | -- | --
16 | 2019-04-25 | 2020-04 |  **16.0.5 (2019-09-27)**  |  16.0.**??**
15 | 2018-12-10 | 2019-12 |  **15.0.12 (2019-09-27)**  |  15.0.**??**
14 | 2018-09-10 | 2019-09 |  **14.0.14 (2019-08-16)**  |  **(unsupported)**

- - -  

Yes, one could think of contributing directly into the code of the pages. 😉 

@jospoortvliet  However, schedules should be the main interest of somebody with dev plan responsibilities or even better with marketing P&R interests.

Maybe, maybe, maybe another page next time.

**Comment by TP75** [comment]
release of 16.0.6 an no docs update?

QM ?

**Comment by kesselb** [comment]
I think we should remove the information from the docs and link to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule. Less duplicate content and only one place to update.
