### ISSUE TITLE
Remove SAMEORIGIN header from nginx config

### ISSUE THREAD

**Issue by ogasser** [nextcloud/documentation#1701]
As the SAMEORIGIN header is [handled directly by PHP](../blob/331d8ca7a6c5f37951f37e50c8264fc005ffd7d5/admin_manual/release_notes.rst#updates-to-nginx-configuration) and not the webserver anymore, the following two references to the SAMEORIGIN header in the nginx documentation should be removed:

1. remove [first SAMEORIGIN line](../blob/83022d836c4ddec7ef4e34c0ba69b318bfd03836/admin_manual/installation/nginx.rst#L72)
2. remove [second SAMEORIGIN line](../blob/83022d836c4ddec7ef4e34c0ba69b318bfd03836/admin_manual/installation/nginx.rst#L173)

**Comment by skjnldsv** [comment]
Hey :)
Thanks for the report! Can you open a pull request with those changes please? :)
