### ISSUE TITLE
Increase memory_limit in PHP FPM config to upload big files

### ISSUE THREAD

**Issue by ogasser** [nextcloud/documentation#1702]
In order to get rid of the warning in "Security & setup warnings" in addition to increasing the values for `post_max_size` and `upload_max_filesize` you also need to also increase the `memory_limit` in your php.ini config. E.g.:

```
 upload_max_filesize = 16G
 post_max_size = 16G
 memory_limit = 16G
```

This should be reflected in the [PHP documentation for uploading big files](../blob/master/admin_manual/configuration_files/big_file_upload_configuration.rst#L101).

**Comment by tflidd** [comment]
Is it required to have a `memory_limit` of the same size?

**Comment by juliushaertl** [comment]
It should be enough to specify a memory_limit of 512MB as it is recommended in the setup warning: The PHP memory limit is below the recommended value of 512MB.
