### ISSUE TITLE
Nginx + Fastcgi_cache deprecated?

### ISSUE THREAD

**Issue by nariox** [nextcloud/documentation#1706]
I was looking into implementing fastcgi_cache in my server. I've tried to find documentation on the official docs, but the last mention of it is in Nextcloud 11 docs.

Is it not mentioned because it doesn't bring enough improvement? Or is it a security risk? In any case, is it still supported or at least known to work well or should I stay away from it?

**Comment by skjnldsv** [comment]
If it's been removed, I guess we recommend not using it.
You can follow the proper nginx settings in the stable docs branch: https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html
