### ISSUE TITLE
Nextcloud 17 Web hosting issue - File not found

### ISSUE THREAD

**Issue by rudytch** [nextcloud/documentation#1745]
Hello,

i want to host my Nextcloud platform on a web hosting platform but i get the following error :

> Fatal error: require_once(): Failed opening required 'support/appinfo/app.php' (include_path='.:/home/homnet882') in /home/homnet882/ownc/lib/private/legacy/app.php on line 260

I have made some research and i think i have to modify the include_path variable but i don't know where.

thanks for your support

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
