### ISSUE TITLE
Missing PHP API documentation

### ISSUE THREAD

**Issue by p-bo** [nextcloud/documentation#1782]
Hello,

When trying to read developer documentation, URLs:
https://docs.nextcloud.com/server/15/developer_manual
https://docs.nextcloud.com/server/16/developer_manual
https://docs.nextcloud.com/server/stable/developer_manual
https://docs.nextcloud.com/server/latest/developer_manual

are returning only:
File not found.

Last working is for version 14.

Not exactly encouraging to developers…

**Comment by J0WI** [comment]
@nextcloud/infrastructure do you have any kind of monitoring for this?

**Comment by rullzer** [comment]
> @nextcloud/infrastructure do you have any kind of monitoring for this?

Yeah we do. But weekend etc. 
Is backup now.

**Comment by WarfoX72** [comment]
API Documentations is totally missing yet.

**Comment by rullzer** [comment]
@juliushaertl ^^

**Comment by juliushaertl** [comment]
Yes, they were removed from the main documentation an we planned to host them in a dedicated location, since they were actually were messing up the developer docs sphinx build to much, e.g. when searching for something. https://github.com/nextcloud/documentation/pull/1777 

I'll see if I can come up with a proper separate build for those.

**Comment by juliushaertl** [comment]
I’ve published a quick build of the API doc from 18 with phpDocumentor here https://bitgrid.net/~jus/nextcloud-phpdoc/namespaces/OCP.html 2 as a temporary solution and I’ll look into how we can bring back the proper documentation pages again.

**Comment by korelstar** [comment]
When there will be a final solution for this? The official developer manual still has no link or information for the PHP API: https://docs.nextcloud.com/server/latest/developer_manual/api.html

**Comment by juliushaertl** [comment]
I wanted to have this directly running with phpDocumentor 3 but encountered https://github.com/phpDocumentor/phpDocumentor/issues/2294 when running it against the server code. The issue is fixed and the build works fine now with the nightly build, but I'd say we wait for another RC then. I assume we can set this up somehow automated to publish to docs.nextcloud.com then. cc @rullzer

**Comment by skjnldsv** [comment]
> The issue is fixed and the build works fine now with the nightly build, but I'd say we wait for another RC then

I'm up for rc while we wait for final.
No documentation is not ideal :)

You have a working pr somewhere?


> I assume we can set this up somehow automated to publish to docs.nextcloud.com then. cc @rullzer

We can also publish on docs-nextcloud.github.io ? With github actions.
And then link docs.nc.com to here?

**Comment by juliushaertl** [comment]
> You have a working pr somewhere?

No, i was just testing it locally by running phpDocumentor against lib/public/ in the server repo.

> We can also publish on docs-nextcloud.github.io ? With github actions.
> And then link docs.nc.com to here?

Probably good to have that on the server repo then.

**Comment by qdii** [comment]
I'm a new developer, trying to develop a simple app for NextCloud for the first time. I was very confused by the documentation missing, and wondering if I had to regenerate myself it somehow, until I found this post.

So if I understand correctly, the documentation has been missing for more than 3 months now, and it looks like the fix would just be to push the files on a server, but nobody has done it. Is that correct?

**Comment by skjnldsv** [comment]
> it looks like the fix would just be to push the files on a server, but nobody has done it. Is that correct?

not really, we need a proper new way of building them, there is a bug on the library used to generate them as far as I understood

**Comment by qdii** [comment]
> not really, we need a proper new way of building them, there is a bug on the library used to generate them as far as I understood

Why not publish a prior revision, built before the bug was introduced, so that users have access to some documentation? Parts would be outdated, but it's arguably better than having no documentation at all.

**Comment by marcelklehr** [comment]
:crying_cat_face:

**Comment by dartcafe** [comment]
Any news on this? We have a lot of deprications and a current doc would help a lot.

**Comment by juliushaertl** [comment]
The nightly build from phpDocumentor seems to work again, I've updated http://bitgrid.net/~jus/nextcloud-phpdoc/ to represent the current server master now for preview. I'll try to come up with a script to build the api docs so we can probably hook that up to docs.nextcloud.com as well. 

However ideally this should of course be based on a stable release of phpDocumentor which there is no estimation on when this will happen unfortunately.

**Comment by skjnldsv** [comment]
Maybe we can use the github actions to push a githb.io static website?

**Comment by juliushaertl** [comment]
I'm not a big fan of github pages for this since this would mean that we need to commit the built HTML pages to the repo every time it gets updated. We could probably use netlify but I think docs.nextcloud.com would be the best place actually.

**Comment by juliushaertl** [comment]
Let's actually give that a try https://app.netlify.com/sites/elated-chandrasekhar-db34f5/deploys/5f45fc1073360c84e9f7f85b

**Comment by juliushaertl** [comment]
Worked like a charm https://elated-chandrasekhar-db34f5.netlify.app/

@rullzer Could you check the github admin settings? I requested access for netlify to the server repo so we can basically build the api docs on master and the stable branches from there.

**Comment by skjnldsv** [comment]
> @rullzer Could you check the github admin settings? I requested access for netlify to the server repo so we can basically build the api docs on master and the stable branches from there.

approved!

**Comment by skjnldsv** [comment]
> I'm not a big fan of github pages for this since this would mean that we need to commit the built HTML pages to the repo every time it gets updated. We could probably use netlify but I think docs.nextcloud.com would be the best place actually.

Can probably be automated with Github Actions, no?

**Comment by juliushaertl** [comment]
Could be done, sure. I still like to keep git tree clean from the actual build assets that is why I'd prefer something like netlify.

**Comment by skjnldsv** [comment]
Sure thing :)
Can we have a proper netlify name though? :p

**Comment by juliushaertl** [comment]
See the server PR https://github.com/nextcloud/server/pull/22432 :wink:

**Comment by marcelklehr** [comment]
:heart: :tada:
