### ISSUE TITLE
Shorten and SEO improve doc URLs

### ISSUE THREAD

**Issue by eppfel** [nextcloud/documentation#179]
This `https://docs.nextcloud.com/server/10/developer_manual/app/css.html` could be improved to something like this `https://docs.nextcloud.com/developer/app/css.html`
For one thing the levels should be less and the readability improved, so people see, where they are or which link they click or even what to type when they directly want to access the docs).

Secondly, after each release the documentation you get in search engines is outdated, because of the version number. There should be a default without version number, which gives you the current version automatically.

For example: https://www.google.de/search?q=nextcloud+documentation+css 😐

**Comment by juliushaertl** [comment]
Let's use #517 since the discussion happened over there.
