### ISSUE TITLE
Section on Thunderbird should mention TBsync, which brings autodiscovery for caldav/carddav resources

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/documentation#1793]
So far the [section on Thunderbird](https://docs.nextcloud.com/server/18/user_manual/pim/sync_thunderbird.html) doesn't mention TBsync, instead it is explained how to subscribe to calendars individually which is a tedious process. 
The [TBsync extension](https://addons.thunderbird.net/de/thunderbird/addon/tbsync/) is a way to make nextcloud calendar integration into Thunderbird easy. Like all modern caldav/carddav clients, it has autodiscovery, so all you have to give it is the URL of your nextcloud server and through the autodiscovery mechanism, it will find all the available calendars and addressbooks for you. You don't have to subscribe to each calendar individually anymore. I recommend this to all of my users. If you have TBsync, it is still nice to have Cardbook, because it is much better than the built-in address book, but you don't have to have it for the sync functionality, because TBsync can sync your address books as well.

**Comment by skjnldsv** [comment]
Hey :)
Could you maybe help here? You can edit the pages directly and suggest a change :rocket: 
That would be supper great :hugs:

**Comment by vasyugan** [comment]
> Hey :)
> Could you maybe help here? You can edit the pages directly and suggest a change rocket
> That would be supper great hugs

Oh, I didn't notice that I can. 
Seems I have no excuse then... I'll write something up...

**Comment by vasyugan** [comment]
> Hey :)
> Could you maybe help here? You can edit the pages directly and suggest a change rocket
> That would be supper great hugs

I have added a pull request https://github.com/nextcloud/documentation/pull/1794

However, I have no idea how I can add my own screenshots. It seems I can only add plain text.

**Comment by vasyugan** [comment]
> Hey :)
> Could you maybe help here? You can edit the pages directly and suggest a change rocket
> That would be supper great hugs

Could you please review this error message:

![grafik](https://user-images.githubusercontent.com/3313208/72925837-a64f0d80-3d53-11ea-9974-a7347a7926b4.png)

**Comment by skjnldsv** [comment]
You're awesome!!
I restarted the tests, because I couldn't figure the issue :)

**Comment by vasyugan** [comment]
> You're awesome!!
> I restarted the tests, because I couldn't figure the issue :)

I got the same error again. Something seems broken.
BTW, I guess one should clean up the section, making TBSync the canonical method and mentioning CardBook for those who need a more advanced address book (I do!), but drop the original description, which describes manually subscribing to individual calendars, because we clearly don't want that in the 21rst century, and this may confuse users.

**Comment by vasyugan** [comment]
> You're awesome!!
> I restarted the tests, because I couldn't figure the issue :)

When I look at the failed checks at https://github.com/nextcloud/documentation/pull/1794/checks?check_run_id=404608506 each one ends with a URL that isn't accessible:

![grafik](https://user-images.githubusercontent.com/3313208/72981255-a7784d00-3ddc-11ea-87ba-49c4208b705e.png)

And this is what I see when I manually visit the URL in the browser:
![grafik](https://user-images.githubusercontent.com/3313208/72981303-c5de4880-3ddc-11ea-9e5e-04a2170ba7f9.png)

**Comment by skjnldsv** [comment]
Yes, this is because we cannot lint on forks apparently :/
Opened issue #1795

**Comment by vasyugan** [comment]
> Yes, this is because we cannot lint on forks apparently :/
> Opened issue #1795

So is there something I am supposed to do now or just wait?
