### ISSUE TITLE
Apache2 HOME and HTTP_HOME env vars

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/documentation#1798]
Code reference: https://github.com/nextcloud/documentation/commit/f9a3f4ebcff672049c9c0585644de23e1321e34e#r36865865
Forum reference: https://help.nextcloud.com/t/apache2-home-and-http-home-env-vars/68557

What are these two variables for?

**Comment by skjnldsv** [comment]
No idea :/

@blizz @rullzer @juliushaertl @ChristophWurst ?

**Comment by juliushaertl** [comment]
I also cannot see any reason for keeping them.

**Comment by ChristophWurst** [comment]
No idea.

:fire: it :)

**Comment by MichaIng** [comment]
PR up: #1800
