### ISSUE TITLE
Public Page example isn't working

### ISSUE THREAD

**Issue by Tim-Obert** [nextcloud/documentation#1812]
I've tried to implement an AuthPublicShareController with the [Public Page documentation](https://docs.nextcloud.com/server/latest/developer_manual/app/publicpage.html). 
But if the share is password protected this error shows up in the log:

**Symfony\Component\Routing\Exception\RouteNotFoundException**: Unable to generate a URL for the named route "wcoonetimesecret.authsecretsharecontroller.showAuthenticate" as such route does not exist.

So the route is generated wrong, it should be wcoonetimesecret.authsecretshare.showAuthenticate.

**Comment by skjnldsv** [comment]
Hey!
Where did you find the `wcoonetimesecret.authsecretsharecontroller.showAuthenticate` part on the docs?

**Comment by Tim-Obert** [comment]
This is my implemented controller. 'wcoonetimesecret' is my namespace and 'AuthSecretShareController' is the controller which extends the AuthPublicShareController.

**Comment by skjnldsv** [comment]
Yes, but you claim that the doc is wrong, where did you see the part with the extra "controller" ?

**Comment by Tim-Obert** [comment]
The example of the docs is with the PublicShareController and underneeth there is written:
"On some pages password authentication might be required (just like the when you share a file via public link with a password). In this case you need to extend a different provider.

The AuthPublicShareController requiers in addition to the PublicShareController that you also implement the verifyPassword and showShare functions."
I've added these methods, but it won't work unless the routes are in the core/routes.php.

**Comment by skjnldsv** [comment]
@Tim-Obert can you share some code?

**Comment by Tim-Obert** [comment]
```php
class AuthSecretShareController extends AuthPublicShareController{
    /** @var Defaults */
    protected $defaults;
    /** @var Secret */
    protected $secret;

    /** @var SecretMapper */
    protected $mapper;
    public function __construct(string $appName, IRequest $request, ISession $session, IURLGenerator $urlGenerator, Defaults $defaults, SecretMapper $mapper)
    {
        parent::__construct($appName, $request, $session, $urlGenerator);
        $this->urlGenerator = $urlGenerator;
        $this->defaults = $defaults;
        $this->secret = new Secret();
        $this->mapper = $mapper;
    }

    /**
     * @inheritDoc
     */
    protected function verifyPassword(string $password): bool
    {
        return $password == '123';// TODO: Implement verifyPassword() method.
    }
    /**
     * @inheritDoc
     * @NoCSRFRequired
     * @PublicPage
     */
    public function get()
    {
        return 1;
    }
    /**
     * @PublicPage
     * @NoCSRFRequired
     *
     * Show the authentication page
     * The form has to submit to the authenticate method route
     */
    public function showAuthenticate(): TemplateResponse {
        parent::showAuthenticate();
    }

    /**
     * @inheritDoc
     * @NoCSRFRequired
     * @PublicPage
     */
    public function showShare(): \OCP\AppFramework\Http\TemplateResponse
    {
        // TODO: Implement showShare() method.
        return new \OCP\AppFramework\Http\TemplateResponse('wcoOneTimeSecret', 'secret/show', ['share' => $this->secret], 'guest');
    }
    /**
     * @inheritDoc
     */
    protected function getPasswordHash(): string
    {
        return md5(123);
        // TODO: Implement getPasswordHash() method.
    }
    
    /**
     * @inheritDoc
     */
    public function isValidToken(): bool
    {
       return true;
        // TODO: Implement isValidToken() method.
    }
    
    /**
     * @inheritDoc
     * @NoCSRFRequired
     */
    protected function isPasswordProtected(): bool
    {
        return true;
        // TODO: Implement isPasswordProtected() method.
    }

}```


And in the core/routes.php I've added:
```
        [ 'name' => 'authsecretsharecontroller#get', 'url' => '/secret/{token}', 'verb' => 'GET' , 'app' => 'wcoonetimesecret'],
        ['name' => 'authsecretsharecontroller#showShare', 'url' => '/display/{token}', 'verb' => 'GET', 'app' => 'wcoonetimesecret'],
        ['name' => 'authsecretsharecontroller#showAuthenticate', 'url' => '/secret/{token}/authenticate/{redirect}', 'verb' => 'GET', 'app' => 'wcoonetimesecret'],
        ['name' => 'authsecretsharecontroller#authenticate', 'url' => '/secret/{token}/authenticate/{redirect}', 'verb' => 'POST', 'app' => 'wcoonetimesecret'],
```

**Comment by Tim-Obert** [comment]
It will give the error I mentioned in my first comment, if you don't extend the core/routes.php. Because the Route which is build in AuthPublicShareController with the class name ('controller' at the end). If there is a soulution to define the route in the app and not in the core, it would be helpful if it's documented.

**Comment by skjnldsv** [comment]
> And in the core/routes.php I've added:

should indeed be directly into your appinfo folder.
Have you checked the full app tutorial app?  :)
https://github.com/nextcloud/app-tutorial

**Comment by Tim-Obert** [comment]
I've tried already but the route which is tried to be accessed by the AuthPublicShareController is in my example:
wcoonetimesecret.authsecretshare***controller***.showAuthenticate
The right route would be:
wcoonetimesecret.authsecretshare.showAuthenticate

with the "controller" at the end i didn't get it working in the appinfo folder.

**Comment by skjnldsv** [comment]
Make sure your namespace is correct and all your declarations are ok.
This is working in all apps, so there is most likely an issue with your files :)

Again, giving access to your full repository and code might help us to find your issue.

Unfortunately, as this is a development issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
You might get better feedback there
