### ISSUE TITLE
replace Windows 7 screenshots with Windows 10 screenshots

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/documentation#1815]
not sure if there are more, but I stumbled over this one https://github.com/nextcloud/documentation/blob/master/user_manual/files/access_webdav.rst#mapping-drives-with-windows-explorer

Win7 is End of Life. To build trust, we should update all win7 screenshots to win10.

**Comment by skjnldsv** [comment]
Hey :)
Could you provide those changes? That would really help :hugs:

**Comment by alexanderdd** [comment]
Sorry, this does not have a high enough priority for me atm. If nobody did it within ~ two months, feel free to ask me again here.

**Comment by cmasterdelphi** [comment]
![image](https://user-images.githubusercontent.com/56067322/74720501-36d71b80-5236-11ea-8f03-0567cc3db309.png)

**Comment by cmasterdelphi** [comment]
![image](https://user-images.githubusercontent.com/56067322/74720576-4ce4dc00-5236-11ea-9742-4ee0b54b997b.png)

**Comment by cmasterdelphi** [comment]
here you go.
![image](https://user-images.githubusercontent.com/56067322/74720844-b1a03680-5236-11ea-9bb4-1e6905cd4f82.png)

**Comment by tflidd** [comment]
a pull request would be nice. This is the corresponding file: https://github.com/nextcloud/documentation/blob/master/user_manual/images/explorer_webdav.png
