### ISSUE TITLE
Location block logic in the nginx samples

### ISSUE THREAD

**Issue by artemkonev** [nextcloud/documentation#1831]
Hi everyone,

I'm working on a basic howto about NextCloud configuration for NGINX's new app server, NGINX Unit: http://unit.nginx.org/howto/nextcloud/. As you can see, it is loosely based on the respective NextCloud docs article (by the way, it is really helpful): https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

I'm trying to simplify the config, avoiding the need to set up nginx in front of Unit; I can see what the nginx config samples do, but I don't really understand the logic behind that, as it mostly pertains to NextCloud.

Can someone please elaborate on these samples from NextCloud's perspective, especially the location blocks?

**Comment by skjnldsv** [comment]
> Can someone please elaborate on these samples from NextCloud's perspective, especially the location blocks?

Hey, they're matching different services.
Sometimes it's because we're serving some files over php, sometimes it's a direct serv of static files, sometimes it's redirect needed by other protocoles (dav, well-known...)

**Comment by artemkonev** [comment]
Thank you!
