### ISSUE TITLE
app_install_overwrite is not documented

### ISSUE THREAD

**Issue by GAS85** [nextcloud/documentation#1865]
As written above `app_install_overwrite` is nowhere documented. Here is also asked about: https://help.nextcloud.com/t/ncp-what-is-app-install-overwrite-for/71523

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/4e36157f3dc4fe085e629f07d0cae8c24879b5df/apps/settings/lib/Controller/AppSettingsController.php#L273

It is apps whom max supported version gets ignored :)
When you force install apps in the app store

**Comment by GAS85** [comment]
Thanks! Still could not find where it is documented.

**Comment by skjnldsv** [comment]
It is not, this is a gui function and can be set with occ app:enable --force
