### ISSUE TITLE
Protokoll Error

### ISSUE THREAD

**Issue by Posi81** [nextcloud/documentation#1869]
What is this?

[no app in context] Error: UnexpectedValueException: The Nextcloud configuration (config/config.php) does not contain the key user_backend_sql_raw which should contain the configuration for the app user_backend_sql_raw. at <<closure>>

 0. <<closure>>
    OCA\UserBackendSqlRaw\Config->__construct(OC\AppFramework\Logger {}, OC\AllConfig {})
 1. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 83
    ReflectionClass->newInstanceArgs([OC\AppFramework ... }])
 2. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 100
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 3. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 115
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\UserBackendSqlRaw\\Config")
 4. /home/www/nextcloud_mdfashion/lib/private/AppFramework/DependencyInjection/DIContainer.php line 415
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\UserBackendSqlRaw\\Config")
 5. /home/www/nextcloud_mdfashion/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\UserBackendSqlRaw\\Config")
 6. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 70
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\UserBackendSqlRaw\\Config", true)
 7. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 100
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 8. /home/www/nextcloud_mdfashion/lib/private/AppFramework/Utility/SimpleContainer.php line 115
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\UserBackendSqlRaw\\UserBackend")
 9. /home/www/nextcloud_mdfashion/lib/private/AppFramework/DependencyInjection/DIContainer.php line 415
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\UserBackendSqlRaw\\UserBackend")
10. /home/www/nextcloud_mdfashion/lib/private/ServerContainer.php line 134
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\UserBackendSqlRaw\\UserBackend")
11. /home/www/nextcloud_mdfashion/apps/user_backend_sql_raw/lib/AppInfo/Application.php line 56
    OC\ServerContainer->query("OCA\\UserBackendSqlRaw\\UserBackend")
12. /home/www/nextcloud_mdfashion/apps/user_backend_sql_raw/appinfo/app.php line 21
    OCA\UserBackendSqlRaw\AppInfo\Application->__construct()
13. /home/www/nextcloud_mdfashion/lib/private/legacy/app.php line 266
    require_once("/home/www/nextc ... p")
14. /home/www/nextcloud_mdfashion/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("user_backend_sql_raw")
15. /home/www/nextcloud_mdfashion/lib/private/legacy/app.php line 128
    OC_App::loadApp("user_backend_sql_raw")
16. /home/www/nextcloud_mdfashion/lib/private/legacy/user.php line 125
    OC_App::loadApps(["prelogin"])
17. /home/www/nextcloud_mdfashion/lib/base.php line 717
    OC_User::setupBackends()
18. /home/www/nextcloud_mdfashion/lib/base.php line 1089
    OC::init()
19. /home/www/nextcloud_mdfashion/index.php line 36
    require_once("/home/www/nextc ... p")

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
