### ISSUE TITLE
add full php path  for cron job 

### ISSUE THREAD

**Issue by dassio** [nextcloud/documentation#1887]
I am using NC18, when configuring the crontab as in here, [setup cron](https://docs.nextcloud.com/server/18/admin_manual/configuration_server/background_jobs_configuration.html).

you need to use `/usr/local/bin/php  -f /var/www/html/cron.php` instead of ` php  -f /var/www/html/cron.php` , not sure why, but otherwise, job showed executed on syslog, but no effect

**Comment by skjnldsv** [comment]
It completely depends on your user PATH variable :)
If it's properly set, you don't need it.

I'd say it's fine like this, php can be installed in /usr/bin as well.
If you're doing sysadmin stuff, you should be aware enough to know how to handle your PATH I'd say :)

**Comment by dassio** [comment]
" If it's properly set, you don't need it." ----  the problem is in the standard docker image, it is not configured properly.
"If you're doing sysadmin stuff, you should be aware enough to know how to handle your PATH I'd say :)"   --- we should not assume that people will know everything

"I'd say it's fine like this, php can be installed in /usr/bin as well."  ---  you can  tell that the risk, let  user find the path like what you did with "/var/www/nextcloud" 

software should be easy to use, you can not assume too much of the user , i think this is the biggest problem  of open source software.  to reach  as many people as  possible, we should make everything as smooth as possible

**Comment by dassio** [comment]
www-data is nologin, the `php -f /var/www/html/cron.php` will not work for sure. this is an error, please  reopen it
