### ISSUE TITLE
[User docs] update What's new page

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/documentation#1890]
The page [What’s new for users in Nextcloud latest](https://docs.nextcloud.com/server/18/user_manual/whats_new.html) is pretty outdated and needs to be adjusted.

**Comment by wiswedel** [comment]
@jospoortvliet The 19 what's new page is still showing the content from 12. Do you have some updates?

**Comment by joshtrichards** [comment]
Closing in favor of tracking in #8309
