### ISSUE TITLE
Theming documentation missing in NC18 doc (and since NC16)

### ISSUE THREAD

**Issue by cercec** [nextcloud/documentation#1900]
Hello, 
I am new to NC and I am not sure this is an issue. I wanted to customise the footer of the login page (the theming app is not enough for me). Unfortunately, I can't find any documentation on theming NC18, nor on any version next the 15th. Is it still possible ?

**Comment by skjnldsv** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
It was removed in favor of the Theming app with https://github.com/nextcloud/documentation/pull/946 see https://github.com/nextcloud/documentation/pull/946#issuecomment-441999185 for details.
