### ISSUE TITLE
Show free space in Web UI

### ISSUE THREAD

**Issue by Staubgeborener** [nextcloud/documentation#1914]
Well, i read and searched a lot for this issue, but couldn't found a solution. Is there a way to show the free space in the bottom left corner of the UI? Now it only shows the used space, but not the free space (like "1.2 GB / 10 GB used").

**Comment by skjnldsv** [comment]
Hey, no there is no option for this.
Cheers

**Comment by Staubgeborener** [comment]
Thats disappointing and i don't get why. But nevermind.

**Comment by skjnldsv** [comment]
You can see the reasons why here: https://github.com/nextcloud/server/pull/16049
Basically doesn't make sense to show unlimited. So the total is only shown when your account is set to a specific quota
