### ISSUE TITLE
https://docs.nextcloud.com/server/18/go.php?to=admin-dir_permissions

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/documentation#1915]
i encountered an error:

Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory
See https://docs.nextcloud.com/server/18/go.php?to=admin-dir_permissions

but the link does not seem to be available in the documentation which is really frustrating

**Comment by skjnldsv** [comment]
Right, thanks, I opened a pr to remove this outdated link https://github.com/nextcloud/server/pull/20210

**Comment by gary-kim** [comment]
Closed by nextcloud/server#20210
