### ISSUE TITLE
Update external storage images 

### ISSUE THREAD

**Issue by joshmorel** [nextcloud/documentation#1925]
The unmaintained backends (Dropbox etc) were removed from text #1891 but the images still references them, which is confusing. I'm willing to take a stab.

https://docs.nextcloud.com/server/18/admin_manual/configuration_files/external_storage_configuration_gui.html

![image](https://user-images.githubusercontent.com/10546720/77934879-b1a44500-727e-11ea-8aca-0e97ef848ab0.png)

**Comment by skjnldsv** [comment]
> I'm willing to take a stab.

awesome :)
Could you open a pr and ping me in it ?
