### ISSUE TITLE
incomplete documentation?

### ISSUE THREAD

**Issue by fds2610** [nextcloud/documentation#1927]
Dear all,
where can I find actual documentation about how to setup email adresses correctly for using nextcloud/calendar/caldav for multiple users ?
my invitations are being sent with the following "from:":
[Full Username] via Nextcloud like
Max Mustermann über Nextcloud cloud@provider.net
and replys automatically go back to the server-email which usualls shall process communication with internal users.
This leads to all replies to calendar-invitations are being sent to the admins...
Is this intended ?

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
