### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [nextcloud/documentation#1940]
documentation/user_manual/pim/sync_kde.rst 

You can set a manual refresh rate **four** your calendar and contacts resources.

for

**Comment by skjnldsv** [comment]
You're missing your end of sentence?

**Comment by AlexandrParkhomenko** [comment]
"four" means "for"
Four calendars are absent.

**Comment by skjnldsv** [comment]
Can you edit it and provide a pull request? 
That would be awesome :)

**Comment by AlexandrParkhomenko** [comment]
Und noch einmal. (And one more time.)
user_manual/files/access_webdav.rst
window opens, enter your **Nexcloud** server’s WebDAV
