### ISSUE TITLE
Missing download link of l10n.pl script to translate apps.

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/documentation#199]
Hi,
In the developer manual you refers to a perl script that is not distributed in the nextcloud/owncloud tarball..

> https://docs.nextcloud.com/server/10/developer_manual/app/l10n.html#creating-your-own-translatable-files

Well.. Where you can download this?

Finally I could translate my application using this script:

> https://github.com/nextcloud/apps/blob/master/l10n/l10n.pl

...but their use is differently than described. 😕

**Comment by MorrisJobke** [comment]
Currently I use the one from https://github.com/owncloud/administration/tree/master/jenkins/translation_sync

**Comment by MorrisJobke** [comment]
The plan is to move this also over - but this didn't happened yet.

**Comment by jowi24** [comment]
I also did a long research, before finding this issue. Isn't it possible to add a link to https://raw.githubusercontent.com/owncloud/administration/master/jenkins/translation_sync/l10n.pl in the meantime?

**Comment by joshtrichards** [comment]
This is handled a bit differently now (from the looks of it) and seems far better documented.

https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#translation

There is also now a link to the Nextcloud org managed tool for manual translations, which I believe is what this old issue was covering:

https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#manual-translation
