### ISSUE TITLE
CentOS Installation direction issues with optional Redis/Imagemagick

### ISSUE THREAD

**Issue by peterzieba** [nextcloud/documentation#2011]
Hi,

The following page:
https://docs.nextcloud.com/server/18/admin_manual/installation/example_centos.html

Has an issue in the section "Manually building redis/imagick (optional)"
```
# dnf install -y php-pear gcc curl-devel php-devel zlib-devel pcre-devel make pecl install redis
Last metadata expiration check: 0:24:38 ago on Tue 21 Apr 2020 01:48:44 PM CDT.
No match for argument: pecl
No match for argument: install
Error: Unable to find a match: pecl install

```

**Comment by skjnldsv** [comment]
pecl seems to be provided by `php-pear` ?
Can you try?

**Comment by skjnldsv** [comment]
Ah ok, no
you copied the second line
First command is `dnf install -y php-pear gcc curl-devel php-devel zlib-devel pcre-devel make` second command is `pecl install redis`

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/documentation/pull/2015 :)

Thanks for the find @peterzieba !!
