### ISSUE TITLE
Broken link to "development tool"

### ISSUE THREAD

**Issue by fancycode** [nextcloud/documentation#202]
The link to "development tool" in section "Check out the code" on https://docs.nextcloud.com/server/10/developer_manual/general/devenv.html points to https://github.com/nextcloud/ncdev which results in a 404 from GitHub.

**Comment by Henni** [comment]
I suggest linking to https://github.com/owncloud/ocdev for now, until this functionality is integrated into the app store (https://github.com/nextcloud/appstore/issues/316). cc @janibonnevier

**Comment by janibonnevier** [comment]
It already is :)
https://apps.nextcloud.com/developer/apps/generate

**Comment by tflidd** [comment]
The broken link isn't there any more. However, it says you should install the development tool and get it from https://github.com/nextcloud. Shouldn't this be a bit more specific?

**Comment by tflidd** [comment]
at some time there @BernhardPosselt linked something (which does not exist any more):
https://github.com/nextcloud/documentation/commit/bc5c1ba7e2797c321d7967c245d521029b99b2f7

**Comment by joshtrichards** [comment]
This has been replaced by:

https://apps.nextcloud.com/developer/apps/generate

And the docs now reference this:

https://docs.nextcloud.com/server/latest/developer_manual/app_development/intro.html#create-an-app

There is one stray reference to "development tool installation" here which I'll submit a PR for now to eliminate so we'll finally be able to close this Issue out:

https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html#check-out-the-code
