### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [nextcloud/documentation#2026]
--- a/developer_manual/app/npm.rst
+++ b/developer_manual/app/npm.rst
@@ -13,7 +13,7 @@ npm build
 
 Once ``npm install`` (``npm i`` for short) has been run to install all dependencies specified
 on ``package.json``, one typically has to build the project. Building can happen with tools like
-Webpack, Grunt or similar. To unify the build command across Nextcoud apps, just add the build
+Webpack, Grunt or similar. To unify the build command across **Nextcloud** apps, just add the build
 command(s) as ``build`` script to your.
 
 For apps that use webpack, this might look like this:

**Comment by skjnldsv** [comment]
Hi!
It seems your message is incomplete @AlexandrParkhomenko, can you check? :)

**Comment by tflidd** [comment]
I got it: https://github.com/nextcloud/documentation/pull/2112

On the documentation page, there is a link to edit the current document. That's quick and easy just in case someone else finds a typo.
