### ISSUE TITLE
Improve SSL hardening guide

### ISSUE THREAD

**Issue by fabian-hk** [nextcloud/documentation#2038]
I have seen that you have referenced the Mozilla TLS profiles in the [SSL hardening guideline](https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/harden_server.rst#proper-ssl-configuration). @danielfett and I developed a free web service called [Web TLS Profiler](https://tlsprofiler.danielfett.de/) that can compare the TLS settings of a server with a Mozilla TLS profile. The Web TLS Profiler gives detailed error messages if the TLS settings deviate from the Mozilla TLS profile. Since you referenced the Mozilla TLS profiles, I was wondering whether you are interested in linking the Web TLS Profiler in the SSL hardening guideline?

**Comment by MorrisJobke** [comment]
Sounds like a useful tool :) Do you mind to open a pull request against the documentation page to add a link to the web profiler?

**Comment by fabian-hk** [comment]
Yes, I will submit a PR as soon as possible ;)

**Comment by MorrisJobke** [comment]
Closed with #2060
