### ISSUE TITLE
Others with access needs documentation

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/documentation#2042]
Nextcloud 18 introduced the feature "others with access" in the sharing sidebar:

![image](https://user-images.githubusercontent.com/1804221/80952738-6ee40880-8dfa-11ea-8059-8c0d03fd3c0a.png)

It is not yet documented. Documentation should go into the User Manual under https://docs.nextcloud.com/server/latest/user_manual/files/access_webgui.html#file-controls.

**Comment by tflidd** [comment]
Question: These are subpoints for a shared link? So ein can send a link either for people who have internally access or externally or for a project?

**Comment by wiswedel** [comment]
> Question: These are subpoints for a shared link? So ein can send a link either for people who have internally access or externally or for a project?

No, this applies to internal shares and could also be described as "inherited shares". 
If you share a folder containing a bunch of sub- and sub-sub-folders, you so far wouldn't know for a specific file or sub-folder who else has access to this because a superior folder had been shared with someone.
This function now reveals that information and also where exactly the share is coming from.

**Comment by joshtrichards** [comment]
Fixed in #2116 and merged long ago. This Issue can be closed out. (If someone wants to give me triage privs in this repo I can do so myself hah).

**Comment by tflidd** [comment]
Structure changed a bit, check current version:
https://docs.nextcloud.com/server/latest/user_manual/en/files/sharing.html
