### ISSUE TITLE
config sample page in "latest" broken

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/documentation#2043]
The config sample documentation is broken when watching it in the _latest_ view (https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html). 
All parameters are missing :-(
18 works (https://docs.nextcloud.com/server/18/admin_manual/configuration_server/config_sample_php_parameters.html)

**Comment by wiswedel** [comment]
@juliushaertl Do you have any clue?
Did I break something in https://github.com/nextcloud/documentation/pull/1896?

**Comment by MorrisJobke** [comment]
> Did I break something in #1896?

This change is usually overwritten by a job that takes the config sample and pastes it into the docs. So you need to change it there: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L610

**Comment by MorrisJobke** [comment]
it's this tool here: https://github.com/MorrisJobke/nextcloud-config-converter

**Comment by wiswedel** [comment]
Thank you for the enlightening, @MorrisJobke! 
PR is open.

**Comment by MorrisJobke** [comment]
I found also the issue for this. It was @ChristophWurst cleaning up the core code: https://github.com/nextcloud/server/commit/b80ebc96748b45fd2e0ba9323308657c4b00b7ec#diff-2f769bc01ffefdf14eb04404218e7582

I fixed it in https://github.com/MorrisJobke/nextcloud-config-converter/commit/1d2c17a9e9ecb6efdb3acd27e51ba06af4104af2 and will re-run the sync job then.

**Comment by MorrisJobke** [comment]
And back they are: 9eb12ba47deb91541be6e74c46c120d328dde181

**Comment by wiswedel** [comment]
> And back they are: [9eb12ba](https://github.com/nextcloud/documentation/commit/9eb12ba47deb91541be6e74c46c120d328dde181)

Awesome.
Does the documentation web server have to be reloaded or so? The page doesn't show it yet.

**Comment by MorrisJobke** [comment]
> Does the documentation web server have to be reloaded or so? The page doesn't show it yet.

It only builds one a day. So it will be there tomorrow. Is this okay?

**Comment by wiswedel** [comment]
> It only builds once a day. So it will be there tomorrow. Is this okay?

Totally. Thanks
