### ISSUE TITLE
wrong manual steps in how to upgrade guide

### ISSUE THREAD

**Issue by cortex3** [nextcloud/documentation#2045]
I've noticed that all versions of the nextcloud documentary show the steps for Nextcloud 13 in the how to upgrade chapter.
Example:
https://docs.nextcloud.com/server/18/admin_manual/maintenance/upgrade.html
This is the Nextcloud 18 documentary but It's still showing the NC 13 steps.

**Comment by cortex3** [comment]
Looks like the change was introduced in https://github.com/nextcloud/documentation/commit/e968661e344a59f6fe69c6681706612ad48babf8

I'm a bit confused by this repository, seems like the documentaries are split across branches.

**Comment by MorrisJobke** [comment]
That looks like a leftover. It was introduced in Nextcloud 13, but still is sometimes good to execute. We detect this automatically and give the admin a hint in the setup checks in the admin panel. So I guess it's fine to remove the section there.

**Comment by MorrisJobke** [comment]
Fix is in #2051
