### ISSUE TITLE
Server URI for Synchronizing with iOS

### ISSUE THREAD

**Issue by kw90** [nextcloud/documentation#2049]
Hi,

I just set up a iOS device for synchronization with an NextCloud instance running on version 16.0.1 and found that the proposed URI in the [documentation](https://docs.nextcloud.com/server/16/user_manual/pim/sync_ios.html#contacts)

```
example.com/remote.php/dav/principals/users/USERNAME/
```

did not work. As I was testing with Android at the same time, I noticed a different URI after configuring it with DAVx^5 and tested this with the iOS device. The URI that worked looked like

```
example.com/remote.php/dav/addressbooks/users/USERNAME/
```

Seems like the path after `dav` with `principals` was replaced by `addressbooks`. This should be corrected in the documentation for this version.

Thanks! :)

Edit: Add link to relevant page in docs

**Comment by MorrisJobke** [comment]
cc @georgehrke @tobiasKaminsky @rullzer

**Comment by MorrisJobke** [comment]
@kw90 Mind to open directly a pull request against the page of the documentation here?

**Comment by georgehrke** [comment]
The URL for iOS is correct. Please make sure that you fix your server config.
The well-known URL is most likely not properly resolving.

**Comment by tobiasKaminsky** [comment]
No idea for Android. This is done by awesome davX5 app and working normally out of the box.

**Comment by kw90** [comment]
> The URL for iOS is correct. Please make sure that you fix your server config.
> The well-known URL is most likely not properly resolving.

Thanks for the feedback guys! Seems to be a missing Nginx configuration in the above linked Docker image(s) that I am using. Closing this, as it has to be fixed over there.
