### ISSUE TITLE
has_rebuilt_cache - is not documented anywhere

### ISSUE THREAD

**Issue by GAS85** [nextcloud/documentation#2050]
Hello, in my `config.php` I found the line:

    'has_rebuilt_cache' => true,

But it is nowhere documented. Could you please added description of it? Have no idea what this means and why it is added.

**Comment by MorrisJobke** [comment]
I can't find this in the server code. This seems to originate from an app (which usually shouldn't put config in the config.php but rather into the appconfig DB table). So this needs to be documented in that app: https://apps.nextcloud.com/apps/carnet
