### ISSUE TITLE
Login Flow v2 Documentation

### ISSUE THREAD

**Issue by boyi01** [nextcloud/documentation#2077]
Hey,

at the moement i try to build an with Flutter for the Cookbook App,

For this i want to use the login Flow v2..

but i miss the callback URL in the doc...

i do guess:
https://cloud.example.com/index.php/login/v2/grant

is this correct? or a other?

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/pull/14161

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/18/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2

What do you need a callback url for?

**Comment by boyi01** [comment]
I guess i just missunderstood some stuff, understand it know so you right i don't one

**Comment by kesselb** [comment]
Great! Looking forward to your app :+1:
