### ISSUE TITLE
Missing /

### ISSUE THREAD

**Issue by schnello** [nextcloud/documentation#208]
Hello.

Could you please review the script at the following page:
https://docs.nextcloud.com/server/10/admin_manual/installation/installation_wizard.html#strong-perms-label

```
find ${ocpath} -type f -print0 | xargs -0 chmod 0640
find ${ocpath} -type d -print0 | xargs -0 chmod 0750
```

In my opinion an "/" is missing and critical... in the worst case it makes the system unusable.
```
find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750
```

Br,
Christian

**Comment by MariusBluem** [comment]
Hi Christian,
Thank you for your report. Can you open a Pull Request?

cc @MorrisJobke

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/documentation/pull/209

**Comment by schnello** [comment]
Thank you for merging
