### ISSUE TITLE
Upgrade script has no documentation

### ISSUE THREAD

**Issue by rbcouture-csiflex** [nextcloud/documentation#213]
From the discussion [here](https://help.nextcloud.com/t/what-is-the-recommended-installation-method/585/15), It would be nice to show the steps required to upgrade nextcloud with the upgrade script.
Somewhere on [this page](https://github.com/nextcloud/documentation/blob/master/admin_manual/maintenance/upgrade.rst)

Thanks

**Comment by juliushaertl** [comment]
Alredy fixed. The update script got replaced by the new updater.
