### ISSUE TITLE
version control setting: "disabled" is the description accurate?

### ISSUE THREAD

**Issue by whitel** [nextcloud/documentation#2151]
On https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/file_versioning.html?highlight=version the description of "disabled" is "Disable Versions; no files will be deleted." 

Is this accurate? or should it say something like "No versions will be retained"?

**Comment by jneplokh** [comment]
The documentation seems accurate. The "Versions" (files_versions) referred to here is the app, which manages the automatic deletion of file versions to make sure users do not exceed their storage quota. Therefore, disabling it would disable the automatic deletion.

Although, it is somewhat confusing (as evident by this issue), perhaps it should say "Disable the Versions app; no files will be deleted."?

**Comment by MorrisJobke** [comment]
> Although, it is somewhat confusing (as evident by this issue), perhaps it should say "Disable the Versions app; no old file versions will be deleted."?

Yep - that makes it more clear 👍 Do you mind to open a PR with this change? :)
