### ISSUE TITLE
Manual has wrong query for 4 byte update on mariaDB 10.4 (and possibly a bit older).

### ISSUE THREAD

**Issue by noci2012** [nextcloud/documentation#2153]
The procedure here:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
Fails for 10.3 or later in Step 3: due to a missing column FILE_FORMAT 
There is no way to get that information in 10.4 and up.
So the step should be skipped. (possibly a hint can be derived from compatible data 
for Baracuda formats (like row_format = compressed, or row_format=dynamic).
Enquiry with mariaDB yielded:

> Enquiry with MariaDB  yields:

Question: Miising FILE_FORMAT column in INNODB_SYS_TABLES
Title: Re: Missing FILE_FORMAT column in INNODB_SYS_TABLES
User: Marko Mäkelä
INFORMATION_SCHEMA.INNODB_SYS_TABLES is a hard-coded view that is provided to the InnoDB internal data dictionary table SYS_TABLES that resides in the system tablespace. The column FILE_FORMAT does not have any direct counterpart in SYS_TABLES.
The configuration parameters innodb_file_format and innodb_large_prefix were deprecated in MariaDB 10.2.2 when the InnoDB changes from MySQL 5.7.9 were merged. The motivation for the deprecation and removal was that originally these parameters were introduced to supposedly allow downgrading to older versions than MySQL 5.5. To make matters worse, the default values of these parameters caused the files to remain in the backward-compatible format. Only MySQL 5.7 and MariaDB 10.2 would change the defaults to sane values and deprecate these useless parameters. (The predecessors of MySQL 5.5 were already EOL at that point, and besides, we do not really support downgrades.)
Those 2 deprecated parameters were removed in MariaDB 10.3, but they were put back later in MDEV-18399, because the sane defaults were explicitly specified in commonly used configuration files.
I do not think that it makes sense to carry the column in INNODB_SYS_TABLES.
Note: In MariaDB 10.3 and MariaDB 10.4, InnoDB file formats were extended by MDEV-11369 and MDEV-15562. You can disable those format changes by
SET GLOBAL innodb_instant_alter_column_allowed=never;
which was implemented in MDEV-20590.

I guess going forward from step 4  should be the way to go.

The ALTER Query can be done better aswell... 
using 
```
MariaDBl> SELECT CONCAT("ALTER TABLE `", TABLE_SCHEMA,"`.`", TABLE_NAME, "` ROW_FORMAT=DYNAMIC;") AS MySQLCMD FROM TABLES WHERE TABLE_SCHEMA = "nextcloud" and row_format != 'Dynamic'  into /tmp/alter.sql;
```
The file is then ready to be process possibly with
`MariaDB> \. /tmp/alter.sql`

So the manual needs some adjusting from MariaDB 10.3.0 onward.

**Comment by ChristophWurst** [comment]
:eyes: @nickvergessen

**Comment by nickvergessen** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-3-or-later
The 10.3 section doesn't contain the query. After step 1 you are told to continue in the mysql manual at step 2

**Comment by nickvergessen** [comment]
It should say step 3 thou, so let's keep this open to fix that
