### ISSUE TITLE
Add / Improve developer documentation about creating an (admin) UI

### ISSUE THREAD

**Issue by jbreitung** [nextcloud/documentation#2162]
Hi there again,

as I already mentioned in my post [https://help.nextcloud.com/t/cannot-develop-own-backgroundtask-when-using-nextcloud-developer-documentation/83411/6](https://help.nextcloud.com/t/cannot-develop-own-backgroundtask-when-using-nextcloud-developer-documentation/83411/6) we are having some real issued to get started with the development of an (admin) UI for our first Nextcloud App using the Nextcloud developer documentation.

It would be very helpful to provide some basic App UI documentation which describes the main cases “file selection” and “CRUD with CSRF via the Apps routes”.

**Comment by joshtrichards** [comment]
Fixed in #7178
