### ISSUE TITLE
Reference to ownCloud

### ISSUE THREAD

**Issue by janvlug** [nextcloud/documentation#2171]
This [page](https://docs.nextcloud.com/desktop/2.2/conflicts.html) states:
The **ownCloud** desktop client uploads...

**Comment by MorrisJobke** [comment]
You can find this file in https://github.com/nextcloud/desktop/blob/master/doc/conflicts.rst 

We would welcome a pull request :) Thanks for finding this.

**Comment by jneplokh** [comment]
Since the OP did not respond, I made a PR for it :)
