### ISSUE TITLE
Migrate documentation from RST (Sphinx) to Markdown (e. g. VuePress)

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/documentation#2192]
While trying to make my first contribution, i failed to setup a development environment.

I propose to switch from the **r**e**S**tructured**T**ext by `Sphinx` to any Markdown based system like [`VuePress`](https://vuepress.vuejs.org/) because

- Each and every formatting in the whole Nextcloud ecosystem is done by Markdown (Text, Deck, Notes, ...). Why making a break here?
- Markdown is very common for every developer, especially here on GitHub.
- It does not require a development environment
  - Using Markdown allows editing with auto-of-the-box syntax highlighting in nearly every editor as well as directly editing in GitHub itself. No need to setup a complex environment.
- There are also [`GitHub Actions`](https://github.com/marketplace/actions/deploy-to-vuepress) available for a completely automated CI / CD as well as various export mechanisms like `PDF` for most other tools like `VuePress` or `GitBook` or various other systems just like for `Sphinx`
- ~~It matches the technology stack which is recommended by Nextcloud itself (It's a commitmend to `VueJS` as frontend language)~~
- See this comment for further, more detailed infos: https://github.com/nextcloud/documentation/issues/2192#issuecomment-654218837

**Comment by MorrisJobke** [comment]
Can it output to PDF? Because that is what we use to generate the user manual we put into the releases.

**Comment by MorrisJobke** [comment]
cc @jospoortvliet @skjnldsv @rullzer 

Also the docs are quite common in the tech scene. The typically readthedocs theme is a known theme that makes it easier to navigate the documentation. Also moving this over is really a lot of work and also the URLs need to stay the same as we have them out there in the wild.

**Comment by MorrisJobke** [comment]
> *
> * There are also [`GitHub Actions`](https://github.com/marketplace/actions/deploy-to-vuepress) available for a completely automated CI / CD

That's also possible right now with sphinx.

**Comment by MorrisJobke** [comment]
> * It matches the technology stack which is recommended by Nextcloud itself (It's a commitmend to `VueJS` as frontend language)

That should not be an argument for a documentation tool. As we use it to document and not develop this tool.

**Comment by stefan-niedermann** [comment]
>  The typically readthedocs theme is a known theme that makes it easier to navigate the documentation.

Well, documentations are always based on the same basic layout - a tree-style navigation at the left side with a search box in the top - main content in the rest of the area. There is nothing special about this layout (that's fine - it's a documentation after all).

`VuePress` for example support themes and i am pretty sure that there will be one which is similar to the current one.

> That's also possible right now with sphinx.

That's why i wrote "also" :wink: Just wanted to make sure that this is not a missing feature.

> That should not be an argument for a documentation tool. As we use it to document and not develop this tool.

I don't necessarily insist on `VuePress` - because you are right: the language of the tool is irrelevant for a documentation tool. Way more important is **how easy it is to read and to write stuff**.
- Regarding **reading**: Nearly every tool supports HTML and PDF export, so this doesn't matter ([yes there are ways to generate PDFs with `VuePress`](https://www.npmjs.com/package/@snowdog/vuepress-plugin-pdf-export))
- Regarding **writing**: Markdown will make it way easier for new users to contribute, as it has a wider adoption, especially within the Nextcloud ecosystem as i wrote.

So, don't nail this issue down to `VuePress` - you can choose `GitBook` or a thousand other tools as well. If it helps, i will change the title to "Migrate documentation from RST to Markdown" which is my primary intention - i just used `VuePress` because it's a personal preference :man_shrugging:

**Comment by MorrisJobke** [comment]
> So, don't nail this issue down to `VuePress` - you can choose `GitBook` or a thousand other tools as well. If it helps, i will change the title to "Migrate documentation from RST to Markdown" which is my primary intention - i just used `VuePress` because it's a personal preference 🤷‍♂️

That sounds good :) And yes - documentation should also be easy to change. And I also need to say that bringing Sphinx up and running is a bit of work TBH.

**Comment by gary-kim** [comment]
Yeah, the difficulty in setting up the build for the documentation is also why [my Nextcloud build script](https://github.com/gary-kim/nc-build-script) does not bother including documentation at the moment.

We should discuss a bit about what the best tool to migrate to will be. Using markdown would be nice as it would make it easier for people to get started though restructredText does include way more of what we need in the standard. Using markdown will mean that we need to use a modified variant of markdown but it's usually pretty simple.

I'm gonna put Hugo in the list as well since it's what I use for public documentation.

**Comment by ChristophWurst** [comment]
:-1: from my side. I also used to prefer markdown over rst at the beginning. But markdown is **really** limiting in what it can do, you'll notice once you start linking your larger docs together. Labels and links are great in rst, there is no such thing in md, only relative and absolute *URLs*.

**Comment by stefan-niedermann** [comment]
@ChristophWurst it is nice that we have a sharp sword with unlimited possibilities using RST and i agree that it is probably way more powerful than markdown.

But i am asking my self why

- the documentation for the **Android stuff** seems to be abandoned (rhetorical question, @tobiasKaminsky already gave a clear statement in the Talk community chat)
- the documentation for the **Deck server app** is actually pretty good but [completely written in markdown](https://github.com/nextcloud/deck/tree/master/docs) and hosted on [deck.readthedocs.io](https://deck.readthedocs.io/en/latest/) instead of here @juliushaertl 
- the documentation for the **Talk server app** is also [completely written in markdown](https://github.com/nextcloud/spreed/blob/master/docs/index.md) and no idea where it is hosted - definitely not at the official docs. @nickvergessen 

I suspect they are all splintered because noone wanted to deal with RST :man_shrugging: .
This was also fine for me, in this case the Android stuff should maybe be split out and moved to the `docs` folder in the Android repository @tobiasKaminsky ? Since i only wanted to contribute to the Android stuff this would be sufficient for me and we can close the issue at this point. :smile: 

But to be honest, as a user i would expect all the documentation of all official apps in one place - at least as kind of a brace which links to all the different app documentations. And as a contributor who wants to enhance the documentation, i want to deal with markdown (which i am probably already familiar to because i am using GitHub).

**Comment by MorrisJobke** [comment]
> This was also fine for me, in this case the Android stuff should maybe be split out and moved to the `docs` folder in the Android repository @tobiasKaminsky ? Since i only wanted to contribute to the Android stuff this would be sufficient for me and we can close the issue at this point. 😄

The Android stuff does make very little sense. Because if you need to document how the app works, then we should refine the app itself. All the stuff that is written as of now in the android manual is self explanatory in the app itself.

**Comment by ChristophWurst** [comment]
I'm not sure if everything should be in one place because the versioning of the three main manuals here is tightly coupled to server releases whereas Nextcloud apps and mobile apps are mostly independent of that.

> I suspect they are all splintered because noone wanted to deal with RST man_shrugging

My take: very few people want to or enjoy writing docs. It they don't it really doesn't matter.

**Comment by nickvergessen** [comment]
Talk is also at `readthedocs`: https://nextcloud-talk.readthedocs.io/en/latest/ and I followed deck I think while doing it.

> I suspect they are all splintered because noone wanted to deal with RST 

For me the reason was that the docs are bound to the talk version, which might or might not be related to the server version, and with the current place they can be adjusted in the same PR, which always helps.

**Comment by stefan-niedermann** [comment]
>  if you need to document how the app works, then we should refine the app itself

Absolutely agree for the Users documentation, but the Developers documentation should contain information about how to use `nextcloud-library` and `android-singlesignon` libs.

> very few people want to or enjoy writing docs

Granted :laughing: therefore it should be as simple as possible to write documentation (*IMHO*)

> For me the reason was that the docs are bound to the talk version, which might or might not be related to the server version, and with the current place they can be adjusted in the same PR, which always helps.

I get that it makes sense to split up the documentations, but then
- The android stuff should go to the correspond repository
- There should be links from the "main" documentation
- I still don't get why every official app hosts at readthedocs.io or whereever they want and the main documentation doesn't. Why don't you all use the same system?

**Comment by tobiasKaminsky** [comment]
> Absolutely agree for the Users documentation, but the Developers documentation should contain information about how to use `nextcloud-library` and `android-singlesignon` libs.

Yes, this should/need to be enhanced.


>     * I still don't get why every official app hosts at readthedocs.io or whereever they want and the main documentation doesn't. Why don't you all use the same system?

This is indeed something that feels strange and we should put some energy in it, to have it consistent.

**Comment by nickvergessen** [comment]
`readthedocs` comes with auto-deploying and can be done quickly without sysadmin interaction? :man_shrugging:

**Comment by ChristophWurst** [comment]
This means we should keep the aspects of documentation separate

a) Means two write the docs
b) Means to deploy the docs

Working with the dev docs a lot the last few months I've seen the advantages of sphinx and it would be a terribly move to replace the sophisticated solution with a simplistic but limiting one in my honest opinion. In fact, I would argue that sphinx is not even that far off from Markdown for the most parts. So spend 10 minutes on a little tutorial or simply see how the other docs were written, and you'll get the concept. If that is still barrier for you, then you'll also find reasons not to use Markdown. You will definitely not need to have a deep understanding of sphinx to do little fixes or add a paragraph here or there.

**Comment by stefan-niedermann** [comment]
Fine for me, was just a suggestion 🙂
