### ISSUE TITLE
Gallery app documentation doesn't correspond to real life.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/documentation#2199]
1. There's no such app as _Gallery_. It's called _Photos_.
2. One can't find any buttons for gallery in the top right corner but only in the list of applications in the top bar.
3. There are no sorting options shown.

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Right 
https://docs.nextcloud.com/server/19/user_manual/files/gallery_app.html

**Comment by joshtrichards** [comment]
#5158

Gallery docs are gone. Closing.
