### ISSUE TITLE
html source pages contain owncloud in id

### ISSUE THREAD

**Issue by PeterEdens** [nextcloud/documentation#224]
Hi,
in some of the pages there is a reference to owncloud in the id of the element:

id="owncloud" tabindex="1">

this should be changed to nextcloud.

I have seen this in access_webdav.html, index.html and federated_cloud_sharing.html

**Comment by MariusBluem** [comment]
Thank you for reporting that 😅🙈 do you want to submit a PR?

**Comment by Tronde** [comment]
Is this issue still relevant? I could not find the mentioned files in the current master branch.

**Comment by PeterEdens** [comment]
It looks like it has been fixed, I will close the issue.
