### ISSUE TITLE
Create client documentation pages

### ISSUE THREAD

**Issue by pixolin** [nextcloud/documentation#227]
Hi. After installing the Nextcloud desktop client on my Mac I was curious if I could find some more information about the bandwidth throttle. 

It turns out, that the Help link (right-click on the desktop client icon > Help) links to webpage https://docs.nextcloud.com/desktop/2.2/, which returns a _404 – File not found_ error. Seems to be some legacy from the fork, as https://doc.owncloud.org/desktop/2.2/ is accessible.

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by tflidd** [comment]
Now there is a documentation page when you open the URLs:
https://docs.nextcloud.com/desktop/2.2/
