### ISSUE TITLE
Theming: Add documentation on themed icons

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/documentation#233]
Add documentation for imagemagick dependencies on nextcloud/server#840

**Comment by MorrisJobke** [comment]
Ping @juliushaertl ;)

**Comment by juliushaertl** [comment]
@MorrisJobke done in #233 :wink:

**Comment by MorrisJobke** [comment]
> @MorrisJobke done in #233 😉

but it is #248 😉

**Comment by juliushaertl** [comment]
:see_no_evil: to much numbers, but you've found it :wink:
