### ISSUE TITLE
Improve section about encryption

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#235]
The page on the nextcloud-doc is very short:
https://docs.nextcloud.com/server/10.0/user_manual/files/encrypting_files.html?highlight=enabling%20encryption

and it is missing some essential information (how to use occ command with this, default encryption module, ...), just compare it to:
https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/encryption_configuration.html

**Comment by wiswedel** [comment]
Documentation has been enhanced in the meantime: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html
