### ISSUE TITLE
Please stop changing URL's...

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/documentation#2410]
Hi team,

Lots of pages on the internet link to our developer documentation, including our own website. Please stop re-arranging things and changing URL's - most of the changes (from "app" to "digging_deeper") are mostly arbitrary and really do more damage breaking links than help people find things.

Ref
https://github.com/nextcloud/nextcloud.com/commit/c66f4f23bc6d170b4d1c6a2c64d72fda23843def

**Comment by dassio** [comment]
i think the new structure is much clearer for a newcomer, I really appriciate it .
