### ISSUE TITLE
NC 10: outside of the local network.

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/documentation#243]
https://docs.nextcloud.com/server/10/admin_manual/configuration_files/files_access_control.html

Should be another picture. This one - I think - displays the opposite:

![bildschirmfoto vom 2016-12-01 22-35-26](https://cloud.githubusercontent.com/assets/3857906/20813608/879ce454-b816-11e6-8792-64ed490b808a.png)

"The second rule group Internal testing prevents users of the Internal testers group to access files from outside of the local network."

**Comment by tflidd** [comment]
NC 10 is no longer supported. There are other issues on the NC 12 version:
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/access_control.html
all the pngs get a 404 error!

And there is no corresponding page in the NC 13 documentation!

@jospoortvliet @nickvergessen

**Comment by MariusBluem** [comment]
I will take care of this.

**Comment by MorrisJobke** [comment]
Fixed with #689
