### ISSUE TITLE
Adjust Header

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#244]
cc @Espina2 @jospoortvliet

**Comment by jancborchardt** [comment]
@Espina2 any progress here? Would be really cool to have the same header on docs.nextcloud.com as we have on the rest of the website. :)

cc @nextcloud/website

**Comment by Espina2** [comment]
@jancborchardt 
I don't have any know how with Sphinx maybe anyone familiar with that can help...

**Comment by jancborchardt** [comment]
cc @nextcloud/documentation can anyone of you help here?

**Comment by MorrisJobke** [comment]
> cc @nextcloud/documentation can anyone of you help here?

We all need to dig into this :/
