### ISSUE TITLE
SMB - one listener for all shares

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#249]
@icewind1991 Is there such a thing for the smb:notify command? (like the wnd:listen at OC)

**Comment by MorrisJobke** [comment]
ref #203

**Comment by icewind1991** [comment]
There isn't, if there is a demand I can add it

**Comment by icewind1991** [comment]
(note that it is inherently limited so I'm not fully convinced about it usefullness)

**Comment by MorrisJobke** [comment]
> There isn't, if there is a demand I can add it

I guess it would make the setup of such an notify service easier. (only run one command instead of one for each share)

**Comment by MorrisJobke** [comment]
> (note that it is inherently limited so I'm not fully convinced about it usefullness)

Then propose a way to automatically generate maybe systemd files, that only need to be put into the correct folder and then are enabled by the admin. Otherwise setting this up is a nightmare.
