### ISSUE TITLE
Permissions script breaks updater

### ISSUE THREAD

**Issue by Lartza** [nextcloud/documentation#255]
The script presented on https://docs.nextcloud.com/server/11/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions breaks the updater as it expects there to be no assets folder.

**Comment by MorrisJobke** [comment]
Good point. The assets dir is not there anymore and will also not be used in the future. @Lartza Could I ask you to remove the stuff that creates and modifies the assets dir?
