### ISSUE TITLE
Please update documentation (Web <-- Github)

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/documentation#267]
While updating Nextcloud, I just noticed, that the web page (which is linked from the installation page https://nextcloud.com/install/#instructions-server )

* https://docs.nextcloud.com/server/10/admin_manual/maintenance/manual_upgrade.html

is partially incorrect (and I wanted to correct it), but the github page appears to be correct

* https://github.com/nextcloud/documentation/edit/master/admin_manual/maintenance/manual_upgrade.rst

When do you upgrade the web page/s  from github ?

**Comment by nickvergessen** [comment]
what exactly is different?

**Comment by Wikinaut** [comment]
see for example point 10 (restarting the webserver)

**Comment by Wikinaut** [comment]
webpage shows:

```
Now launch the upgrade from the command line using occ, like this example on CentOS Linux:
sudo -u apache php occ upgrade
```

(-u apache is wrong, because all other examples use Ubuntu syntax and user must be -u www-data)

github simply say:
```
10. Restart your Web server.
```

**Comment by nickvergessen** [comment]
well master is 11, 10 is here https://github.com/nextcloud/documentation/blob/stable10/admin_manual/maintenance/manual_upgrade.rst

Feel free to backport the change

**Comment by Wikinaut** [comment]
You do not understand. both branches (10, 11) appears better than the current web version, pls. check the point 10 (on the web). Where is the source for the web version ?

**Comment by nickvergessen** [comment]
Yes I do understand, but the stable10 branch of the docs also says `-u apache`:
https://github.com/nextcloud/documentation/blame/stable10/admin_manual/maintenance/manual_upgrade.rst#L53-L57

This branch is used to build the web docs in https://docs.nextcloud.com/server/10/admin_manual/ , it's done automatically all 6 hours iirc.

**Comment by Wikinaut** [comment]
see https://github.com/nextcloud/documentation/pull/269
