### ISSUE TITLE
Update manual is invalid

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/documentation#268]
@MorrisJobke can you adjust https://docs.nextcloud.com/server/11/admin_manual/maintenance/update.html for your updater.
At least the mentioned `--skip-migration-test` does not exist anymore. But I guess it also needs some adjustments for the updater aswell?

**Comment by MorrisJobke** [comment]
https://www.c-rieger.de/nextclouds-new-updater-app-how-to/ is an awesome updater guide. Thanks to @riegercloud - you rock

**Comment by MorrisJobke** [comment]
Was completely updated. See #460
