### ISSUE TITLE
Nextcloud 11 documentation fix needed

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/documentation#270]
https://github.com/nextcloud/documentation/blob/stable11/admin_manual/maintenance/manual_upgrade.rst

```
Section 9 Adjust file ownership and permissions

   chown -R www-data:www-data nextcloud 
   find nextcloud/ -type d -exec chmod 750 {} ;
   find nextcloud/ -type f -exec chmod 640 {} ;
```
is rendered incorrectly:

![20161213-23 29 15_auswahl](https://cloud.githubusercontent.com/assets/1151915/21162122/0208ce50-c18c-11e6-8423-2eacad81a681.png)

Yes, I tried to fix this, but without success (I got crazy by editing this rst file...)

**Comment by jospoortvliet** [comment]
What do you think about https://github.com/nextcloud/documentation/pull/278 ??? If ok, approve it ;-)
