### ISSUE TITLE
new line in shell command

### ISSUE THREAD

**Issue by blackm** [nextcloud/documentation#277]
https://github.com/nextcloud/documentation/blame/master/admin_manual/maintenance/manual_upgrade.rst#L53 and the following two lines are not well displayed on https://docs.nextcloud.com/server/11/admin_manual/maintenance/manual_upgrade.html - the line brake is missing with the result that copy'n'pasts the command will not work.

Is there a way to force a newline, like `<br>` ? also the `\` is not displayed....

Sorry, my knowledge on this rst text files is very poor :-(

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/nextcloud/documentation/pull/278

**Comment by MorrisJobke** [comment]
Will be updated this night automatically ;)
