### ISSUE TITLE
Enabling MySQL 4-byte support (mariaDB)

### ISSUE THREAD

**Issue by riegercloud** [nextcloud/documentation#286]
Hi Guys,
i find a small issue regarding your doc:
https://docs.nextcloud.com/server/11.0/admin_manual/maintenance/mysql_4byte_support.html

please change (2.)
...
innodb_file_per_table=true to **innodb_file_per_table=1**

otherwise you can't migrate the database file format to Barracuda.
Having changed this setting i was able to migrate successfully!
Cheers, Carsten

**Comment by MorrisJobke** [comment]
Fix is in #287

**Comment by MorrisJobke** [comment]
Fixed in 12 and 11 manual

**Comment by riegercloud** [comment]
the
> innodb_large_prefix=**_on_**

should be adjusted either to:

[mysqld]
innodb_large_prefix=**true**

for both version: 11 and 12.
cheers, carsten

**Comment by nickvergessen** [comment]
@riegercloud can you make a PR?

**Comment by riegercloud** [comment]
never did it before but now: https://github.com/nextcloud/documentation/pull/451
hopefully as expected?

**Comment by MorrisJobke** [comment]
stable11 af2bbe0d
stable12 70c6448f
master e190183f

**Comment by danger89** [comment]
I think something needs to be changed in the manual yet again. I'm using MariaDB v10.3, and this whole innodb_file_format (_max) is now removed. So this MariaDB manual is very confusing for me.

**Comment by nickvergessen** [comment]
Thanks for the hint @danger89 I fixed the docs in https://github.com/nextcloud/documentation/pull/910
You can also find a screenshot of the updated docs there, so you can follow it easier in case you didnt get it done sofar
