### ISSUE TITLE
Add link with more debug info for cal/cardDAV troubleshoot-page

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#289]
For setting up calDAV and cardDAV, sabre.io gives more specific information for debugging. Perhaps we can add a link to our documentation, thanks to foomep (https://help.nextcloud.com/t/ios-calendar-contacts-sync/6612):

On the website you can find more infos: http://sabre.io/dav/service-discovery/3
Maybe it would be good to mention this on https://docs.nextcloud.com/server/9/admin_manual/issues/general_troubleshooting.html#troubleshooting-contacts-calendar

**Comment by MariusBluem** [comment]
Seems to be done.

**Comment by vrubiolo** [comment]
Just a note to mention that the link for SabreDav service discovery is actually https://sabre.io/dav/service-discovery/ (as is correctly mentioned in https://docs.nextcloud.com/server/18/admin_manual/issues/general_troubleshooting.html#service-discovery).

This is just for the record, as I ended up on this issue while investigating iOS caldav sync issues.
