### ISSUE TITLE
Adjust Docs to the new AppStore

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#308]
**admin_manual/installation/apps_management_installation** should be adjusted to the new Nextcloud App Store 😁  

Follow up of https://github.com/nextcloud/server/issues/2976

cc @BernhardPosselt @jbicha

**Comment by Chartman123** [comment]
Is this still an issue? I can't find the mentioned page...

**Comment by MorrisJobke** [comment]
Let's close it then.
