### ISSUE TITLE
Typo: Wrong MySQL setting for MySQL 4-byte support

### ISSUE THREAD

**Issue by RudiScholz** [nextcloud/documentation#311]
Step 2 of the documentation on how to enable 4byte UTF8 support with MySQL (https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html) contains a typo. It states 
`innodb_large_prefix=true`, however the correct syntax is `innodb_large_prefix=ON`.

With the correct setting, I have now nice Emojis in my NextCloud 11 together with MariaDB 10.1 on Debian Testing .  

Regards,
Ruediger

**Comment by MorrisJobke** [comment]
cc @nickvergessen @MariusBluem

**Comment by MariusBluem** [comment]
correct 😅 http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

**Comment by MariusBluem** [comment]
@RudiScholz Do you want to open a pull-request changing this file: https://github.com/nextcloud/documentation/blob/master/admin_manual/maintenance/mysql_4byte_support.rst 👊😅

**Comment by nickvergessen** [comment]
Also in https://github.com/nextcloud/documentation/blob/master/admin_manual/admin_manual/installation/system_requirements.html

**Comment by MariusBluem** [comment]
> Also in https://github.com/nextcloud/documentation/blob/master/admin_manual/admin_manual/installation/system_requirements.html

He meant: https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst 😜
