### ISSUE TITLE
Document "Please use the command line updater because you have a big instance" metrics

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#318]
> The web updater is disabled if either the config flag is set (upgrade.disable-web https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1296) or user_ldap is enabled or user_shibboleth is enabled (https://github.com/nextcloud/server/blob/30689f338faf5327e13b65d3b4a2d85f9e79064d/lib/base.php#L340-L351).
>
> If you have one of those apps enabled but don't need them: disable them and the web updater should work.

Ref https://github.com/nextcloud/server/issues/3128

**Comment by cmorty** [comment]
Also if you have more than 50 users (which is not necessarily a big database) https://github.com/nextcloud/server/blob/30689f338faf5327e13b65d3b4a2d85f9e79064d/lib/base.php#L345-L350).

**Comment by MorrisJobke** [comment]
Will be fixed with https://github.com/nextcloud/server/pull/4804
