### ISSUE TITLE
Document how to change the recovery key password 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#320]
cc @schiessle 

See https://github.com/owncloud/documentation/pull/2813

**Comment by MorrisJobke** [comment]
cc @MariusBluem

**Comment by joshtrichards** [comment]
Long ago completed and appears here:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html?highlight=recovery%20key#enabling-users-file-recovery-keys

Closing.
