### ISSUE TITLE
Code Comment In Filesystem Example Wrong

### ISSUE THREAD

**Issue by jarofgreen** [nextcloud/documentation#329]
https://github.com/nextcloud/documentation/blob/master/developer_manual/app/filesystem.rst

Section "Reading from a file"

The code comment says "// check if file exists and write to it if possible"

This has obviously been copied and pasted from the section above - "Writing to a file"

I know it's a small pedantic detail but may as well make it really clear for people using the documentation :-)

**Comment by tflidd** [comment]
You can make changes and create a pull request to correct it
