### ISSUE TITLE
Templates page has minor HTML error

### ISSUE THREAD

**Issue by jarofgreen** [nextcloud/documentation#330]
https://github.com/nextcloud/documentation/blob/master/developer_manual/app/templates.rst has 

    <img src="<?php print_unescaped(image_path('myapp', 'app.png')); ?> />

It's a minor thing but may as well get it perfect :-) The close quote is missing. It should be

    <img src="<?php print_unescaped(image_path('myapp', 'app.png')); ?>" />

**Comment by tflidd** [comment]
@jarofgreen fix is on the way: https://github.com/nextcloud/documentation/pull/339
