### ISSUE TITLE
Css guidelines summary

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/documentation#333]
https://docs.nextcloud.com/server/12/developer_manual/app/css.html
This is a list of what we need to do to update it
1. Rebuild icons list
2. Add popover explanations: https://github.com/nextcloud/server/issues/2798
    - Arrow position (padding right)
    - Popover types: text only, icon only, text+icon, paragraph
    - Popover alignment: right, center, left
3. Button design
    - text only, icon only, icon+text
4. Header menu
    - menu class
    - arrow position
5. App-navigation
    - Need active class on li for blue shadow
    - ul must be direct children of #app-navigation
    - `with-counter` `with-menu` `with-icon` not needed anymore
    - no need for the svg class
    - the icon class must have `icon-` in it to have the auto padding
    - rules about padding and margin of li elements
    - maximum nested menu is 1
    - icon menu custom in app-navigation-entry-utils
    - max icon h/w
    - bullet class
    - loading icon class to menu
    - encourage users to use the "deleted X" string
    - ability to set class in files nav -> pinned class

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
> Popover types: icon only

This should not exist. ;)

**Comment by jancborchardt** [comment]
cc @eppfel on this one

**Comment by jancborchardt** [comment]
@skjnldsv any update here? :)

**Comment by skjnldsv** [comment]
Okay, I will soon finally have the guts to attack this! :)
Wish me luck! :D

**Comment by MorrisJobke** [comment]
cc @Espina2 because we talked about this at the conf again and it was unclear who wants to look into this ;)

**Comment by skjnldsv** [comment]
I would be glad to work with someone on this. I think this is one of the biggest issue we have in our dev manual, and it leads many apps to inconsistency amongst them! :)

**Comment by jancborchardt** [comment]
@skjnldsv I'm down to contribute. :) We should also use this to standardize the Mail/Contacts column layout, using the classes from the Contacts app.

**Comment by skjnldsv** [comment]
I'm also on it! ^^'
Let me finish polishing all the scss on server, adding the latest classes, backporting and we'll be good to go on the docs! 🙈 🙌

**Comment by Espina2** [comment]
@MorrisJobke I will be completelly stuck in this month, so no time to help. :(
