### ISSUE TITLE
Favorite API

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#334]
We need to document the favorite API to use it in the mobile apps (cc @tobiasKaminsky @AndyScherzinger @mario @marinofaggiana )

Something like that seems to be the API for now:

They can be exposed from within WebDAV. During the PROPFIND for a folder just add `<oc:favorite />` to the request body:

```xml
<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:prop>
   <d:getlastmodified />
   <d:getetag />
   <d:getcontenttype />
   <d:resourcetype />
   <oc:fileid />
   <oc:permissions />
   <oc:size />
   <d:getcontentlength />
   <nc:has-preview />
   <oc:tags />
   <oc:favorite />
   <oc:comments-unread />
   <oc:owner-display-name />
   <oc:share-types />
 </d:prop>
</d:propfind>
```

Then the properties of that file contain: `<oc:favorite>1</oc:favorite>` if the file is a favourite or nothing it not.

Beside that there is a general API to get all files: `https://example.org/apps/files/api/v1/tags/_%24!%3CFavorite%3E!%24_/files`

This then returns a JSON object like here: 

```json
{"files":[{"id":23,"parentId":-1,"mtime":1484799137000,"name":"asd","permissions":9,"mimetype":"httpd\/unix-directory","size":163,"type":"dir","etag":"58803ca182cac","shareOwner":"abc@localhost\/server\/","isShareMountPoint":true,"mountType":"shared-root","path":"\/","tags":["_$!\u003CFavorite\u003E!$_"]}]}
```

@nickvergessen @schiessle @rullzer Can somebody of you please properly document this?

cc @karlitschek

**Comment by MorrisJobke** [comment]
> @nickvergessen @schiessle @rullzer Can somebody of you please properly document this?
> 
> cc @karlitschek

Ping. @marinofaggiana really needs this.

**Comment by marinofaggiana** [comment]
Yes, urgent please, GET & POST

**Comment by nickvergessen** [comment]
I have no idea, I just know that it's somewhere in dav. Maybe you can have a look at the requests the browser sends when you favor a file in the web UI

**Comment by mario** [comment]
You get favorites just like @MorrisJobke mentioned, and here's how to set/unset them:


Set favorite 

POST /apps/files/api/v1/files/path/to/file 

{tags: ["_$!<Favorite>!$_"]} 

To unfavorite use 

{tags: []} 

as body

You have to do this on a per-file basis.

**Comment by nickvergessen** [comment]
But that is not public API 🙊

**Comment by MorrisJobke** [comment]
> But that is not public API 🙊

Ah right 🙈 ... Interested in porting this to OC? 🙊

**Comment by marinofaggiana** [comment]
I don't understand ... POS ? but this API exists or not ? 😄

**Comment by MorrisJobke** [comment]
> I don't understand ... POS ? but this API exists or not ? 😄

It exists, but not in our public namespace. So we don't guarantee, that it will keep stable. We need to move this to a public endpoint if we want to use it outside of the web interface.

**Comment by MorrisJobke** [comment]
> It exists, but not in our public namespace. So we don't guarantee, that it will keep stable. We need to move this to a public endpoint if we want to use it outside of the web interface.

@AndyScherzinger @mario @tobiasKaminsky This is right, or? The android app only uses OCS and WebDAV, right?

**Comment by mario** [comment]
@MorrisJobke Yup.

**Comment by mario** [comment]
Since @icewind1991 was the one who told me about all this, maybe involve him :)

**Comment by icewind1991** [comment]
Imo it would make most sense to support setting/unsetting favorites (and tags in general) using PROPPATCH

**Comment by mario** [comment]
Do it!

**Comment by icewind1991** [comment]
After you give me feedback on the last DAV stuff I implemented for you

**Comment by icewind1991** [comment]
Turns out this is already possible, you can set tags and favorites using PROPPATCH

To favorite:

PROPPATCH remote.php/dav/files/username/path/to/file

```
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
      <oc:favorite>1</oc:favorite>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

Set tags:

PROPPATCH remote.php/dav/files/username/path/to/file

```
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
      <oc:tags>
        <oc:tag>tag1</oc:tag>
        <oc:tag>tag2</oc:tag>
      </oc:tags>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

Note that you need to specify the full tag list for a file, you can't just specify one that you want to add

**Comment by icewind1991** [comment]
> Beside that there is a general API to get all files: https://example.org/apps/files/api/v1/tags/_%24!%3CFavorite%3E!%24_/files

You can also list favorites in a more "DAV" way using 

    REPORT remote.php/dav/files/user/path/to/folder
    <?xml version="1.0"?>
    <oc:filter-files  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
    	 <oc:filter-rules>
    		 <oc:favorite>1</oc:favorite>
    	 </oc:filter-rules>
     </oc:filter-files>

Which will return the same XML format a when doing a `PROPFIND` and supports requesting properties in the same way as a `PROPFIND` by adding a `<d:prop/>` element to the request.
