### ISSUE TITLE
User metadata API

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#335]
@schiessle could you please properly document the user metadata API from https://github.com/nextcloud/server/pull/3232

Thanks

cc @tobiasKaminsky @AndyScherzinger @mario @marinofaggiana @karlitschek

**Comment by mario** [comment]
Would be good, but this is already implemented on Android :)

**Comment by MorrisJobke** [comment]
> Would be good, but this is already implemented on Android :)

Documenting it is always the way to do. Often we got also requests how to query the API and then refering to: "umm yes, just look how the Android app does it" isn't cool 😉

**Comment by mario** [comment]
Yes, of course :)

**Comment by MorrisJobke** [comment]
@marinofaggiana See the linked ticket. There is an example of how to use the API. Please make sure to check the server version first to not run into issues on older instances.

**Comment by mario** [comment]
@marinofaggiana new metadata works starting 11.0.2, but even before that you can get display name and email.

**Comment by marinofaggiana** [comment]
Thanks, i start now with API  a question, this return quota, email, twitter etc. ... but the image of user ?

**Comment by MorrisJobke** [comment]
> Thanks, i start now with API; a question, this return quota, email, twitter etc. ... but the image of user ?

The avatar is handled in a separate endpoint - @rullzer could you document the avatar endpoint as well? Is it also public?

We fetch this via `http://example.org/index.php/avatar/admin/64`

**Comment by MorrisJobke** [comment]
Fix in #364

**Comment by MorrisJobke** [comment]
fixed in #364
