### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#337]
@nickvergessen Please then also document the notifications API from https://github.com/nextcloud/notifications/pull/59

**Comment by nickvergessen** [comment]
Docs are going to be and already are in the PR

**Comment by MorrisJobke** [comment]
> Docs are going to be and already are in the PR

I guess we then need a page in the docs where we link all those stray documentation about API for different apps.

**Comment by MorrisJobke** [comment]
🙈

**Comment by MorrisJobke** [comment]
@marinofaggiana The API is documented already in the linked PR - see https://github.com/nextcloud/notifications/blob/push-notification/docs/push-v3.md

**Comment by marinofaggiana** [comment]
yes yes this is a good point 👍

**Comment by MorrisJobke** [comment]
Fix in #365
