### ISSUE TITLE
Replace owncloud with nextcloud

### ISSUE THREAD

**Issue by sentabi** [nextcloud/documentation#36]
since nextcloud already released, time to replacing all _owncloud_ string to _nextcloud_?

I've do that but on my own fork.

**Comment by MorrisJobke** [comment]
There where a lot of PRs in the last days that already accomplished that: See https://github.com/nextcloud/documentation/pulls?q=is%3Apr+is%3Aclosed

If you find something please report this more specifically, then we can fix this occurence. Thanks anyways :)

**Comment by schiessle** [comment]
> If you find something please report this more specifically, then we can fix this occurence. Thanks anyways :)

Or even better, send us directly a pull request if you already changed it on your instance. :smile:

**Comment by sentabi** [comment]
pull request send #38
