### ISSUE TITLE
Backing up Nextcloud - mysqldump parameter

### ISSUE THREAD

**Issue by mrclschstr** [nextcloud/documentation#375]
Hi everyone,

the article [Backing up Nextcloud](https://docs.nextcloud.com/server/11/admin_manual/maintenance/backup.html#backup-database) suggests the following command for backing up the MySQL tables using mysqldump (shortened):

`mysqldump --lock-tables -h [server] -u [username] -p[password] [db_name]`

The [official mysqldump documentation](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_lock-tables) states the following:

> For transactional tables such as InnoDB, --single-transaction is a much better option than --lock-tables because it does not need to lock the tables at all.

So, wouldn't it be a better solution to use the `--single-transaction` parameter instead?

Kind regards

**Comment by MorrisJobke** [comment]
Oh yes :) Thanks for spotting. Could I ask you to send a pull request with that change?

**Comment by mrclschstr** [comment]
I've never done this before, but I'll do my very best ;-)

**Comment by mrclschstr** [comment]
Hi everyone,

it's me again. A little bit off topic but still part of the same [Backing up Nexcloud](https://docs.nextcloud.com/server/11/admin_manual/maintenance/backup.html#backup-folders) article is the recommendation of the rsync command:

`rsync -Aax nextcloud/ nextcloud-dirbkp_``date +"%Y%m%d"``/`

I used this for quite some time to backup my nextcloud to a local folder. This local copy is then backed up by duply to an external destination. While doing some restores I discovered that this rsync command only adds files to the local folder and does not delete removed source files. As a result there are a lot of files in my local backup I removed a long time ago. I'd suggest to add a note to use the rsync `--delete` parameter to delete removed files in "persistent local backups". What do you think?

Kind regards

**Comment by tflidd** [comment]
The command should make a backup to a new folder each time, so I don't see why this is a problem. Also this is more like a one time backup before running an update.
For regular backups that don't use much storage, you might want take a look at rsnapshot.

**Comment by Tronde** [comment]
Hi,
I've sent a pull request to solve this issue. Thanks @mrclschstr for spotting that.
