### ISSUE TITLE
add to docs: share multiple calendars in one link

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/documentation#3810]
Possibility to share multiple calendars in one link (e.g. for iframe embedding) is already implemented: https://github.com/nextcloud/calendar/issues/708 but not documented yet: https://docs.nextcloud.com/server/18/user_manual/pim/calendar.html#publishing-a-calendar

context: https://github.com/nextcloud/calendar/issues/2289

**Comment by tcitworld** [comment]
Fixed in #5207
