### ISSUE TITLE
Discourage the use of subfolders for setups

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#396]
If you install Nextcloud in a subfolder, you get a warning on the security scan at scan.nextcloud.com
`
The __Host prefix mitigates cookie injection vulnerabilities within potential third-party software sharing the same second level domain. It is an additional hardening on top of 'normal' same-site cookies.
`
However, the configuration example in the documentation (https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html#apache-web-server-configuration) does not mention this problem and even uses this case by default.

@LukasReschke

**Comment by MariusBluem** [comment]
You are right. I think our current setup guide installs Nextcloud in the `/nextcloud/`-subdirectory which is not best practice 😉 Do you agree with changing that? @LukasReschke

**Comment by jpbegin** [comment]
@MariusBluem what are best practices? installing it in /var/www/ ?

**Comment by wiswedel** [comment]
Is this still an issue, or can we close this, @MariusBluem ?
I haven't had any issues myself or at customers with /var/www/nextcloud

**Comment by MorrisJobke** [comment]
Both kinds of setups are fine. So yes this can be closed.
