### ISSUE TITLE
Be more specific about apps which disable the "Stay logged in" checkbox

### ISSUE THREAD

**Issue by Luxoboy** [nextcloud/documentation#401]
I find the phrasing ambiguous in the [Web interface](https://github.com/nextcloud/documentation/blob/master/user_manual/webinterface.rst) page (line 18).

> Some apps like `files_external` or `encryption` will disable the Stay logged in checkbox.

It is unclear whether other apps disable it too.
I believe this a per app thing so maybe the conditions which make an app disable the checkbox should be added in the note.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
Afaik files_external no longer disables cookie login (cc @ChristophWurst )

**Comment by ChristophWurst** [comment]
Yup, we don't do that anymore with NC12+

**Comment by MorrisJobke** [comment]
@icewind1991 @ChristophWurst That means it is never disabled anymore?

**Comment by ChristophWurst** [comment]
Exactly. See https://github.com/nextcloud/server/pull/2044

**Comment by z3ntu** [comment]
@ChristophWurst If I understand these comments correctly, the warning should be removed from https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage_configuration_gui.html#enabling-external-storage-support

**Comment by ChristophWurst** [comment]
@z3ntu correct!

**Comment by wiswedel** [comment]
closing this issue because the affected versions are long deprecated
