### ISSUE TITLE
Dokuwiki Connection

### ISSUE THREAD

**Issue by chaot2** [nextcloud/documentation#407]
Hi,
is there a good possibility to connect the nextcloud with a dokuwiki?

To Connect the user-accounts - logi to the nextcloud with the dokuwiki-login or other way around?

To connect the dokuwiki media files with nextcloud, so you can add files in nextcloud and use in dokuwiki?

Is this working with a current nextcloud:
https://www.dokuwiki.org/plugin:owncloud
https://apps.owncloud.com/content/show.php/dokuwiki?content=158978

**Comment by MorrisJobke** [comment]
This repo is about the documentation of nextcloud. Maybe ask the author of the owncloud app to test it with nextcloud(usually should work out of the box) and maybe publish it in the nextcloud App Store as well. Thanks
