### ISSUE TITLE
NGINX -- officially supported or not?

### ISSUE THREAD

**Issue by Tronde** [nextcloud/documentation#420]
Hi folks,
I'm just studying the documentation and got into some struggle.

From [system requirements](https://docs.nextcloud.com/server/11/admin_manual/installation/system_requirements.html) supported platforms:

> Web server: Apache 2 (mod_php, php-fpm) or Nginx (php-fpm)

But the [nginx example configurations](https://docs.nextcloud.com/server/11/admin_manual/installation/nginx_examples.html) say:

> Note that Nginx is not officially supported, and this page is community-maintained. (Thank you, contributors!)

So, is it officially supported or not? If not, imho there should be a note at the system requirements chapter, that tell admins that running nextcloud on nginx is only community maintained.

Any other opinions on this?

Regards,
Tronde

**Comment by MorrisJobke** [comment]
The configuration works and we look into problems if there are some. So it is supported.

**Comment by Tronde** [comment]
In that case, the note in the nginx example configuration could be removed, couldn'i it?

**Comment by MorrisJobke** [comment]
> In that case, the note in the nginx example configuration could be removed, couldn'i it?

Correct. Could you send a PR?

**Comment by Tronde** [comment]
Yes, I'm going to do that in the morning.

**Comment by Tronde** [comment]
PR #422 is ready to be reviewed. If it's going to be merged the PRs #423, #424 and #425 could be merged, too.
