### ISSUE TITLE
updater command line options section wrong

### ISSUE THREAD

**Issue by tessus** [nextcloud/documentation#427]
https://docs.nextcloud.com/server/11/admin_manual/maintenance/update.html#updater-cli-label

There is no `updater/application.php`. The only 2 files in the `updater` directory are: `index.php` and `updater.phar`.

nc 11.0.2

**Comment by MorrisJobke** [comment]
Right - this is old configuration. 🙈

**Comment by tessus** [comment]
can I run the updater from the command line to update my nc from 11.0.2 to 11.0.3?

if yes, how? or is it always better to just do the entire [manual update](https://docs.nextcloud.com/server/11/admin_manual/maintenance/manual_upgrade.html)?

**Comment by MorrisJobke** [comment]
yes:

place the phar in the folder `updater/` and run it as web server user: `php updater.phar` and see the same steps as in the web.

**Comment by tessus** [comment]
Great, thanks. It seems there are no more concerns with the updater. I remember that at one point a few developers suggested to rather use the manual upgrade process instead.

**Comment by MorrisJobke** [comment]
> Great, thanks. It seems there are no more concerns with the updater. I remember that at one point a few developers suggested to rather use the manual upgrade process instead.

No - we spend some time to properly replace it with a more solid version. And we have a lot of users that reported that everything went super smooth.

**Comment by tflidd** [comment]
Looks for me like this has been solved with https://github.com/nextcloud/documentation/pull/460

**Comment by MorrisJobke** [comment]
> Looks for me like this has been solved with #460


Correct :+1:
