### ISSUE TITLE
Update Permissions script assumes some permissions

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/documentation#429]
https://docs.nextcloud.com/server/11/admin_manual/maintenance/update.html#setting-permissions-for-updating
In the script provided, it's assumed that all permissions are already set correctly, but only that the owner needs to be changed to the web user to allow the updater to overwrite files. However, in some cases this is not true.

A case in point would be when Nextcloud is installed and configured, and you've already run the strong permissions script. Then later on, the admin decides to install some new app, running as root (oops), so now the owner of these files is root, and some permissions are 444 (not even write permissions for the owner 😢 ). Everything seems to work fine at this point. But now the admin wants to upgrade to the latest version, so he/she runs through the updater permission script (no problem), setting the owner recursively, and then they run into permission problems.

I suggest we simply add the same chmod commands that are in the set strong permissions script to this updater script, so that people can avoid this pain.

**Comment by MorrisJobke** [comment]
See #431 - we removed that script
