### ISSUE TITLE
Reccomended way of upgrading.

### ISSUE THREAD

**Issue by notaduck** [nextcloud/documentation#44]
I am not completly sure if this is an issue or not but I think it seems strange regarding with what the nextcloud team said earlier on IRC.  
But if you look in the [docs](https://docs.nextcloud.org/server/9/admin_manual/maintenance/upgrade.html) then the reccomended way to upgrade Nextcloud is Using your Linux package manager with our official Nextcloud repositories. This is the recommended method.  
and i am pretty sure you guys said there wouldn't be any **official** repos for nextcloud in the nearest feature?.

**Comment by MorrisJobke** [comment]
cc @LukasReschke @jospoortvliet

**Comment by mar1u5** [comment]
The official and recommended way to upgrade should be to do this manual by replacing the server files (without config and data) :grin:

**Comment by notaduck** [comment]
Guys what info/specs do you need?

**Comment by mar1u5** [comment]
Good question 😁 @nickvergessen

**Comment by nickvergessen** [comment]
We need infos from nextcloud, about packages and that stuff, other than that, I'd say manual file update it is.

**Comment by mar1u5** [comment]
> I'd say manual file update it is

👍

**Comment by jospoortvliet** [comment]
So I've submitted PR's to fix this for 10 and 11.
