### ISSUE TITLE
Gap between Social Buttons unequally

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#442]
Gap between RSS and newsletter...

<img width="479" alt="bildschirmfoto 2017-05-08 um 20 02 25" src="https://cloud.githubusercontent.com/assets/19711361/25817992/699baba4-3429-11e7-8bc9-c192fdb1883b.png">

@MorrisJobke

**Comment by MorrisJobke** [comment]
Was added here: https://github.com/nextcloud/documentation/commit/c5c73b892f031c14971d132ee17d0d5d7646651b

Let me fix that :)

**Comment by MorrisJobke** [comment]
Fix is in #443
