### ISSUE TITLE
Add to docs: App deployment automation via Github Actions

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/documentation#4545]
Hey i just created a new Github Workflow Action which automates the deployment process of a new app version via Nextcloud's appstore. I was wondering if you would like to add something like that to the NC docs at https://docs.nextcloud.com/server/stable/developer_manual/app/index.html?

You can find the Github Action [here](https://github.com/marketplace/actions/nextcloud-push-app-to-appstore) which i'm also using in my [`workflow_ocr`](https://github.com/R0Wi/workflow_ocr) app for publishing new app releases.

Let me know if i can provide further information or if i could create a documentation site for this if you're interested.

**Comment by MorrisJobke** [comment]
cc @rullzer @ChristophWurst @skjnldsv @kesselb @nickvergessen

**Comment by skjnldsv** [comment]
oh my god :heart:

**Comment by jancborchardt** [comment]
Very cool @R0Wi! :) We have a Nextcloud Talk instance where contributors hang out for easier collaboration, we can invite you via your email address if you like?

**Comment by R0Wi** [comment]
@jancborchardt sounds great 👍

**Comment by skjnldsv** [comment]
@R0Wi you're not signing your app? :)

**Comment by R0Wi** [comment]
> @R0Wi you're not signing your app? :)

Sorry but i don't understand what you mean by *signing*? And which app do you mean? Currently i'm maintaining 2 NC apps ;-)

**Comment by skjnldsv** [comment]
Every app at Nextcloud is signed with occ app:sign :)

**Comment by R0Wi** [comment]
> Every app we maintain at Nextcloud is signed with `occ app:sign` :)

Just read something in the [docs](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/code_signing.html). Didn't know that such a mechanism exists but i'm sure i can exend the Github Action and my two apps to support code signing. Thanks for the hint :-)

**Comment by MorrisJobke** [comment]
@R0Wi Mind to just propose the changes as PR against this repo here? Then we can work on the wording together :)

**Comment by R0Wi** [comment]
@MorrisJobke sounds good. I'd add the code-signing functionallity mentioned by @skjnldsv and changing the README.md of the Github Actions repo accordingly. I think then we could create a documentation based on the REAME together?

**Comment by MorrisJobke** [comment]
> I think then we could create a documentation based on the REAME together?

Makes sense 👍

**Comment by R0Wi** [comment]
Hey @MorrisJobke sorry for the late response but i did some work on the mentioned Github Action and i think it can now also be used in combination with code signing. I also added some information to the [README](https://github.com/R0Wi/nextcloud-appstore-push-action/blob/master/README.md). What do you think makes sense to add to this repo here?

**Comment by skjnldsv** [comment]
> What do you think makes sense to add to this repo here?

I think a small summary and links to the action would be nice.
I guess it would be easier to maintain a readme on your repo rather to have to update the docs here each time :)

**Comment by R0Wi** [comment]
> PS: I added you as a guest on our instance, you should be added to the community chat in a few seconds :)

I have been added to the instance but currently i think i cannot see any "community chat", yet? Or maybe it's too late and i'm doing anything wrong :facepalm:

**Comment by skjnldsv** [comment]
> I have been added to the instance but currently i think i cannot see any "community chat", yet? Or maybe it's too late and i'm doing anything wrong

You should be able to if you open the talk app on the instance :)

**Comment by R0Wi** [comment]
> > I have been added to the instance but currently i think i cannot see any "community chat", yet? Or maybe it's too late and i'm doing anything wrong
> 
> You should be able to if you open the talk app on the instance :)

Worked, thanks 👍

**Comment by SMillerDev** [comment]
This is now being used for news. @Grotax maybe you can help with documentation here?

**Comment by MorrisJobke** [comment]
> I think a small summary and links to the action would be nice.

@R0Wi Do you mind to send something for this in?

**Comment by MorrisJobke** [comment]
Or @Grotax xD

**Comment by Grotax** [comment]
@MorrisJobke PR will come this afternoon, already planed to do this but was observing how it works for nextcloud/news.

**Comment by R0Wi** [comment]
Thanks @Grotax let me know if you need any assistance or if something is not clear, yet.
