### ISSUE TITLE
Document Apps Management

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#470]
- Install Apps
- Uninstall Apps
- Update Apps
- App Bundles

**Comment by MorrisJobke** [comment]
:rocket:

**Comment by MorrisJobke** [comment]
@MariusBluem Mind to write it for 14 finally? ;)

**Comment by MariusBluem** [comment]
Yes.

**Comment by MorrisJobke** [comment]
https://docs.nextcloud.com/server/13/admin_manual/installation/apps_management_installation.html
