### ISSUE TITLE
Proper configuration for SELinux

### ISSUE THREAD

**Issue by julenl** [nextcloud/documentation#473]
I set up a Nextcloud server on CentOS7, and I followed the [SELinux documentation](https://docs.nextcloud.com/server/11/admin_manual/installation/selinux_configuration.html), but at the end the system still does not work with SELinux "Enforced".

The steps I followed for the whole installation are collected in this script:
https://github.com/julenl/installets/blob/master/CentOS/nextcloud.sh

Could someone update the SELinux configuration documentation?

**Comment by MorrisJobke** [comment]
Could you check if those two changes work for you:

https://github.com/owncloud/documentation/commit/885ff32bfa18c43913eee8c642ad745015d27c4a
https://github.com/owncloud/documentation/commit/01ae477d20506c470ab1843761ea1fba791f3792

**Comment by julenl** [comment]
Thank you!
Everything works now both nicely and securely :)

**Comment by MorrisJobke** [comment]
Let me port this to our docs then

**Comment by MorrisJobke** [comment]
c65ae409 and d6777a31

**Comment by MorrisJobke** [comment]
stable11 ab77949e and 2d3d8fe5
