### ISSUE TITLE
Wrong value is set for output_buffering in .user.ini and .htaccess

### ISSUE THREAD

**Issue by ghost** [nextcloud/documentation#478]
Please adjust 

> output_buffering=0`

to

> output_buffering='Off'`

in /nextcloud/.user.ini and as well in the .htaccess

> php_value output_buffering 'Off'

Please be aware, case sensitive: '**O**ff'.

Cheers, Carsten

**Comment by MorrisJobke** [comment]
@riegercloud Do you have any reason for this? Because the PHP doc says "integer or boolean"

**Comment by riegercloud** [comment]
If set to zero "my" phpinfo() tells me, value is not set.
If set to 'Off' it is set to 'Off' inphpinfo as well.

**Comment by riegercloud** [comment]
I have to correct myself a bit:
Without having made changes it will display 0 instead of "not set":
![0](https://cloud.githubusercontent.com/assets/20593693/26294070/7576993c-3ec1-11e7-9f8a-41ee3ed3fca5.PNG)
Having made the adjustment:
![off](https://cloud.githubusercontent.com/assets/20593693/26294075/80499c10-3ec1-11e7-8a21-fbd2f90c18d1.PNG)

**Comment by riegercloud** [comment]
written in php.ini's itself:

> Default` value: 'Off'
> Off = Disabled

**Comment by MorrisJobke** [comment]
But the value itself has the same meaning, right? 0 and Off means for PHP the same.

**Comment by riegercloud** [comment]
Yes.
But i would recommend to set the value to 'Off'.
This would avoid any conflicts regarding other applications on the same server.

**Comment by joshtrichards** [comment]
As far as I'm concerned this can be closed.

Besides the equivalence, '0' is the out-of-the box value from PHP and officially documented default: https://www.php.net/manual/en/outcontrol.configuration.php

We handle it just fine and we just go out of our way to make sure it's set to the default. Seems fine.
