### ISSUE TITLE
[nginx] $uri variable may lead to HTTP-Splitting vulnerability

### ISSUE THREAD

**Issue by dimejo** [nextcloud/documentation#485]
Feeding the suggested configuration for nginx into [Gixy](https://github.com/yandex/gixy) shows a possible HTTP-Splitting vulnerability.
```
>> Problem: [http_splitting] Possible HTTP-Splitting vulnerability.
Description: Using variables that can contain "\n" may lead to http injection.
Additional info: https://github.com/yandex/gixy/blob/master/docs/en/plugins/httpsplitting.md
Reason: At least variable "$uri" can contain "\n"
Pseudo config:

include /etc/nginx/sites-enabled/nextcloud.example.com;

server {
	server_name nextcloud.example.com;

	location / {
		rewrite ^ /index.php$uri;
	}
}
```
I've replaced `$uri` with `$request_uri` in the mentioned section and at a first glance it doesn't make a difference.

**Comment by MorrisJobke** [comment]
cc @LukasReschke @josh4trunks

**Comment by josh4trunks** [comment]
This seems to be a duplicate of https://github.com/nextcloud/server/issues/5117
I suggest we follow up there, and close this issue, since it was submitted slightly earlier.

**Comment by dimejo** [comment]
> This seems to be a duplicate of nextcloud/server#5117
I suggest we follow up there, and close this issue, since it was submitted slightly earlier.

Sorry, didn't search for it in [nextcloud/server](https://github.com/nextcloud/server/).

**Comment by josh4trunks** [comment]
no worries, thanks for reporting. I responded on the other issue already
