### ISSUE TITLE
Mac client does not connect to server

### ISSUE THREAD

**Issue by Dirk23** [nextcloud/documentation#494]
I have a Nextcloudserver (v12) behind a apache2 proxy wich terminates SSL (Lets Encrypt. My iOS Clients work fine but the Mac Client won't connect to server: 
![bildschirmfoto 2017-06-07 um 07 35 15](https://user-images.githubusercontent.com/4200682/26863675-63abc32c-4b54-11e7-9e44-e5d728ff4ce7.png)

The error message says that the connection to the https://cloud.---.de/status.php was interrupted and could not be established. 

I can successfully connect to that status.php via a Browser!

What is wrong here?

Regards

Dirk

**Comment by MariusBluem** [comment]
This repository is only for the documentation and not the server. Please report your issue over here: https://github.com/nextcloud/server 😉

**Comment by Dirk23** [comment]
This is not a Server issue!

**Comment by MariusBluem** [comment]
It might also be an reported in the repo of the client you are using.

Why should it be a *Documentation* issue? Have you configured this instance with docs.nextcloud.com and want to report a specific problem with the docs? If no - use one of the other repositories.

Is this maybe related to this issue: 
https://github.com/nextcloud/client_theming/issues/152

**Comment by Dirk23** [comment]
@MariusBluem so can you please tell me where on github i can find the client Repo? I'm asking because the link on this [page](https://docs.nextcloud.com/server/10/developer_manual/bugtracker/index.html ) leads to an [Page not found](https://github.com/nextcloud/client/issues) on Github

**Comment by MariusBluem** [comment]
Client itself: https://github.com/owncloud/client
Nextcloud branding: https://github.com/nextcloud/client_theming

I'll fix the wrong link later today. Thank you for reporting ;)

**Comment by MorrisJobke** [comment]
This looks most likely like a setup issue, than a bug. Please ask in the forums for help first.

https://help.nextcloud.com

**Comment by Dirk23** [comment]
@MorrisJobke no it is not a setup issue! Owncloud Client and Nexcloud iOS Client work fine, only Nexcloud Client for Mac does not. I found a Thread where others have the same problem. It seems to be a problem to have modern SSL Ciphers, Nextcloud Client for Mac doesnt like TLSv1.2 and only works with TLSv1.0!!

**Comment by MariusBluem** [comment]
Again: Please follow https://github.com/nextcloud/client_theming/issues/152 😉
