### ISSUE TITLE
Cosmetic: space between heading and toc link

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/documentation#502]
On all headings it feels like the toc link indicator that pops up on hover: 

![image](https://user-images.githubusercontent.com/3178412/27189197-8ae570ba-51e8-11e7-862e-77ceb16031ab.png)

1. Is too close to the title (needs a space)
2. Doesn't need the underline

I gave up looking for the relevant toc code as it's not super obvious, but if I'm pointed to it I'll knock up a PR (or 2) for both changes if agreed 👍

**Comment by MorrisJobke** [comment]
> I gave up looking for the relevant toc code as it's not super obvious, but if I'm pointed to it I'll knock up a PR (or 2) for both changes if agreed 👍

Just do it in CSS with some margin-right and text-decoration ;)

**Comment by jasonbayton** [comment]
I mean I could.. bit hacky though :p

**Comment by MorrisJobke** [comment]
> I mean I could.. bit hacky though :p

That stuff is not in here, but in sphinx. So this is the only way we can update this or you patch upstream and then wait for the next version.

**Comment by jasonbayton** [comment]
Hacky it is then :D

**Comment by jasonbayton** [comment]
https://github.com/nextcloud/documentation/pull/503

Thanks! :)
