### ISSUE TITLE
Documentation for installation with docker

### ISSUE THREAD

**Issue by pomu0326** [nextcloud/documentation#505]
## Expect
I want something like "installing from docker" as a subsection of the Installation section of "Administration Manual".The content can be at the README level of https://github.com/nextcloud/docker.

## Actual
There is no pass which can follow the explanation of installation using Docker from "Administration Manual".

## Because
I would like to use nextcloud immediately, but the explanation of "Installation on Linux" is too difficult. After that, I started it with docker, so I made it immediately, so I thought it was wonderful if it was described in the Administartion Manual.

**Comment by MorrisJobke** [comment]
@tilosp @pierreozoux Mind to do it?

**Comment by pierreozoux** [comment]
We try to keep the [nextcloud/docker](https://github.com/nextcloud/docker) the best place for Docker installation instruction.
Can we just add a link? It would ease a lot for us :) And it will be in sync also then.

**Comment by MorrisJobke** [comment]
@pierreozoux Sure - just add a little intro text and then the link with further details.

**Comment by MariusBluem** [comment]
I don’t like linking from docs to GitHub, since this is a development platform. What about linking to the dockerhub, which has the same information: https://hub.docker.com/_/nextcloud/
