### ISSUE TITLE
How to import an ical calendar file into NextCloud

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/documentation#508]
I have not found any documentation on how to import an ical calendar file into NextCloud. As far as I can tell, the user doc is completely silent on how to use it. So:

This writeup reflects 11.0.3 (stable).

If you want to import a calendar repeatedly, you should create a new, separate calendar. That way you can delete it and import it again. That is the easiest way to avoid buildup of duplicate entries. Similarly, if you want to delete a calendar later on (say, a calendar for an event).

You may first have to install the calendar app. That is beyond the scope of this write-up.

To create a calendar:

    You may find it convenient to have an extension of ".ics" on the file you wish to import.

    Navigate to the calendar app. In the upper left hand corner of your NextCloud web page, click on "Files". Click on "Calendar" in the pop-up menu.

    You may wish to delete an existing calendar and replace it. In the list of calendars on the left panel of the window, click on the ellipsis (three horizontal dots) for the calendar you wish to delete. Click on "Delete". Wait on the obnoxious countdown, then click again on the cute garbage can.

    To import a calendar. In the lower left, click on "Settings & import". Click on "Import calendar". Navigate to the file you wish to import. Select it and hit the appropriate button on your file selector. Select "New calendar" in the pulldown menu. Click on the check mark. You should see the phrase "import scheduled", then a progress bar. You should then see the freshly imported calendar on the left side. To make the entries visible, click the color dot to the left twice (but don't double click).

**Comment by MorrisJobke** [comment]
@mariusbluehm

**Comment by MorrisJobke** [comment]
@MariusBluem

**Comment by MariusBluem** [comment]
Will be part of coming calendar docs.

**Comment by charlescurley** [comment]
On Wed, 21 Jun 2017 23:43:13 -0700
Marius Blüm <notifications@github.com> wrote:

> Will be part of coming calendar docs.

Thanks.

Here's an alternative:

--------------------------------------------------

You can also subscribe to a calendar. Unlike an imported calendar, a
subscribed calendar will update as the subscribed calendar changes on
the server.

In the left panel of the Calendar app, click on "+ New
Subscription". This will bring up a dialog, with the cursor set to a
box for a link to an ical calendar. Enter a valid URL. Click on
"Create".

--------------------------------------------------

Note: I don't know how quickly NextCloud updates from the subscribed
calendar when it changes on the server. Any ideas?

-- 

The right of the people to be secure in their persons, houses, papers,
and effects, against unreasonable searches and seizures, shall not be
violated, and no Warrants shall issue, but upon probable cause,
supported by Oath or affirmation, and particularly describing the
place to be searched, and the persons or things to be seized.
-- U.S. Const. Amendment IV

Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB

**Comment by tflidd** [comment]
It's documented for *.ics files now: https://docs.nextcloud.com/server/stable/user_manual/en/groupware/calendar.html?highlight=import#import-a-calendar

Please open up again, if there is a function that isn't documented.
