### ISSUE TITLE
Add PHPdoc class documentation to docs.nextcloud.com

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/documentation#509]
It is still linking to the other project, i guess we should have an up to date version of the phpdoc class documentation for Nextcloud.

See: Nextcloud App API
https://docs.nextcloud.com/server/12/developer_manual/app/index.html#phpdoc-class-documentation

**Comment by juliushaertl** [comment]
maybe @MorrisJobke ?

**Comment by MorrisJobke** [comment]
Mmmmh ... any good PHPDoc documentation generator? Because I really don't like the default one, because it's not very easy to read :/

But then I'm open do add a cron job that updates this.

**Comment by juliushaertl** [comment]
https://github.com/ApiGen/ApiGen looks promising, but I was not running out of the box with the Nextcloud code base when I gave it a short try.

I'll check if i find anything else.

**Comment by juliushaertl** [comment]
@BernhardPosselt mentioned https://github.com/varspool/sphpdox which would allow us to include to API documentation to the sphinx built developer documentation. Sadly it is not maintained, as it seems in the repo. Documentation builds fine except for one error with the following line: https://github.com/nextcloud/server/blob/5f25dd7095fadccb7458dbe09c048fbf6645552d/lib/public/IPreview.php#L49

Other options i still need to check out:
- http://phpdox.de/
- https://github.com/FriendsOfPHP/Sami

Maybe we can also use PHPdoc (https://www.phpdoc.org) as before and look for a different template that makes it a bit nicer to read.

**Comment by juliushaertl** [comment]
Implemented with #578
