### ISSUE TITLE
Database performance considerations uses deprecated MYSQL variables

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/documentation#518]
Hello,

the developer manual contains deprecated MYSQL query variables at https://docs.nextcloud.com/server/12/developer_manual/general/performance.html.

`log_slow_queries` was replaced by `slow_query_log` in MYSQL 5.6.1:

https://dev.mysql.com/doc/refman/5.6/en/server-options.html#option_mysqld_log-slow-queries

**Comment by MorrisJobke** [comment]
cc @MariusBluem @xh3n1 @jonatoni maybe ;)
