### ISSUE TITLE
App development tutorial links incompatible owncloud app

### ISSUE THREAD

**Issue by Bubu** [nextcloud/documentation#521]
https://github.com/nextcloud/documentation/blob/master/developer_manual/app/tutorial.rst links to https://github.com/owncloud/app-tutorial#tutorial as the finished tutorial app. This app doesn't work in NC12 and generally seems different from the appstore skeleton referenced elsewhere on the page.

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/documentation/pull/557
