### ISSUE TITLE
how to hide username in user menu. 

### ISSUE THREAD

**Issue by smgodtest** [nextcloud/documentation#5240]
Wonder how to hide the username. So it only shows the display name?
how to remove the top username code?

![image](https://user-images.githubusercontent.com/65642042/95705280-9f6b8080-0c7d-11eb-9dab-e456fe505199.png)

**Comment by MorrisJobke** [comment]
There is no way to remove this.

**Comment by krakazyabra** [comment]
@kesselb Why not? It can be done through CSS
For class `.displayName.subtitle` add rule `display: none;`. This will hide all names under user's ID.
