### ISSUE TITLE
App Dev pages use different structure than tutorial or the skeleton apps.

### ISSUE THREAD

**Issue by curtisolson** [nextcloud/documentation#528]
https://github.com/nextcloud/documentation/blob/master/developer_manual/app/init.rst

Beginning app development, so I just went through the tutorial. Now reading the app dev pages and the first page describes /appinfo/app.php, which isn't in the tutorial code, or the skeleton code that was generated as preparation for the help pages.

I don't have a suggestion for which is correct since I'm just learning, but it wold be helpful is they were all structured the same way. The tutorial is still Owncloud and last updated over 2 years ago, so I'm guessing that version is out of date and shouldn't be used.

**Comment by joshtrichards** [comment]
Fixed in #567 (and elsewhere)
