### ISSUE TITLE
Update NC requirements regarding Postgres databases

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/documentation#5321]
As stated in this thread https://help.nextcloud.com/t/postgres-13-support/93184, Postgres 13 seems to work fine with both NC 19 and NC 20.

I propose to update the following doc page for the two versions to reflect this: https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html

**Comment by MorrisJobke** [comment]
> I propose to update the following doc page for the two versions to reflect this: https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html

Mind to do the changes and hand it in as Github Pull Request? :)

**Comment by Chartman123** [comment]
Shouldn't this be validated first? I mean it's just based on observation... I don't know if there might be some problems/incompatibilities that occur only in special constellations/usage scenarios.

**Comment by MorrisJobke** [comment]
> Shouldn't this be validated first? I mean it's just based on observation... I don't know if there might be some problems/incompatibilities that occur only in special constellations/usage scenarios.

Yep - also noticed that we lack the CI job for 12. Mind to report this in https://github.com/nextcloud/server (Continuous Integration for Postgres 12 and 13)?

**Comment by Chartman123** [comment]
As Postgres 12/13 have been added to CI for NC 21, should I create a PR for the master branch of the docs?
