### ISSUE TITLE
Proper documentation needed for pretty URLs

### ISSUE THREAD

**Issue by oparoz** [nextcloud/documentation#54]
## Missing doc

This is the only paragraph found in [the documentation](https://docs.nextcloud.org/server/9/admin_manual/installation/source_installation.html#pretty-urls):

> Pretty URLs are created automatically when .htaccess is writable by the HTTP user, mod_env and mod_rewrite are installed, and 'overwrite.cli.url' in your config.php is set to any non-null value.

This means that if your setup wasn't a 100% as expected by Nextcloud before creating the admin account, you will have missed your chance to setup pretty URLs, because there isn't any documentation available on how to set it up manually.
## Config sample is unclear

From the [config sample](https://github.com/nextcloud/server/blob/master/config/config.sample.php#L376-L399)

> - Note that above rule is not valid in every case, there are some rare setup
>   - cases where this may not apply. However, to avoid any update problems this
>   - configuration value is explicitly opt-in.

This means that unlike all other parameters, this needs to be added to config.php. 
I think this should be the first line in that large comment and the setting should be commented out since it's not working when found in the sample.

---

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by MorrisJobke** [comment]
> The most obvious one being that the theme you've created with the built-in editor will be wiped.

Really? Why?

**Comment by MorrisJobke** [comment]
> There is no mention anywhere about the side effects of switching.

There are none AFAIK. Only when switching back some URLs won't work.

**Comment by oparoz** [comment]
>>There is no mention anywhere about the side effects of switching.

>There are none AFAIK. Only when switching back some URLs won't work.

I've removed that section. It's not a side-effect, just that theming is currently not a 100% compatible with pretty URLs

**Comment by MorrisJobke** [comment]
> I've removed that section. It's not a side-effect, just that theming is currently not a 100% compatible with pretty URLs

Could you open an issue for this in the server repo? This is definitely a bug and should be addressed instead of documented ;)

**Comment by oparoz** [comment]
It's [there](https://github.com/nextcloud/server/issues/315) already and I just have to create the PR to fix the problem.

**Comment by MorrisJobke** [comment]
> It's there already and I just have to create the PR to fix the problem.

Awesome. I also just found it :) 👍

**Comment by tflidd** [comment]
A user just found out how to implement this on nginx:
https://help.nextcloud.com/t/pretty-urls-for-nextcloud-11-with-nginx-and-php5/11921

**Comment by MorrisJobke** [comment]
@tflidd but the existing nginx config already explains and contains this. :confused:

**Comment by MorrisJobke** [comment]
Fixed in #556

**Comment by Nottt** [comment]
I still find the documentation is lacking :/ 

Having a lot of difficulty to set up pretty URL with nginx, with nextcloud docker v14, even if I copy and paste and only change some stuff this fails:

https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html

**Comment by ostasevych** [comment]
Have a question: how to make desktop client to share internal links without index.php, so prettified?.. The webui does it.
