### ISSUE TITLE
update link in user manual

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/documentation#5418]
Please use a link to the latest desktop client

https://github.com/nextcloud/documentation/edit/master/user_manual/index.rst
line 25:
.. _`Nextcloud Desktop Client`: https://docs.nextcloud.com/desktop/2.3/

**Comment by cloud2018** [comment]
@MorrisJobke 
perhaps  https://docs.nextcloud.com/desktop/latest and link to the newest version instead the hard coded version number is easier for maintenance

**Comment by cloud2018** [comment]
@MorrisJobke
Links is not to the latest desktop client (https://docs.nextcloud.com/desktop/3.3/index.html)
Link is to verison 3.0:
.. _`Nextcloud Desktop Client`: https://docs.nextcloud.com/desktop/3.0/

**Comment by MorrisJobke** [comment]
I'm not with the project anymore. Please reach out to @nextcloud/desktop

**Comment by mgallien** [comment]
> @MorrisJobke Links is not to the latest desktop client (https://docs.nextcloud.com/desktop/3.3/index.html) Link is to version 3.0: .. _`Nextcloud Desktop Client`: https://docs.nextcloud.com/desktop/3.0/

I will take care of it
