### ISSUE TITLE
Development Environment instructions are inaccurate

### ISSUE THREAD

**Issue by Instagit** [nextcloud/documentation#542]
https://docs.nextcloud.com/server/12/developer_manual/general/devenv.html

    sudo chown -R www-data:www-data /var/www/core/data/

should be

    sudo chown -R www-data:www-data /var/www/<folder>/core/data/

I think and following the instructions, that directory doesn't exist.

**Comment by MariusBluem** [comment]
THX. Mind opening a Pull Request against this repository? 🙈

**Comment by Instagit** [comment]
Yes, but should I remove the line completely or fix it? Is the _core/data_ directory still required? Like I said, following the instructions I don't even have that directory. I'm not familiar with the Nextcloud internals.

**Comment by juliushaertl** [comment]
That might come from the times before the fork, where the root git repo was named core. it shoudl be /var/www/server/data/ i guess.

**Comment by juliushaertl** [comment]
Seems fixed https://docs.nextcloud.com/server/16/developer_manual/general/devenv.html
