### ISSUE TITLE
Nginx caching delays for dynamic elements

### ISSUE THREAD

**Issue by anoymouserver** [nextcloud/documentation#5472]
https://github.com/nextcloud/documentation/blob/122ed88e536d45afa6b671c8f90a8d43f9510b21/admin_manual/installation/nginx.rst#L103-L104

This seems to cause update delays for dynamic elements requested via APIs.

For example when using the news plugin, it causes feed items which I've marked as read still being displayed in the list for 60 seconds (`/apps/news/items?limit=40&oldestFirst=false&search=&showAll=false&type=6`)

The live update in the Administration > Logging section has the same problem `/apps/logreader/poll?lastReqId=UwWXOsccR9Rw6DoVbATf` is only executed every 1 minute, every other call is loaded from the cache.

@jivanpal, @josh4trunks any idea how to fix this other than removing the default caching policy?

_Originally posted in https://github.com/nextcloud/documentation/pull/2197#discussion_r530570586_

**Comment by josh4trunks** [comment]
Could you  confirm if there is also a 1 minute delay using a vanilla apache setup?
If other parts of the UI are working responsively with the defualt `expires` set then I think it is better fixed on the application side.

Maybe the working parts of Nextcloud are setting the cache-control header, while the broken ones are accepting the 1m default? I haven't worked with cache's in a while, but there's also likely other ways to bust NGINX's cache.

**Comment by anoymouserver** [comment]
I asked in the maintainer chat if someone could test it with apache and the default htaccess, because I don't necessarily want to set up an extra apache for it.

However, I just looked at the root htaccess in the server package and can't see a configured default cache of 1 minute there.
