### ISSUE TITLE
Description of the contacts icon

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/documentation#5518]
- Description of the contacts icon:
` In the bottom left of the Contacts View (in Nextcloud contatcs) look for a little impeller symbol that looks like this:`
in the file: `user_manual/pim/sync_windows10.rst` is incorrect.

There should be a gear icon when it comes to the settings icon. Then describe finding the icon to copy the link.

- Also need to change the preview image.

https://raw.githubusercontent.com/nextcloud/documentation/master/user_manual/images/contacts_link.png

**Comment by joshtrichards** [comment]
Fixed in #8929
