### ISSUE TITLE
Old pictures for Contacts app - Update of images needed

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/documentation#5521]
* The icon picture for uploading https://raw.githubusercontent.com/nextcloud/documentation/master/user_manual/images/contact_picture.png in the `user_manual/pim/contacts.rst` a picture for contacts should be as follows:
![obraz](https://user-images.githubusercontent.com/47037905/101261101-ee410e00-3734-11eb-8fb6-99e4874db21c.png)

* This image is also out of date: https://raw.githubusercontent.com/nextcloud/documentation/master/user_manual/images/contact_manageaddressbook.png

It now looks like this:
![obraz](https://user-images.githubusercontent.com/47037905/101261298-7aa00080-3736-11eb-9100-520bc2ac780d.png)

**Comment by rakekniven** [comment]
Did not get it. Could you improve the issue please.

**Comment by Valdnet** [comment]
@rakekniven I mean need to refresh the pictures in the user guide for the Contacts app because they are too old for their present appearance. See examples:

Old:
https://raw.githubusercontent.com/nextcloud/documentation/master/user_manual/images/contact_picture.png
New:
![obraz](https://user-images.githubusercontent.com/47037905/114012275-6dbb2700-9866-11eb-9a4c-bb2630bbd8f2.png)

Old:
https://raw.githubusercontent.com/nextcloud/documentation/master/user_manual/images/contact_manageaddressbook.png
New:
![obraz](https://user-images.githubusercontent.com/47037905/114012400-917e6d00-9866-11eb-84dd-f62956843998.png)

There are other pictures for Contacts to be corrected 😉.

**Comment by joshtrichards** [comment]
Fixed in #9304

Confusingly the linked "out of date" images above point at the live images so they are the current ones now.
