### ISSUE TITLE
Add documentation on how to change data folder

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#555]
Since https://github.com/nextcloud/server/issues/137 we allow to change the data folder but the documentation says nothing about it. There are a few guides for Nextcloud (https://help.nextcloud.com/t/changing-data-directory/11156) but nothing official.

Owncloud added a documentation but I don't know if their solution is still close enough that we can copy it:
https://github.com/owncloud/documentation/pull/2781/files

edit: and the forum's own howto: https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170

**Comment by jasonbayton** [comment]
Validated steps here: 

https://help.nextcloud.com/t/is-there-a-safe-and-reliable-way-to-move-data-directory-out-of-web-root/3642?source_topic_id=19612

**Comment by wiswedel** [comment]
fixed by https://github.com/nextcloud/documentation/pull/954
