### ISSUE TITLE
There are no corrected strings to translate in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/documentation#5581]
In Transifex it is still possible to translate `files-gallery_app` despite deleting @MorrisJobke in https://github.com/nextcloud/documentation/commit/03d3430b793b60ec123da27738ea0b824b2e5949.

**Comment by Valdnet** [comment]
I also noticed that Transifex does not update the corrected sentences after merging the PR from the user manual.

**Comment by Valdnet** [comment]
ping @MorrisJobke, @nickvergessen, @skjnldsv Does the Transifex bot scan documentation daily?

> I also noticed that Transifex does not update the corrected sentences after merging the PR from the user manual.

As long as the corrected texts do not appear in Transifex, the manual will not be fully translated. It looks like:

![obraz](https://user-images.githubusercontent.com/47037905/101892902-44cea200-3ba4-11eb-85fd-3be6c34d30de.png)

> In Transifex it is still possible to translate `files-gallery_app`

Please delete `files-gallery_app` as it no longer appears in the user manual and is still in Transifex for translation. Translators are working on it unnecessarily.

**Comment by nickvergessen** [comment]
> In Transifex it is still possible to translate files-gallery_app despite deleting MorrisJobke in 03d3430.

I guess it also translates stable20, 19 and 18 branches?

**Comment by Valdnet** [comment]
> I guess it also translates stable20, 19 and 18 branches?

@nickvergessen Where can you watch it? I can't find it in `user_manual`.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/documentation/commits/stable20/user_manual

**Comment by nickvergessen** [comment]
but also seems like the bot died at some point.

**Comment by Valdnet** [comment]
> https://github.com/nextcloud/documentation/commits/stable20/user_manual

Note that in `user_manual` does not have a gallery related `gallery_app` file.

> but also seems like the bot died at some point.

That's what I noticed too 😉.
