### ISSUE TITLE
Calendar docs is broken and badly formatted

### ISSUE THREAD

**Issue by GiantCrocodile** [nextcloud/documentation#563]
I have no clue what this should tell me but it tells me nothing:

![grafik](https://user-images.githubusercontent.com/6271057/30665333-f76a098a-9e50-11e7-8d5d-5b6b93221406.png)

I see this at https://docs.nextcloud.com/server/12/user_manual/pim/calendar.html and the other links in that section ain't much better: https://docs.nextcloud.com/server/12/user_manual/pim/sync_osx.html has formatting issues.

**Comment by MorrisJobke** [comment]
cc @MariusBluem

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by JonasDralle** [comment]
not only is the doc missing (#127) there's also a "12 replace:: 12" at the end of the doc.
This is a result of switching docs

[![](https://i.imgur.com/xuUCvO9.gif)](https://i.imgur.com/xuUCvO9.gifv)

**Comment by cedewey** [comment]
I'd love to help with this if possible, is there someone on the NextCloud team who can check in with me to help resolve this issue?

**Comment by MariusBluem** [comment]
Closing in favor of #127. The missing docs for calendar will come very soon.
@cedewey I'll mention you when there is a PR ready for reviewing. Thanks!
