### ISSUE TITLE
Remove references to Dropbox-support as external storage or add info about current situation

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/documentation#569]
Support for Nextcloud's Dropbox API V1 was phased out.
As of current, dropbox-integration is dysfunctional and future of API V2 implementation seems to be undecided.
#https://github.com/nextcloud/server/issues/991

**Comment by devjb** [comment]
What is the current plan? Will the dropbox integration become an official feature of nextcloud or not? At the moment, the current solution https://github.com/icewind1991/files_external_dropbox suffers from issues (https://github.com/icewind1991/files_external_dropbox/issues/11, https://github.com/icewind1991/files_external_dropbox/issues/13, and others) that block users from using it and there is hardly any response to issues from the owner or any visible development going on for the last 4 weeks. 

Please make an official statement whether

1. You are interested in providing dropbox connection as a feature or not. It's fine if not, but then please communicate it. 
2. is https://github.com/icewind1991/files_external_dropbox in any way connected with the official nextcloud development team? 

Thanks for clarification

**Comment by MorrisJobke** [comment]
> is https://github.com/icewind1991/files_external_dropbox in any way connected with the official nextcloud development team?

It is done by somebody from the nextcloud team and the current way of how dropbox can be used.

**Comment by MorrisJobke** [comment]
@MariusBluem Mind to update it.

**Comment by MariusBluem** [comment]
Yes. Is this stable enough to get documented? It is not in the App Store and not in the nextcloud-org on GitHub ... @icewind1991

**Comment by umgfoin** [comment]
> It is not in the App Store and not in the nextcloud-org

And support in server's external-storage-GUI is still there (as of 12.0.4).
I mean, atleast a notice in the GUI should be left to lower mankind's overall lifetime-waste on IT-technology.

**Comment by kb-1000** [comment]
icewind1991's app no longer works, and is currently referenced by the docs. Why do you reference a broken app in the docs?

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/documentation/pull/1891
Anyone can edit our documentation and suggest their changes.

**Comment by kb-1000** [comment]
Has this removed the reference in 
![image](https://user-images.githubusercontent.com/18211838/77334842-9e94f080-6d25-11ea-8181-90bff62e8484.png)
for new installations too?

**Comment by skjnldsv** [comment]
Yes
