### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/documentation#5700]
There is an invalid link `See :doc:admin documentation <file_sharing_configuration>` to the administrator documentation in the [sharing](https://github.com/nextcloud/documentation/blob/master/user_manual/files/sharing.rst) file:

It looks like this:
![obraz](https://user-images.githubusercontent.com/47037905/101905182-4c4b7680-3bb7-11eb-98e1-e587f7f1afb5.png)

**Comment by Valdnet** [comment]
The link `See :ref:an example below <supported_variables_label>` is also displayed incorrectly in the [gallery_app](https://github.com/nextcloud/documentation/edit/backport/1931/stable18/user_manual/files/gallery_app.rst) file.

**Comment by MorrisJobke** [comment]
Looks like we need to do full URLs instead of those cross manual ones.

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/user_manual/en/files/sharing.html#file-sharing

Fixed in #7826
