### ISSUE TITLE
Personal info visible for: Local, Contacts, Public. How to use?

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/documentation#5845]
Hello,
I was confused by the user interface in setting my personal information like email adress etc, like this user https://help.nextcloud.com/t/personal-info-visible-for-local-contacts-public-how-to-use/11147 (what do you mean by public address book - public within the instance, or for the whole world?) 
and wanted to check documentation but there is no info about it --- https://docs.nextcloud.com/server/20/user_manual/en/userpreferences.html

can someone put some info there?

**Comment by MorrisJobke** [comment]
cc @schiessle @nickvergessen

**Comment by nickvergessen** [comment]
So the current levels are:
![Bildschirmfoto von 2021-01-15 11-31-59](https://user-images.githubusercontent.com/213943/104714285-536d2380-5725-11eb-8836-e0599d8efe43.png)

And yes, public addressbook is "globally shared between all nextclouds" via a lookup server.

**Comment by alexanderdd** [comment]
Ok, I understand. This bug is about improving the documentation though, so I'll keep it open.

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/user_manual/en/userpreferences.html#sharing-your-data-in-the-global-address-book

Fixed in #10264
