### ISSUE TITLE
Minimum password length should be consistent

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/documentation#5858]
in the manual text and the corresponding screenshot
https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_user/user_password_policy.rst

The current text just says 10 characters, while the app itself says 8 characters.

Also concerns https://github.com/nextcloud/password_policy/blob/master/README.md
and https://github.com/nextcloud/password_policy/blob/19a4714a95830f3b151872925962da9195c3a3cc/lib/PasswordPolicyConfig.php#L56 in the password policy app.

Is there a consensus in the team about which value should be suggested as a placeholder? 

And should the manual then be adjusted just for Nextcloud 21 or for all Nextcloud versions that are currently still maintained?

**Comment by jotoeri** [comment]
Hey @sudwhiwdh,
honestly, i'm not the one to finally decide this. However: @rullzer, who is the one to decide, somewhen decreased the password-length from 10 first to 6 and then to 8 with the comment/title to follow NIST recommendations (https://github.com/nextcloud/password_policy/commit/89635ef2a0aead06fae65a57406965feeceac7bd). As far as i see, [NIST still recommends](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret) up to today a min-length of 8 for user-generated passwords. So as i see, the length of 8 is the current way, the number of 10 is just a historical artifact.

Do you wannt to create a PR? Just create one for the master branch, the backport will then be done more or less automatically from there. 😉 
Greets,
Jonas
