### ISSUE TITLE
Can't upload .apk files to cloud

### ISSUE THREAD

**Issue by OneHappyForever** [nextcloud/documentation#587]
Hello,

I have a bunch of .apk files that I want to upload to the cloud, but everytime I try to upload one, once the upload is finished, the file just disappears, nowhere to be found.

Down nextcloud support .apk files? Is there an app in the marketplace that supports .apk files?

Best regards,

**Comment by MorrisJobke** [comment]
Usually it should work. Maybe look at the logs for any hints what is going wrong.

For further questions, please use the forums at https://help.nextcloud.com.

Thanks
