### ISSUE TITLE
"build-in" should be "built-in"

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#590]
The Admin manual uses the term "**build-in**". 

$ grep -R build-in *
maintenance/update.rst:Upgrade via build-in Updater
maintenance/update.rst:The build-in updater automates many of the steps of upgrading an Nextcloud
maintenance/update.rst:before every update. The build-in updater does not backup your database or data
maintenance/update.rst:The build-in updater performs these operations:
maintenance/update.rst:Using the build-in Updater to update your Nextcloud installation is just a few
maintenance/upgrade.rst:The :doc:`build-in Updater <update>` does this for you before replacing the

This should be "**built-in**". It also looks like there is inconsistent capitalization of "updater".

**Comment by MorrisJobke** [comment]
Fix is in #593
