### ISSUE TITLE
Fix Jessie warning

### ISSUE THREAD

**Issue by Jibec** [nextcloud/documentation#591]
hi

in this page: https://github.com/nextcloud/documentation/tree/master/admin_manualadmin_manual/configuration_files/files_locking_transactional.rst

I think we can remove this warning "Debian Jesse users, please see this Github discussion if you have problems with LDAP authentication." which links to a bug fixed in 8.2.

**Comment by MorrisJobke** [comment]
cc @MariusBluem

**Comment by MorrisJobke** [comment]
Fix is in #595
