### ISSUE TITLE
nginx sample config example format malformed by comments - Nginx Configuration - Nextcloud 12 Server Administration Manual

### ISSUE THREAD

**Issue by Oclair** [nextcloud/documentation#592]
the page:
[Nginx Configuration - Nextcloud 12 Server Administration Manual](https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html)
give instructions regarding nginx configuration.

Problem is, when someone added comments, they malformed the code which is only detectable when using curl or firefox see: 
https://help.nextcloud.com/t/nextcloud-12-wont-load-on-firefox-on-http2/20333/2

There are a few blocks where this entry is broken up by comments, unfortunately it will require changing the format

Correct format before adding comments
`add_header Strict-Transport-Security "max-age=16070400; includeSubdomains";`

Incorrect format adopted by the guide
```
     # add_header Strict-Transport-Security "max-age=15768000;
     # includeSubDomains; preload;";
```

**Comment by MorrisJobke** [comment]
Thanks for the report - fix is in #594
