### ISSUE TITLE
British spelling for "customize"

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#596]
The American spelling for "customize" is usually used in the documentation. The British spelling occurs at the following locations:

    documentation$ grep -Ri customis *
    developer_manual/core/configfile.rst:Nextcloud can be set to use a custom app directory in 
    /config/config.php. Customise the following code and add it to your config file:
    developer_manual/design/html.rst:As default html5 checkboxes & radios are **not** 
    customisable, we created an override using label and ``::after`` elements.

Change these to the American spelling.

**Comment by MorrisJobke** [comment]
@peterdamian Could I ask you to send this in as a pull request? Thanks :)

**Comment by MorrisJobke** [comment]
Fixed by #597
