### ISSUE TITLE
Capitalization of headers

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#600]
Your style guide doesn't specify the capitalization for headers but "title case" is usually used within your documentation. The headers shown in the attached file don't follow this convention. I can change these headers to title case if that's desirable. (I'll script most of the work.)
[titles.zip](https://github.com/nextcloud/documentation/files/1459533/titles.zip)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by peterdamian** [comment]
Revised file. With the previous file I did not merge changes from master. Also, the script now accommodates nonstandard headers.
[revised_titles.zip](https://github.com/nextcloud/documentation/files/1462593/revised_titles.zip)

**Comment by jancborchardt** [comment]
Capitalization of headers for the software itself is always: First word capitalized, others not (except when own name like HTML etc). Like:

- Design guidelines
- Personal settings
- Two-factor authentication
- etc :)

Cc @jospoortvliet about docs casing. I would say we should use that same rule.

**Comment by peterdamian** [comment]
Find attached a list of headers that don't follow the "sentence case" convention (capitalization of the first word only, except for proper nouns etc). If sentence case is preferred you'll likely want to remove some of the items in this list since they may be capitalized within Nextcloud.

It would be good to note in the style guide what convention is used for headers.

@jancborchardt @jospoortvliet 

[nonsentence_case_headers.zip](https://github.com/nextcloud/documentation/files/1464966/nonsentence_case_headers.zip)

**Comment by MorrisJobke** [comment]
@peterdamian Could you do a PR here as well. Maybe wait for opening the PR after the PR for #602 is merged to avoid merge conflicts.

**Comment by peterdamian** [comment]
@MorrisJobke I'll open PRs, timing them as you suggest.
