### ISSUE TITLE
Inconsistent header styles

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#602]
Your style guide documents three headers:

- the equals sign for h1 headers (with both overlining and underlining)
- the minus sign for h2 headers
- the caret for h3 headers

Within the documentation there are many exceptions to this convention. A number of h1 headers are missing the overlining, there are h1 headers used in place of h2 headers, and sometimes an h4 header (~~~)  is used.

Proper use of headers makes it easier to read the raw text and easier to manipulate the text programmatically.

See also #600.

**Comment by MorrisJobke** [comment]
@peterdamian Could you open a PR to fix this? I guess this is a nice improvement 👍
