### ISSUE TITLE
Nextcloud 12 User Manual Introduction links to owncloud desktop client

### ISSUE THREAD

**Issue by johanehnberg** [nextcloud/documentation#604]
In Nextcloud 12's Web UI Help, under Nextcloud 12 User Manual Introduction, there is a link called "Nextcloud/ownCloud Desktop Client" that links to:
https://doc.owncloud.org/desktop/2.2/

This should likely be:
https://nextcloud.com/install/#install-clients

Also see the client's link:
https://github.com/nextcloud/client_theming/issues/165

**Comment by tflidd** [comment]
We have now a proper Nextcloud desktop client documentation, repo: https://github.com/nextcloud/desktop/tree/master/doc
