### ISSUE TITLE
Question about innodb_io_capacity recommendation in admin manual

### ISSUE THREAD

**Issue by Steve8291** [nextcloud/documentation#6046]
In the admin manual:  documentation/admin_manual/installation/server_tuning.rst 
There is the recommendation for your mysqld.cnf file to add:
```
[mysqld]
innodb_buffer_pool_size=1G
innodb_io_capacity=4000
```
I've been trying to understand why that is a good recommendation to have in the manual. Maybe there could be some more documentation around that setting. From what I understand, setting that too high on an SSD will reduce drive life. Also you would have to be sure that the drive you have your database installed on would be able to handle the IOPS. For installations that are on non-ssd drives you would not want to increase that number to 4000 unless they could perform that many writes per second.
This site is what I'm basing some of my info off of: [https://www.percona.com/blog/2020/05/14/tuning-mysql-innodb-flushing-for-a-write-intensive-workload/](url)

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/documentation/commit/d2566e776dddda89aa62ebf1387e2beb061c9562

Let's ask the approver @MorrisJobke 
Or the commiter @Florz

**Comment by MorrisJobke** [comment]
It was coming from https://github.com/nextcloud/server/issues/2837#issuecomment-427768057

The PR to documentation is #891

I guess we can move this to a troubleshooting section so that is still there but only in case you run into problems.

**Comment by MorrisJobke** [comment]
Opinions? cc @ChristophWurst @kesselb

**Comment by acsfer** [comment]
IMHO MySQL tuning is **out of scope** of documentation, as it is related either to the Nextcloud size **and** hardware.
One should rely on default parameters and tune only if needed and fully understand what implications it can have (or hire a DBA).

As an example, in my case `innodb_buffer_pool_size=1G` is very low; i have set it to 24G. Regarding `innodb_io_capacity`: https://www.percona.com/blog/2019/12/18/give-love-to-your-ssds-reduce-innodb_io_capacity_max/

If we want to point in some directions, just link to https://mariadb.com/kb/en/optimization-and-tuning/ should be enough.

**Comment by kesselb** [comment]
Fair enough @acsfer. Mind to send a pull request?
