### ISSUE TITLE
Some js file are missing

### ISSUE THREAD

**Issue by tceydeliler** [nextcloud/documentation#6074]
Hi,
I am newbie about nextcloud. 
I get an error about some js file such as   core/js/oc-backbone-webdav.js 
I search it my server, download and unzip old version, and look for in github, but there no file that named as "oc-backbone-webdav.js" 
where is this file really?

**Comment by MorrisJobke** [comment]
Most likely this https://github.com/nextcloud/server/blob/master/core/src/OC/backbone-webdav.js

But we compile them nowadays into one bigger file. So this might some caching issue.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
