### ISSUE TITLE
Setting up maximally secure server

### ISSUE THREAD

**Issue by Kixunil** [nextcloud/documentation#6077]
After a little bit of playing on a sloppily configured server I want to start using Nextcloud properly. I also want to make it maximally secure.

I have very little experience with PHP or nginx configuration, I've read through docs and other tutorials online and yet I still can't find out everything I want to. I have good knowledge of Linux and various security techniques.

I'd like to do this:

* Have nextcloud under `/nextcloud` to avoid conflicts with other apps
* Put scripts and resources into a read-only location (I will update and install apps using tools external to Nextcloud)
* Only allow executing whitelisted scripts
* Only serve files from whitelisted locations
* If possible have scripts in one directory, resources in another to avoid having to spell out everything in nginx config and worry about it when updating Nextcloud
* Run nextcloud using a separate FPM instance with a dedicated user (I figured out how)
* Let nextcloud store any data it likes into a dedicated directory
* I already use templating for existing nginx configuration 

Some things I have difficulty to figure out:

* Why is there `deny all` in the example? Shouldn't other `location` blocks act as a whitelist?
* Is `$fastcgi_script_name` safe against directory traversal? Is it guaranteed that it'll never contain `..`? If not, can I protect it somehow?
* What's the fuss about `cgi.fix_pathinfo`? Different sources claim different things. Which is better for Nextcloud? (I will probably create a separate `php.ini` for it to avoid surprises)

I'd appreciate answers to these questions and possibly extending the documentation with this information to make it available for others.

**Comment by tflidd** [comment]
>     * Put scripts and resources into a read-only location (I will update and install apps using tools external to Nextcloud)

It might be a solution for your and in the past there were some command to setup permissions properly. However, this is not compatible with the updater app and update process.

With most of your questions, you should ask in the user forum for more help and discussion: help.nextcloud.com

Later, we can implement improvements to the documentation.

**Comment by tflidd** [comment]
The documentation is supposed to work in different setup environments. We probably can't cover all possible use cases here and keep them updated.

As said before, on the [forum](https://help.nextcloud.com/), we can discuss more  individual environments, how you could implement it etc. For more generic parts, there is also the option to put wikis and howtos.

So I am to close this for the moment.
