### ISSUE TITLE
Dependency injection: force object recreation in PSR-11 ContainerInterface

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/documentation#6086]
Hi guys,

a question regarding dependency injection: i just noticed the fact that the `ContainerInterface` implementation will always return the same object when querying via it's `get`-method inside the same request lifecycle. Following the spec at https://www.php-fig.org/psr/psr-11/ this is completely correct and also documented on the [NC docs](https://docs.nextcloud.com/server/latest/developer_manual/basics/dependency_injection.html#how-does-auto-wiring-work). Nevertheless i experienced some issues in my own app (see https://github.com/R0Wi/workflow_ocr/issues/43). There is a processing of PDF files going on via cron-engine. The problem is that inside of one cron iteration the same object tree will be reused which causes issues in my case. I have something like the following dependency tree:

`BackgroundJob` (workflow) -> `PdfProcessor` -> `Command` (wrapper for CLI)

Since these dependencies are only resolved once on the `ContainerInterface->get(...)` call the `Command` object keeps it state through various processing steps of different PDF files (in my case the capture of the std-out is still there on further processing of other files).

**So my question:** is that really the way things should work in that case or is there any possibility to force a object creation without caching objects? Didn't find anything in the docs and neither in the code so far. @ChristophWurst i think you've implemented the usage of the PSR `ContainerInterface`, any help would really be appreciated. Thank you guys!

**Comment by ChristophWurst** [comment]
Hey @R0Wi,

can we move this to https://help.nextcloud.com/c/dev/11?

As far as I understand you're using the container as a factory and don't always expect the same instances? IIRC you can prevent reuse of a constructed service with the third parameter of the service registration, then the service will be re-built every time it's requested. Any class that already owns a built instance won't be updated, of course.

> Thank you guys!

FYI we're luckily not just *guys*.

**Comment by R0Wi** [comment]
Thank you for your quick and useful response, @ChristophWurst. Will try that :-)

> FYI we're luckily not just guys.

Sorry, didn't want to offend anybody. It was just a kind of phrase and it was early in the morning ;-) .

**Comment by ChristophWurst** [comment]
No worries :)
