### ISSUE TITLE
Missing label for cross reference

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#613]
The cross reference ":ref:`db-transaction-label`" is used at a number of locations in the documentation but the matching label is missing. See:

documentation$ grep -R db-binlog-label *
admin_manual/installation/command_line_installation.rst:See :ref:`db-binlog-label`.
admin_manual/installation/source_installation.rst:See :ref:`db-binlog-label`.
admin_manual/installation/system_requirements.rst:* Disabled or BINLOG_FORMAT = MIXED configured Binary Logging (See: :ref:`db-binlog-label`)
admin_manual/maintenance/manual_upgrade.rst:Please refer to :ref:`db-binlog-label` on how to correctly configure your 

Where should the  "db-binlog-label" label appear? Before "Database Requirements for MySQL/ MariaDB"  in  admin_manual/installation/system_requirements.rst? That's the only area of the documentation that addresses binary logging for MySQL.

**Comment by MorrisJobke** [comment]
This section was removed, because it was not valid anymore. @nickvergessen knows more

**Comment by nickvergessen** [comment]
Actually you should: https://github.com/nextcloud/documentation/pull/538
And @MariusBluem
