### ISSUE TITLE
"New" weblogin flow needs documentation

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/documentation#620]
The new login flow should be documented so that third party devs can easily use this without reading android/ios/client/server code.

Ref: https://github.com/nextcloud/android/issues/1145#issuecomment-348210849

**Comment by MorrisJobke** [comment]
cc @LukasReschke @rullzer

**Comment by rullzer** [comment]
Yes I'll write something up. Might need beautification at the end but then somebody else can take over.

**Comment by MariusBluem** [comment]
> beautification

Will take care of this after that ;)

**Comment by rullzer** [comment]
PR in #642
