### ISSUE TITLE
Captions for figures

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#621]
The style guide recommends creating a caption for every figure. This is standard practice--figures should have captions. However, the vast majority of figures in the documentation lack a caption. See the attached file.

Should the style guide be changed or should captions be added? 
[captions.zip](https://github.com/nextcloud/documentation/files/1523487/captions.zip)

**Comment by tflidd** [comment]
@jancborchardt @jospoortvliet can you help? I suppose that people forgot to put the captions most of the time and didn't respect the style guide.

**Comment by jancborchardt** [comment]
@peterdamian could you show a before & after screenshot of an example without and with captions?

We should make sure that captions are actually relevant, because many times it’s visual noise. The caption is very often a part of the text, and duplicating it makes little sense.

**Comment by peterdamian** [comment]
@jancborchardt 
Looking at other style guides and examples of other documentation can be helpful. The Google style manual suggests that all images should be contained within figures (https://developers.google.com/style/images) but that not all figures need captions. In the MySQL documentation images are also contained within figures but figures always have captions. The MySQL Workbench documentation (https://dev.mysql.com/doc/workbench/en/) provides many examples of this.

In HTML5 figures are not associated solely with image files--they can be used to contain paragraphs and code blocks as well. This is not the case in reStructuredText. Figures are only used with images and the only difference between ".. image::" and ".. figure::" is that a figure can have a caption (and a legend). Right now the Nextcloud style guide says that figures must be numbered and the number should appear in the caption. 

I would suggest that the style guide be changed, perhaps saying something like the following:

"If your image file requires a caption use the figure tag but otherwise use the image tag."

With this change the remark about numbering should perhaps also be removed. Because numbering is not automatic, any addition or removal of a figure requires that the numbering of all following figures be adjusted. This is the kind of thing that tends to get overlooked. Not requiring numbering avoids this issue.

**Comment by jancborchardt** [comment]
Fix is at https://github.com/nextcloud/documentation/pull/6393, please review :)
