### ISSUE TITLE
Image files with no alt tag

### ISSUE THREAD

**Issue by peterdamian** [nextcloud/documentation#622]
The documentation style guide says images "must have alt tags". The image files listed in the attached file lack alt tags. alt tags are usually similar or identical to captions so this issue can be addressed at the same time as #621.

[miss_alt.zip](https://github.com/nextcloud/documentation/files/1524250/miss_alt.zip)

**Comment by richardnixonafj** [comment]
I believe the tag is important for the accessibility of screen readers (visually impaired).

someone working on it? I would like to help!

**Comment by jancborchardt** [comment]
Hi @peterdamian @richardnixonafj what was this tested with, so I can check if changes fix the issues? :)

Also @peterdamian I read up on the documentation but nowhere could I find anything about the equivalent of `alt=""` for decorative images, or images of which the value is already conveyed via text. Would this just be achieved by also using an empty alt tag in reStructured Text?
```
.. image:: picture.jpeg
   :alt:
```
Or will this be an error?

**Comment by jancborchardt** [comment]
Fix is at https://github.com/nextcloud/documentation/pull/6393, please review :)
