### ISSUE TITLE
Suggest Installation of php-phar to Use updater.phar

### ISSUE THREAD

**Issue by HouraisanNEET** [nextcloud/documentation#6224]
Ran into nextcloud/updater#329
It is mentioned that update.phar is available to update in CLI, however the documentation doesn't mention that php-phar package is required to use it.
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#using-the-command-line-based-updater
https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation

**Comment by tflidd** [comment]
I think on debian-based systems it was not required, but in FreeBSD I had to install it as well.
Can you make changes and create a pull request? (on the documentation page, you have a small edit link on the top right side).

**Comment by MorrisJobke** [comment]
Fixed with #6231
