### ISSUE TITLE
LDAP-Password-Change documentation clarification

### ISSUE THREAD

**Issue by Sauermann** [nextcloud/documentation#624]
In  "[documentation/admin_manual/configuration_user/user_auth_ldap.rst](https://github.com/nextcloud/documentation/blob/stable12/admin_manual/configuration_user/user_auth_ldap.rst)" it is stated:
`Access control policies must be configured on the LDAP server to grant permissions for password changes.`

However this gives a false impression.
Default ldap accessrights allow (besides an admin) only the user himself to change his password, so this sencence can be interpreted in the wrong way.
Since a user has the accessright to change his own password in ldap, I assumed, that this is enough to fulfill the requirement. Also others made this assumption (See nextcloud/server#3200).

Please update the doumentation to reflect the fact that as [explained in this comment](https://github.com/nextcloud/server/issues/3200#issuecomment-280565627) the entity used for connecting to the ldap server needs the accessrights to change user passwords. 
As an alternative, implement a separate ldap connection with the user himself for the passwordchange, which would be securitywise much more sensible.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
@Sauermann thanks for the report. I added a line about the current state, cf. https://github.com/nextcloud/documentation/pull/625
