### ISSUE TITLE
App development : "Background Jobs" part needs update

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/documentation#627]
I tried to apply what's written in [here](https://docs.nextcloud.com/server/12/developer_manual/app/backgroundjobs.html) for PhoneTrack and it didn't work.

Then i looked at [the same chapter of Owncloud doc](https://doc.owncloud.org/server/latest/developer_manual/app/fundamentals/backgroundjobs.html) and managed to make it work.

Is the Nextcloud doc up to date ? Is the method described there supposed to work in Nextcloud 12 ?

**Comment by marcelklehr** [comment]
I think it would be better to remove the section entirely instead of having information that's plain wrong.

**Comment by skjnldsv** [comment]
@marcelklehr could you help? :)

**Comment by rullzer** [comment]
This has recently been updated https://docs.nextcloud.com/server/stable/developer_manual/app/backgroundjobs.html
