### ISSUE TITLE
Webdav projects link is invalid in webdav docs

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/documentation#629]
Got this today via contact form:

Hello, 

I just wanted to report a broken link on this url: 
https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html#accessing-files-using-microsoft-windows 
The link to the webdav project isn't valid: 
http://www.webdav.org/projects/ (The whole website seems to be down).

**Comment by MorrisJobke** [comment]
Fix is in #630

**Comment by MorrisJobke** [comment]
Merged and deployed for all versions.
