### ISSUE TITLE
Link to nextcloud 21 developer docs broken

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/documentation#6342]
https://docs.nextcloud.com/ links to the nextcloud 20 and 21 developer manuals.

The link to nc20 developer documentation works: https://docs.nextcloud.com/server/20/developer_manual/

This link to nc21 developer documentation does not work: https://docs.nextcloud.com/server/21/developer_manual/ (HTTP 404 - not found)

**Comment by acsfer** [comment]
Fixed.
