### ISSUE TITLE
Max file upload limit due to 32 or 64 bit PHP

### ISSUE THREAD

**Issue by janvlug** [nextcloud/documentation#640]
I ran into the issue that I saw a max file upload of 2G in the nextcloud admin web page. Initially, I did not understand where this limit came from. Further investigation revealed that it is from the fact that I have a 32 PHP version, that supports file sizes up to 2GB.

I recommend to add some information about this to this page:
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/big_file_upload_configuration.html

I determined whether PHP is 32 or 64 bit by starting and interactive php shell (php -a), and then issuing this command: echo PHP_INT_SIZE ;
The result for 32 bit PHP versions is 4, for 64 bit PHP versions the result is 8.

See also: https://stackoverflow.com/questions/5423848/checking-if-your-code-is-running-on-64-bit-php

**Comment by MorrisJobke** [comment]
cc @icewind1991 what is that status on this?

**Comment by wiswedel** [comment]
Information is available in the meantime: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

> < 2GB on 32Bit OS-architecture
