### ISSUE TITLE
Synchronizing with Windows 10

### ISSUE THREAD

**Issue by olegchensky** [nextcloud/documentation#6468]
The manual is old, I think.
https://docs.nextcloud.com/server/18/user_manual/pim/sync_windows10.html?highlight=calendar

There is not possible to do step 5 with the new Windows versions.
There is no Button "Done". It is needed to add correct data.

**Comment by MariusBluem** [comment]
Microsoft added an credential check to the native Windows 10 email and calendar app and does not allow to continue the account setup if the credentials are not valid. This means that a real existing iCloud account (Apple-ID) must be added first. Then the data can be changed again (CalDAV and CardDAV server address). So nothing has changed from the functionality - but for the initial setup a real Apple-ID and an application specific password is required now.

**Comment by olegchensky** [comment]
I have checked it already course with a real apple-id. Each change must be agreed with the right credentials. I think, the method is wrong now.

**Comment by MariusBluem** [comment]
I've just checked the method (with my workaround from above) on the latest Windows 10 Insider Preview build (21364.1000).
**It works fine and calendar sync was successful.**
