### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/documentation#653]
Hello,

Debian 7 (Wheezy) goes end of support in May 2018. Does that mean that Debian 8 & 9 are supported, and can be added to the list of [supported platforms](https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html#supported-platforms)?

Thanks.

**Comment by tflidd** [comment]
I'm not really sure if these are just a few examples of possible platforms or if they are officially supported when you buy support from Nextcloud GmbH. Technically, Debian 8 and 9 are working with Nextcloud as well. Perhaps we should update this page and clear up if these are just examples or if this refers to official support @jospoortvliet

**Comment by jospoortvliet** [comment]
I made https://github.com/nextcloud/documentation/pull/654 which, after review by the Experts should fix this. Thanks!
