### ISSUE TITLE
Include Warnings About Known Bug Involving S3 and SS Encryption?

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/documentation#6531]
There's [a significant breaking bug](https://github.com/nextcloud/server/issues/22077) in Nextcloud Server where server-side encryption is incompatible with using an object store as a primary data store. The linked issue has been open for the better part of a year.

Because this bug has remained in place for a significant period of time and seems likely to require a significant amount of additional time to be fixed, should there perhaps be a warning about it in the documentation? I recognize that referencing known bugs in the documentation is kind of weird, but this one is a major, long-standing pitfall.

Basically what I'm suggesting is that on each page discussing object storage or server-side encryption there be a notice something like this:

> **Warning:** server-side encryption is incompatible with using an object store as a primary data store. For more information and potential workarounds click [here].

The "click [here]" could be an additional page explaining how to use [`s3backer`](https://github.com/archiecobbs/s3backer) as an alternative backend, which I suggest should be an officially supported solution due to the fact that [it actually works](https://github.com/nextcloud/server/issues/22077#issuecomment-707973123).

I would be happy to create a preliminary pull request to get the ball rolling, though I'm less qualified to write a help article regarding migrating to `s3backer`. Please let me know if it would be okay for me to do so. Thanks!

FWIW I think it would be great if Nextcloud supported [Cryptomator](https://cryptomator.org/) as a preferred encryption solution (for the purposes of allowing interoperability), but I recognize that that is [a separate issue](https://help.nextcloud.com/t/nextcloud-client-side-encryption-with-cryptomator-feature-request/13323).

**Comment by mashedkeyboard** [comment]
FWIW [I've already made a PR to do this](https://github.com/nextcloud/documentation/pull/6333), which is approved, but hasn't been merged.
