### ISSUE TITLE
Nextcloud manual has wrong webdav address.

### ISSUE THREAD

**Issue by orangepizza** [nextcloud/documentation#661]
https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html

address mentioned there (davs://example.com/nextcloud/remote.php/dav/files/USERNAME/) doesn't work and will throw 500 error.

davs://example.com/nextcloud/remote.php/webdav works

**Comment by juliushaertl** [comment]
That URL is correct. Please fill out the issue template and provide proper logs so we can see where the issue is when accessing that URL.

**Comment by mrclschstr** [comment]
Hello everyone,

the URL `https://example.com/nextcloud/remote.php/dav/files/USERNAME/` does definitly **not** work. The only working URL is `https://example.com/nextcloud/remote.php/webdav/` (like @orangepizza already mentioned). I've tested this with NC 12.0.5 and 13.

The funny thing is, that the "correct" URL is shown in the screenshot, whereas the "wrong" URL is stated in the text. See: https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html#mapping-drives-with-windows-explorer.

Can this issue be reopened?

**Comment by tflidd** [comment]
> https://example.com/nextcloud/remote.php/dav/files/USERNAME/

I tried this with cyberduck and NC 12.0.5 and this type of link is working. So it's not generally broken, could be a configuration issue on the webserver or a client issue (the drive mapping on Windows with webdav is not that great in general).

**Comment by mrclschstr** [comment]
Nevertheless: Why are there two paths? The documentation isn't clear as well regarding the screenshot I mentioned above.

**Comment by tflidd** [comment]
Let's continue the discussion about the documentation in the other topic. It's clear that this should be cleaned up. For your problem, I would guess this is somehow related to your configuration. The forum is probably the first point to ask for help. Then it could be either a real bug (then it's an issue for this bug tracker), or we can perhaps use this to improve the documentation for others.
