### ISSUE TITLE
Page about Versionsverwaltung is outdated

### ISSUE THREAD

**Issue by oparoz** [nextcloud/documentation#662]
That page is missing the section about how to configure config.php to alter the behaviour:
https://docs.nextcloud.com/server/12/benutzerhandbuch/files/version_control.html

**Comment by MorrisJobke** [comment]
> That page is missing the section about how to configure config.php to alter the behaviour:

What do you mean? Retention policy?

**Comment by oparoz** [comment]
> What do you mean? Retention policy?

Correct.

```
You may alter the default pattern in config.php. The default setting is auto, which sets the default pattern:

'versions_retention_obligation' => 'auto',
Additional options are:

D, auto
Keep versions at least for D days, apply expiration rules to all versions that are older than D days
auto, D
Delete all versions that are older than D days automatically, delete other versions according to expiration rules
D1, D2
Keep versions for at least D1 days and delete when they exceed D2 days.
disabled
Disable Versions; no files will be deleted.
```

**Comment by MorrisJobke** [comment]
@oparoz But the page you linked is the user manual (even if it is the german user manual). This should be documented in the admin manual and there this is already the case: https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/file_versioning.rst

**Comment by oparoz** [comment]
Argh, I see where the problem is... The German version is the benutzerhandbuch... We still don't have a German version of the the admin pages. Let's close this then.

**Comment by MorrisJobke** [comment]
> Argh, I see where the problem is... The German version is the benutzerhandbuch... We still don't have a German version of the the admin pages. Let's close this then.

Correct. There is only `user_manual_de` ;)
