### ISSUE TITLE
Building the Client on Mac / qt5 webkit

### ISSUE THREAD

**Issue by LeSwiss** [nextcloud/documentation#666]
Hi all
I'm trying to build my own client version on Mac HighSierra following the newest instructions on the nextcloud page: https://docs.nextcloud.com/desktop/2.2/building.html step by step. Unfortunately

`cmake -DCMAKE_BUILD_TYPE="Debug" ..`

lead to:

```
  Failed to find Qt5 component "WebKitWidgets" config file at
  "/usr/local/Cellar/qt/5.10.0_1/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake"

-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen dot
-- Configuring done
CMake Error at src/gui/CMakeLists.txt:271 (add_executable):
  Target "nextcloud" links to target "Qt5::WebKitWidgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Obviously Qt5WebKit is totally missing:

```
UM01358:cmake$ ls -l Qt5Web
Qt5WebChannel/       Qt5WebEngine/        Qt5WebEngineCore/    Qt5WebEngineWidgets/ Qt5WebSockets/       Qt5WebView/
```

So the nextcloud doc tell me:

```
Install a Qt5 version with qtwebkit support:

brew install qt5 --with-qtwebkit
```

but qt5 comes no longer with the webkit?! Did nobody tried with this instructions, or am I missing something?
Thanks in advance.

Kind regards

**Comment by MorrisJobke** [comment]
This is the updated version: https://github.com/nextcloud/client_theming#building-on-osx

Or just look into the build.sh which is used on our build server: https://github.com/nextcloud/client_theming/blob/master/osx/build.sh

**Comment by MorrisJobke** [comment]
The latest client needs other steps, but those need to be provided by @rullzer or @mario
