### ISSUE TITLE
NC13: External storage support

### ISSUE THREAD

**Issue by blueish4** [nextcloud/documentation#669]
On a fresh install of Nextcloud 13, only the following external mount types are supported:

- Amazon S3
- (S)FTP
- Nextcloud
- Openstack
- WebDAV

but there are still outdated guides for Google drive and Dropbox, as well as local storage mounts. These pages should be removed.

**Comment by tflidd** [comment]
It was updated on the nextcloud.com page. There are some apps in development, we should update the page and refer to the apps in development (and update again once it is working).
ref: https://github.com/nextcloud/server/issues/7810

**Comment by tflidd** [comment]
I modified 3 files to fix it:
https://github.com/nextcloud/documentation/pull/686
https://github.com/nextcloud/documentation/pull/687
https://github.com/nextcloud/documentation/pull/688
