### ISSUE TITLE
Old documentation not available

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#6695]
Old documentation of not supported versions is not available any more. However, some people have old versions and for many things it can be useful to access old versions. And they are still linked on the main documentation page.

https://docs.nextcloud.com/server/16/admin_manual/ => File not found error

**Comment by acsfer** [comment]
I can access it https://docs.nextcloud.com/server/16/admin_manual/ 🤔

**Comment by tflidd** [comment]
Cool, someone has fixed it.
