### ISSUE TITLE
Add the contributor guidelines to a page independent from the server version

### ISSUE THREAD

**Issue by schiessle** [nextcloud/documentation#67]
Typically the contributor guidelines don't change from version to version. Therefore it would be good to have a URL which doesn't change for every release. For example in the [CONTRIBUTE.md](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md) we point to https://docs.nextcloud.org/server/10/developer_manual/ which doesn't exists yet.

@jospoortvliet is it possible to have this kind of pages on a non changing URL? Maybe also @LukasReschke

**Comment by jospoortvliet** [comment]
https://docs.nextcloud.org/server/latest/developer_manual/  works now...
