### ISSUE TITLE
Is some bot pushing wrong translations?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/documentation#6747]
Just found this in the documentation:

![image](https://user-images.githubusercontent.com/4511254/121081328-de39e200-c7dc-11eb-8e69-cb9afe98224c.png)

**Comment by enoch85** [comment]
cc @jospoortvliet ?

**Comment by ChristophWurst** [comment]
which documentation? the one you built locally? it's translated and it picks the first language by default.

**Comment by enoch85** [comment]
It was the web live one. 

Maybe just temporary, alls seems good now.
