### ISSUE TITLE
Documentation for Uploading big files should mention httpd TimeOut configuration

### ISSUE THREAD

**Issue by dashih** [nextcloud/documentation#6767]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=large%20uploads

I found this document to be excellent for figuring out PHP options I needed to change.  However, I was still having issues uploading large files (error merging chunks).  After much googling, I found that setting TimeOut in nextcloud.conf for apache fixed it.  This should be mentioned in the above document.

**Comment by joshtrichards** [comment]
Thanks for the suggestion! Looks like this was since added in >=NC23 iterations of the docs. Closing this out.
