### ISSUE TITLE
Invalid link (database performance tips)

### ISSUE THREAD

**Issue by TheFlipside** [nextcloud/documentation#6799]
In the file documentation/developer_manual/getting_started/codingguidelines.rst
At the section "Coding" the following link is invalid: "Check these [database performance tips](https://mailman.owncloud.org/pipermail/devel/2014-June/000262.html)"

**Comment by joshtrichards** [comment]
Thanks. Looks like this got addressed in the NC24 iteration of the docs but this issue wasn't closed out.
