### ISSUE TITLE
api docs

### ISSUE THREAD

**Issue by NawafSwe** [nextcloud/documentation#6803]
I couldn’t find a way to create|delete|update,  files/folders in the api documentation. 
how can I find it?

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html#accessing-files-using-curl

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html?highlight=curl#with-curl

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html?highlight=curl

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/bulkupload.html?highlight=curl
