### ISSUE TITLE
Missing X-Frame-Options header in docs?

### ISSUE THREAD

**Issue by rubrik** [nextcloud/documentation#681]
`X-Frame-Options` is used on https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html but not on https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html

**Comment by MorrisJobke** [comment]
It says:

> These headers are hard-coded into the Nextcloud server, and need no intervention by the server administrator.

So all fine :)

**Comment by MorrisJobke** [comment]
See also https://github.com/nextcloud/server/issues/8207
