### ISSUE TITLE
Misleading description: Configuration Parameters / Deleted Items (trash bin)

### ISSUE THREAD

**Issue by SpamReceiver** [nextcloud/documentation#6889]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin

The description of the configuration parameter `trashbin_retention_obligation` is misleading. There it is described:   
"deletes anytime after that if space is needed (note: files may not be deleted if space is not needed)"

However, this is not the implemented behaviour because the question of whether space is needed will only be answered if a user quota is configured.

Hence, the retention of deleted files depends on the user quota setting! 

This dependency is not documented. Please update the documentation accordingly.

**Comment by isdnfan** [comment]
the intention of the affected user from help.nextcloud.com was to enforce file deletion see https://github.com/nextcloud/server/issues/27756
Maybe there should be some value when trashbin removes old files. Personally I feel keeping files in trashbin longer than 2-3 Months (max 6) makes no sense.

**Comment by tflidd** [comment]
> Personally I feel keeping files in trashbin longer than 2-3 Months (max 6) makes no sense.

Well, can't you set this with the D2 value?



> However, this is not the implemented behaviour because the question of whether space is needed will only be answered if a user quota is configured.

so without quota and the auto setting, deleted files will be kept infinitely?
(you can fix the documentation yourself, there is an edit link on top of each page)
It would be great to update the manual to the current behaviour, in a second step we can improve that behaviour.
