### ISSUE TITLE
Contacts keep being grouped...

### ISSUE THREAD

**Issue by JasonNaughton** [nextcloud/documentation#6939]
Hello All,

I recently setup Nextcloud 21.0.3 to manage my contacts as I was moving away from google.   I have over 800 contacts which I downloaded from google in vCard format and was able to nicely upload into NextCloud.   I was also able to sync my ipad/iphone running iOS 14.2 to my CardDAV NextCloud.   Everything was going well.   It seems when I uploaded my contacts via google it may have created a contacts group called myContacts.  I've noticed that my iphone/ipad have only 550 contacts where my myContacts has 800.   I re-connected my iphone to Google to re-sync all my contacts back down (all 800) and I started to compare my iphone synced to google to my ipad synced to my nextcloud instance.   I noticed a number of contacts where not on my ipad but were on the nextcloud web interface.  Using my iphone I "air dropped" a missing contact to my ipad.   I noticed that the specific contact that I transferred showed up in "Not grouped" on the web interface.    

I assumed that maybe the contacts in myContacts were not somehow sync'ing to my ipad so I started (via the web interface) removing each contact from myContacts so that "Not grouped" was growing in number of contacts.   I clicked and un-check marked the group myContacts off of every contact in my 800+ contact list so that they all showed up in "Not grouped" as I assumed my iphone/ipad could possibly have issues with nextcloud grouops.   Yet when I left to my calendar and returned to contacts 300+ contacts suddenly were back in the contact group myContacts....

Why do Not grouped contacts auto-magically get added to a contact group?

**Comment by ChristophWurst** [comment]
put your question on https://help.nextcloud.com/c/support/7
