### ISSUE TITLE
Broken link to the client manual: access is forbidden

### ISSUE THREAD

**Issue by danieltuzes** [nextcloud/documentation#695]
On page https://docs.nextcloud.com/server/13/user_manual/files/desktop_mobile_sync.html a link to Nextcloud Desktop Client Manual is provided as <a class="reference external" href="https://docs.nextcloud.com/desktop/">Nextcloud Desktop Client Manual</a>, but access is forbidden.

**Comment by tflidd** [comment]
related: https://github.com/nextcloud/documentation/issues/678

**Comment by MorrisJobke** [comment]
Fixed by 666f8007a0e3afcd27d0e2044c3b6df00b8b51d6
