### ISSUE TITLE
Only calender owner can sent invites

### ISSUE THREAD

**Issue by Carina744** [nextcloud/documentation#6960]
"Only the calendar owner can send out invitations, the sharees are not able to do that, whether they have write access to the event’s calendar or not." 

Can this be changed or is there a possibility that there is more than one calendar owner?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/26668

**Comment by ChristophWurst** [comment]
use https://help.nextcloud.com/c/support/7 next time. this is the issue tracker of the documentation
