### ISSUE TITLE
Contacts user manual not available

### ISSUE THREAD

**Issue by TheSimu** [nextcloud/documentation#6976]
Might be a duplicate somwhere down the line: 

![grafik](https://user-images.githubusercontent.com/86853588/126270823-46c5c2f0-0964-4246-ac24-a08cb871d495.png)
When following the link for the user manual ("Benutzer Dokumentation"):
https://docs.nextcloud.com/server/stable/user_manual/pim/contacts.html
=> File not found

Don't know, if the admin-manual-link is correct (at least, the destination somewhat makes no sense to me currently)...

Thanks.

**Comment by TheSimu** [comment]
Ahm, hi, well I do not know how...

**Comment by joshtrichards** [comment]
As far as I'm able to verify, this has since been addressed by swapping out that URL.
