### ISSUE TITLE
add documentation for 22

### ISSUE THREAD

**Issue by Alysko** [nextcloud/documentation#7001]
Hi,

On "mobile & desktop", the first three buttons are dead links. 
On 

### Nexcloud version
22.0.0 (beta channel)

### Steps to reproduce
1. Go to /index.php/settings/user/sync-clients
2. Click on "connect your calendar"

### Expected behaviour
Links lead to this page https://docs.nextcloud.com/server/22/go.php?to=

### Actual behaviour
404

**Comment by kesselb** [comment]
In server links to the documentation are generated with the version number. For example the go.php?to=admin-encryption => https://docs.nextcloud.com/server/22/go.php?to=admin-encryption

Code: https://github.com/nextcloud/server/blob/3860dad9eaac937288d125c75e7f58cfbe44848a/lib/private/legacy/OC_Defaults.php#L294
