### ISSUE TITLE
Admin manual lost table with supported platforms

### ISSUE THREAD

**Issue by ferfebles** [nextcloud/documentation#7011]
The table with information about supported operating systems, databases, webservers and php versions is broken and does not appear in the documentation page.

![image](https://user-images.githubusercontent.com/362413/127455099-86b132aa-514b-436f-9de2-a563677766ae.png)

The last commit lacks an space that broke the table.

![image](https://user-images.githubusercontent.com/362413/127455599-5582f3cb-55bd-4a4c-8171-a937acc177e4.png)

I've sent probably the smallest pull request in history. Just an space to bring back the supported platforms table: #7006

**Comment by kesselb** [comment]
Thanks :+1: 

Fixed by #7006

**Comment by kesselb** [comment]
> I've sent probably the smallest pull request in history.

:laughing:
