### ISSUE TITLE
auto-configuration ends with error

### ISSUE THREAD

**Issue by richardpickett** [nextcloud/documentation#7031]
Centos 8, cpanel/whm server

I downloaded the zip here: https://nextcloud.com/install/#instructions-server

After installing all the modules required in the docs, I unziped nextcloud to a web directory and visited that page in my browser.

I put in my username, pwd, selected mysql and provided all the details and continued.

I get the following error

> Internal Server Error The server was unable to complete
> your request.
> 
> If this happens again, please send the technical details
> below to the server administrator.
> 
> More details can be found in the server log.
> 
> Technical details Remote Address: 71.203.224.28 Request ID:
> YRAy3BZWLccKicG9e5Xi3QAAAAI

In the long there's this:

[Sun Aug 08 14:38:16.027298 2021] [access_compat:error] [pid 20324] [client 34.227.124.90:56394] AH01797: client denied by server configuration: <PATH_TO_NEXTCLOUD>/data/htaccesstest.txt

That file doesn't exist, nor is it in the zip.

Please advise.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
