### ISSUE TITLE
Password Policy Image is not correct.

### ISSUE THREAD

**Issue by ynott** [nextcloud/documentation#712]
**Link expiration** is not exist on nextcloud

This is the image from owncloud Enterprise Edition.
![image](https://user-images.githubusercontent.com/2724312/37197349-d08ee91e-23bd-11e8-9c52-faa9f6fc6d99.png)

Correct image.
![image](https://user-images.githubusercontent.com/2724312/37197309-a6e6abba-23bd-11e8-8ea9-9c25d915ce9d.png)

**Comment by MorrisJobke** [comment]
cc @MariusBluem @jospoortvliet

**Comment by MariusBluem** [comment]
Where did you see this?
https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_password_policy.html

**Comment by tflidd** [comment]
https://docs.nextcloud.com/server/13/admin_manual/configuration_files/file_sharing_configuration.html?highlight=password%20policy#share-link-password-policy
