### ISSUE TITLE
Nextcloud 22.0版本ldap新用户无法显示组共享文件

### ISSUE THREAD

**Issue by z351150948** [nextcloud/documentation#7125]
nextcloud 22.0版本，设置ldap后能获取所有用户，但最新加入ldap的用户无法显示指定共享组的文件。在用户’个人设置下’，没有显示”您是以下群组的成员”

且无法查看权限指定为ldap组才能查看的共享文件

![image](https://user-images.githubusercontent.com/69672687/132274477-70ee7f09-ff61-4fda-8c11-5d2c3243bd75.png)

**Comment by kesselb** [comment]
Hey, please rephrase your question in english and post it to https://github.com/nextcloud/server/.
