### ISSUE TITLE
Make the documentation landing page independent

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#717]
Currently the landing page `/index.html` depends on the stable9 resources on the docs server. We should make this independent.

@skjnldsv mind to check this out and maybe also adjust to the new theme ;) (ref #705) 

For example 

https://github.com/nextcloud/documentation/blob/06f37c97ddef7d91dee6884b276b8bc425560e92/index.html#L20-L26

**Comment by skjnldsv** [comment]
Fixed by #720
