### ISSUE TITLE
LDAP page says LDAP is read only, but actually users can change their password

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/documentation#734]
In "User authentication with LDAP" change "Only read access to your LDAP (edit or delete of users on your LDAP is not supported)" to make clear that users can actually change their LDAP password in Nextcloud.

**Comment by tflidd** [comment]
@blizzz can you have a look?

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
By default it is read-only. The password-change is the only thing that can be enabled, but it is opt-in. And the documentation is clear about that enabling this needs write permissions.

**Comment by tflidd** [comment]
@awesome-manuel what do you think? Perhaps a link in to the documentation somewhere or something different could help?

**Comment by awesome-manuel** [comment]
I was reading the documentation when I switched to LDAP. The first thing I noted was "read only" so initially I didn't search any further for how users could change their password. Only by chance I found the checkbox to enable password changes.
So I think the feature list should be more clear as this is the first thing someone can quickly read through.

**Comment by awesome-manuel** [comment]
The LDAP application supports:

- LDAP group support
- File sharing with Nextcloud users and groups
- Access via WebDAV and Nextcloud Desktop Client
- Versioning, external Storage and all other Nextcloud features
- Seamless connectivity to Active Directory, with no extra configuration required
- Support for primary groups in Active Directory
- Auto-detection of LDAP attributes such as base DN, email, and the LDAP server port number
- Only read access to your LDAP (edit or delete of users on your LDAP is not supported)
- **Optional: Allow users to change their LDAP password from Nextcloud**

**Comment by blizzz** [comment]
@awesome-manuel Yeah, looks good! Would be up for trying to add it to the actual the file? https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_user/user_auth_ldap.rst
