### ISSUE TITLE
Editor Suggestions

### ISSUE THREAD

**Issue by c0fe** [nextcloud/documentation#736]
So I am currently making edits to the documentation and I am doing so using Atom text editor but I was wondering if anyone is aware of any sort of GUI editors for RestructuredText documentation. Mainly just so I do not have to format the text myself, for example having to add the spaces to enable code section or headline or anything like that. Any suggestions?

**Comment by MorrisJobke** [comment]
> So I am currently making edits to the documentation and I am doing so using Atom text editor but I was wondering if anyone is aware of any sort of GUI editors for RestructuredText documentation. Mainly just so I do not have to format the text myself, for example having to add the spaces to enable code section or headline or anything like that. Any suggestions?

Maybe check for plugins for Atom. I often use Sublime Text or Visual Studio Code and then install a plugin that provides the functionality that I need. Sadly I'm not aware of any autocompletion feature and I personally only use the highlighting part.

Maybe @jospoortvliet or @MariusBluem have something nice.
