### ISSUE TITLE
sync_thunderbird.rst - Old information in the doc about Lightning Calendar

### ISSUE THREAD

**Issue by always-tinkering** [nextcloud/documentation#7382]
The Lightning calendar add-on has been removed by the author from the Thunderbird.

**Comment by ChristophWurst** [comment]
do you have any references? what are the implications of this change?

**Comment by always-tinkering** [comment]
I opened this issue after I created the PR. The PR was already pulled in. Thanks

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/documentation/pull/7383 is the PR. Had to look it up.

That still doesn't explain *why* this was dropped. Do you have any link for me? Where was this announced?

**Comment by always-tinkering** [comment]
I was using the manual to integrate nextcloud into thunderbird calendar and contacts. When doing so I found a step that was unecessary, submitted a PR to recommend a change.
