### ISSUE TITLE
Trusted domain API

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#7416]
https://github.com/nextcloud/server/pull/29444 needs corresponding dev docs.

**Comment by ChristophWurst** [comment]
@nickvergessen will you make sure this is done for 23?

**Comment by nickvergessen** [comment]
The PR is in.
I wouldn't even know where I would expect such a documentation and also I find it rather niche, so not sure where to put it.

**Comment by ChristophWurst** [comment]
I would add a *Security* page to https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/index.html
