### ISSUE TITLE
Plaintext emails config switch

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#748]
- [ ] Document https://github.com/nextcloud/server/pull/9205

**Comment by MorrisJobke** [comment]
Is the entry in https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html#mail-parameters enough? Will be automatically appear once https://github.com/nextcloud/server/pull/9231 is merged ;)

**Comment by MorrisJobke** [comment]
Was merged and the last entry in https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html#mail-parameters documents it now

**Comment by MariusBluem** [comment]
Yes. That’s enough.
