### ISSUE TITLE
wrong link - datadir permissions

### ISSUE THREAD

**Issue by cptechnik** [nextcloud/documentation#7485]
I have all the time problems with permissions with nextcloud and synology manual installation, 
and there is an errorpage shows following text:
(german)

> Dein Datenverzeichnis ist ungültig Stelle sicher, dass eine Datei ".ocdata" im Wurzelverzeichnis des data-Verzeichnisses existiert. Kann das "Daten"-Verzeichnis nicht erstellen Dies kann zumeist behoben werden, indem dem Web-Server Schreibzugriff auf das Wurzel-Verzeichnis eingeräumt wird. Siehe auch https://docs.nextcloud.com/server/21/go.php?to=admin-dir_permissions 

linked to
 https://docs.nextcloud.com/server/21/go.php?to=admin-dir_permissions 
will be redirected to 
 https://docs.nextcloud.com/server/21/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions
but there is no information to the permissions... or?

**Comment by tflidd** [comment]
In old versions, there were settings for more strict directory permissions:
https://github.com/nextcloud/serverinfo/blob/ca2b970061df1f724668239d92188849d2a24541/css/style.scss

**Comment by tflidd** [comment]
There is a fix to remove this invalid link:
https://github.com/nextcloud/documentation/issues/7485

**Comment by obel1x** [comment]
@cptechnik 
the commit above has been merged. Can you close this issue?

**Comment by tflidd** [comment]
I think we can close this. Ideally, we would change the code base as well, that the error message does no contain the link any more (should be a fix in the server or app code repository, not in the docmentation). However for NC21, we are out of support and no new fixes will be pushed. I couldn't find the string in the main repository, perhaps it was rephrased.
