### ISSUE TITLE
Update list of supported apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/documentation#75]
admin_manual/installation/apps_supported.rst

**Comment by nickvergessen** [comment]
Missing:
* workflowengine
* files_accesscontrol
* files_automatedtagging (to be written)

**Comment by oparoz** [comment]
### Missing in 9
* Auditing / Logging
* Calendar
* Contacts
* Shibboleth/SAML authentication
* Windows Network Drive storage

**Comment by MorrisJobke** [comment]
Let me update this :)

**Comment by oparoz** [comment]
Thanks @MorrisJobke :)
Seems there are items missing both in 9 and 10 and it's unknown if Antivirus is still supported per example.

**Comment by MorrisJobke** [comment]
stable9: #82 #84 
stable10: #83 
master: #85

**Comment by MorrisJobke** [comment]
Should be all fixed now. Also check out #87 ;)
