### ISSUE TITLE
Missing anchor icon when hovering a heading

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#752]
Until recently, it was possible to hover a heading and a little icon appeared which led to an anchor URL like https://docs.nextcloud.com/server/13/developer_manual/general/devenv.html#enabling-debug-mode. Today, there is no hover effect, which makes it harder to quickly locate and copy those URLs to reference specific sections in our documentations.

I hope my report makes sense. I don't know the technical term for this hover effect thingy :wink:

**Comment by MorrisJobke** [comment]
Was broken by https://github.com/nextcloud/documentation/commit/59851ab8005afe6447f7dc1c80eefc42cb0ffcb4 (@jospoortvliet I told you that adding this amount of random stuff will for sure break something) 😉 

Let me fix it.

**Comment by ChristophWurst** [comment]
I love commits that start with `this should fix …` :stuck_out_tongue_closed_eyes:

**Comment by MorrisJobke** [comment]
Fix is in #753

**Comment by ChristophWurst** [comment]
Thank you, @MorrisJobke!
