### ISSUE TITLE
Give more detail for the --include-incoming-shares flag on occ files:transfer-ownership 

### ISSUE THREAD

**Issue by Vilasamuni** [nextcloud/documentation#7559]
I've seen https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#transfer
which says you should use the flag like this:
`sudo -u www-data php occ files:transfer-ownership --transfer-incoming-shares=1 --path="path_to_dir" <source-user> <destination-user>` 
but it doesn't say what the value `1` means. Somewhere else I've seen an example which uses the value `2` with no explanation. 

I commented on [this Pull Request](https://github.com/nextcloud/server/pull/28118#issuecomment-965102426) and someone kindly pointed me to the relevant section of code. I think I understand how to do what I want with the command, but I'm still not sure why there is a `2` option rather than allowing users to just pass `true` or `false`.

**Comment by ChristophWurst** [comment]
@ipasanec could you contribute your usage infos from https://github.com/nextcloud/server/pull/28118#issuecomment-966064154 to https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst please? There is an existing section for file transfer :)

**Comment by ipasanec** [comment]
@ChristophWurst oops, somehow i missed it. Better late than never :-S
I added the info to the manual: https://github.com/nextcloud/documentation/pull/7606
