### ISSUE TITLE
Broken link: https://docs.nextcloud.com/server/13/user_manual/files/desktop_mobile_sync.html

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/documentation#757]
Reported by a user via website form, details below. 

Comments: There is a broken link on this page: 

https://docs.nextcloud.com/server/13/user_manual/files/desktop_mobile_sync.html 

The link with a title of \"Nextcloud Desktop Client Manual\" points to https://docs.nextcloud.com/desktop/, but when I click on it I get \"Access forbidden\".

**Comment by MorrisJobke** [comment]
stable13 ef206f62
