### ISSUE TITLE
Document the @NoTwoFactorRequired route handler annotation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#7587]
Ref https://github.com/nextcloud/server/pull/29752

**Comment by joshtrichards** [comment]
Looks to have since been added here from what I can tell:

https://docs.nextcloud.com/server/latest/developer_manual/basics/controllers.html?highlight=notwofactorrequired#authentication

Okay to close?

**Comment by joshtrichards** [comment]
Fixed in #9359
