### ISSUE TITLE
Get rid of existing sphinx erors/warnings

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/documentation#7637]
When building the documentation in the GitHub actions, some errors in the existing code are rosen. These should be removed to avoid cluttering the annotations of any PR involved.

**Comment by christianlupus** [comment]
@rakekniven I think you are one of the admins of the transifex integration, am I right?

There are some strings badly translated causing the documentation to break (partially). Do you have a good idea, how one could tackle this problem in general?

I could create a list of languages and files where there are issues (although this will take some time). I am not able to read all languages involved. Thus, I cannot solve this all on myself. After #7646 is merged there  are only a hand full of problems left.

**Comment by rakekniven** [comment]
Hello @christianlupus I am just a volunteer spending time for NC project.

I am not into this sphinx thing. But I will spend an eye on it the next days.

**Comment by christianlupus** [comment]
> Hello @christianlupus I am just a volunteer spending time for NC project.

Me too. I just saw you a moderator on the transifex platform although I did not find a quick way to contact you there, @rakekniven.

> I am not into this sphinx thing. But I will spend an eye on it the next days.

It is more a thing of the correct syntax of the restructured text files. If the syntax is bad, links are not generated but just an arbitrary (to the reader) text is displayed. I was just wondering how we can get rid of these _bad_ translations in favor of syntactically correct ones. My thought was to extract said list, have a look at which translations are an issue and then try to recover. Most probably, the punctuation is wrong or some technical words have been translated that need to keep in English (link names etc). 

I can look at the translations and tell you what is wrong. I can't change that in transifex. The question is: Could you alter the relevant strings in transifex? Then we would soon be done, I think.

**Comment by rakekniven** [comment]
> The question is: Could you alter the relevant strings in transifex?

Yes, for sure.

> I can't change that in transifex.

You can get the necessary permissions to do that. Help is welcome.

**Comment by christianlupus** [comment]
Hello, @rakekniven. I found issues in the following languages: `br`, `da`, `de`, `el`, `es`, `fr`, `gl`, `it`, `nl`, `nn`, `pl`, `pt_BR`, `tr`, `zh_CN`, and `zh_HK`.

In transifex, I have access to `de`, `es`, `fr`, `pl`, and `nl`. I will provide updates to these languages soon.
How can I obtain access to the other languages? Or would you prefer me to send the changes to you in some way?

**Comment by christianlupus** [comment]
@rakekniven Regarding the translations, I worked my way through the transifex languages, I was able to access. Some of the translations were already fixed, so I could only put suggestions there. It will take some time until everything is finally through.

I found that the `nl` translation did not get any update in the last 11 months. I was just seeing this as I checked if all errors were gone and the `nl` still threw a few but I was quite sure to have them tackled. Is the translation always pushed directly to GitHub or are there circumstances that will only sync at night? Otherwise, it might be a good idea to check if there is an issue with the `nl` ttranlsations.

Do you have any idea, how to get #7646 approved at best? Should I better break it down into a PR related to the pure documentation (restructured text), one related to the image generation and one related to the build in GH actions?

**Comment by rakekniven** [comment]
Hello @christianlupus , missed your replay. Sorry for that.

> How can I obtain access to the other languages?

Just invited you to all listed languages as reviewer.

**Comment by rakekniven** [comment]
> Do you have any idea, how to get #7646 approved at best? Should I better break it down into a PR related to the pure documentation (restructured text), one related to the image generation and one related to the build in GH actions?

Splitting it would be great. Makes it easier to work with it.
Currently I do not know who to contact since Morris is not here anymore.

**Comment by christianlupus** [comment]
> Splitting it would be great. Makes it easier to work with it.

Done as requested. The related PRs are #7826, #7827, #7828, #7829, #7830, and #7831. 

> Currently I do not know who to contact since Morris is not here anymore.

That is bad news. I will write to the talk channel and see if there is anyone able to provide a name/link.

> Just invited you to all listed languages as reviewer.

Thank you. I will tackle these soon, I hope this evening.

Thanks for the information!

**Comment by rakekniven** [comment]
Hey @christianlupus Is it ok to close here as provided separate PRs for this issue?

**Comment by christianlupus** [comment]
I think so. Reopening this or a more specific issue is always possible.
