### ISSUE TITLE
External mysql link for binlog settings links to transaction isolation levels

### ISSUE THREAD

**Issue by ViktorF** [nextcloud/documentation#767]
Yesterday I happened to notice that at some point the required binary logging settings were changed. So I wanted to read about the differences between the options.

But the link mentioned in the binlog section links to the MySQL Transaction Isolation Levels.
![binlog_link](https://user-images.githubusercontent.com/4988213/40222173-346b768c-5a6e-11e8-85cb-056d10ce45bb.jpg)

I guess it should link to https://dev.mysql.com/doc/refman/5.7/en/binary-log-formats.html

**Comment by MorrisJobke** [comment]
Could you send in a pull request with the needed change? The file that needs to be adjusted is https://github.com/nextcloud/documentation/blob/aee9597c08bbec7aae87b11d4d6ed178faf36a79/admin_manual/installation/system_requirements.rst

**Comment by ViktorF** [comment]
I'm on it!
