### ISSUE TITLE
Document calendar trashbin admin setting

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/documentation#7696]
> `php occ config:app:set dav calendarRetentionObligation --value=%value%` where `%value%` must be replaced by a number of seconds. 0 equals to disabled.

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/stable/user_manual/en/groupware/calendar.html#calendar-trash-bin user docs are already there. But wrongly say that the retention period is always 30d.

**Comment by tcitworld** [comment]
Yeah, it was about admin settings #7701
