### ISSUE TITLE
F-Droid links are in German

### ISSUE THREAD

**Issue by nextcloud486153** [nextcloud/documentation#7716]
Throughout the user manual, specifically in the Groupware > Synchronizing with Android, there are several links to F-Droid, but the links in the English version of the manual are to the German page of the apps (Nextcloud Android and DAVx5).

**Comment by rakekniven** [comment]
> there are several links 

Please name them.

**Comment by nextcloud486153** [comment]
In file `/user_manual/groupware/sync_android.rst` there are several, in lines: 9, 30 and 55. In the latter, there's a space in the middle of the URL that should be removed.
