### ISSUE TITLE
Add client docs to Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/documentation#7729]
Currently the user docs for the server are available at TX.
As the client is a very popular part of Nextcloud and there are plenty of questions regarding it at the forums it would help to have it localised.

Please add the docs for the client as well.

**Comment by rakekniven** [comment]
@mgallien What do you think about my issue?

**Comment by p-bo** [comment]
@rakekniven please see https://github.com/nextcloud/desktop/issues/3234

**Comment by rakekniven** [comment]
@p-bo Thanks for the link.

**Comment by mgallien** [comment]
I would clearly support work to get the client documentation translated
I have the impression that keeping documentation alongside the desktop client is easier to maintain
I am under the impression that it would be odd to have a server23 branch with outdated client documentation and a stable-3.5 with an outdated server documentation

**Comment by rakekniven** [comment]
@mgallien Got your arguments 👍 

Close here and stay with linked issue.
