### ISSUE TITLE
Change the wording of "Trusted Domains" to actually reflect the required configuration

### ISSUE THREAD

**Issue by bitshiftnetau** [nextcloud/documentation#7762]
Your documentation indicates that all IPs used to access the dashboard need to be added. I know I'm not the first to assume this means add your client desktops:

```All URLs used to access your Nextcloud server must be whitelisted in your config.php file, under the trusted_domains setting. Users are allowed to log into Nextcloud only when they point their browsers to a URL that is listed in the trusted_domains setting. You may use IP addresses and domain names. A typical configuration looks like this:```

Whereas in actual fact it's the hosted address of Nextcloud that requires insertion. 

Why is this not reflected in the docs? This cannot be right.

**Comment by rakekniven** [comment]
Hello @bitshiftnetau ,

your cite is pointing to https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/installation_wizard.rst#trusted-domains

> Users are allowed to log into Nextcloud only when they point their browsers to a URL that is listed in the trusted_domains setting.

Is this not correct for your understanding?

Please propose a wording change if needed?

**Comment by bitshiftnetau** [comment]
Sure, I think it's best to speak plainly and be explicit.

"The list of trusted domains is for the server-side, specifically where NextCloud is hosted. This is not a list of allowed client-side domains or addresses. Users will only be able to access the Nextcloud if it's own hosted address is in the trusted domains list"

**Comment by rakekniven** [comment]
Fixed in #7852 
I read it more than once and added a part of your suggestion.
Now it should be clear.

**Comment by bitshiftnetau** [comment]
> Fixed in #7852 I read it more than once and added a part of your suggestion. Now it should be clear.

Legend.
