### ISSUE TITLE
new PPT is built, and PPT is displayed as Chinese garbled.

### ISSUE THREAD

**Issue by hymany** [nextcloud/documentation#778]
![123](https://user-images.githubusercontent.com/19706331/41275536-cd5c5b56-6e53-11e8-94af-b6770f343f09.png)

**Comment by MorrisJobke** [comment]
Please report this in the onlyoffice repo, which is the correct place to reach the maintainers of this feature.

https://github.com/ONLYOFFICE/onlyoffice-owncloud
