### ISSUE TITLE
Admin docs need overhaul for 23

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#7782]
Ref https://github.com/nextcloud/server/issues/27846

**Comment by nickvergessen** [comment]
Anything specific you have in mind?

**Comment by ChristophWurst** [comment]
The recommended php version to reflect the deprecation of 7.4 at least

**Comment by blizzz** [comment]
what do we do with this issue? it's been pushed around for a while.

**Comment by blizzz** [comment]
23.0.12 will be the last release btw

**Comment by ChristophWurst** [comment]
Yeah.
