### ISSUE TITLE
check_for_working_webdav is no longer valid

### ISSUE THREAD

**Issue by rullzer** [nextcloud/documentation#780]
This is no longer a valid config option and should be removed from the docs.

**Comment by MorrisJobke** [comment]
It's not in our docs. It needs to be removed from the config sample, which syncs to the docs. ;)

https://github.com/nextcloud/server/blob/stable13/config/config.sample.php#L641-L645

**Comment by MorrisJobke** [comment]
Was removed in https://github.com/nextcloud/server/pull/9276
