### ISSUE TITLE
Translations are not correctly synchronized between Transifex and GitHub

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/documentation#7848]
I recently stumbled upon the problem that some translations are out of sync between Transifex and the GitHub repo here. I do not know the internals on how the sync is going to happen and what is needed to get it going. However, I got the following answer:

> At 5Am CET the sync run is started. Once a day. Not event triggered by modifying strings or other activities.

_Originally posted by @rakekniven in https://github.com/nextcloud/documentation/issues/7637#issuecomment-989971597_

This is sort of strange. For one, I saw PRs generated during the day to reflect the changes made by Transifex. These changes are almost instantaneous, so it looks like a webhook to me. When you look at the dates of the commits generated in this repo's history by the bot, you see these are distributed over all day.

Also, I do not see anything in the GitHub workflows that indicates something related to the daily push/pull using Transifex. I suspect there is some external CI involved that uses [these docker files](https://github.com/nextcloud/docker-ci/tree/master/translations). But it is just a wild guess.

On the other hand, there are texts in Transifex that are not correctly synchronized to GitHub. Let's take [this translation](https://github.com/nextcloud/documentation/blob/d56c26990bb444f9cdf53f1f15a444ca3c18b6e6/user_manual/locale/gl/LC_MESSAGES/files/sharing.pot#L108-L110) as an example. It was committed on 2020-08-22 09:49 CEST. Looking at the [corresponding entry in transifex](https://www.transifex.com/nextcloud/nextcloud-user-documentation/translate/#gl/user-manual-locale-source-files-sharing-pot--master/296034347?q=text%3Apassword), one sees that the translation in Transifex has `**` at the ending of the string while the POT file in the Github repo only has `*`.

I added the second `*` yesterday in the evening (before 5 AM CET). The change was not propagated to GitHub. Neither _live_ nor on a daily run, the changes were pushed in a PR. I removed and readded the asterisk once in an effort to trigger the webhook (if it was there).

Other files were updated accordingly (e.g. #7845). So, at least, something seems to be working also in this language. I am honestly a bit lost as I do not know who might help here and how to tackle this.

I have seen a few locations in the translations that seem to be out of sync. I found them as some had syntactical errors that rose during test builds. I cannot say how many are tainted/outdated but do not rise any compiler warnings. One would have to do a 1:1 check between the Transifex website and the GitHub repository to find these.

@ChristophWurst I have seen you have done some housekeeping recently. Do you know something or someone to help here?

**Comment by rakekniven** [comment]
#7658 is related to this one.

**Comment by christianlupus** [comment]
Unfortunately, @CarlSchwan your PR #7892 did not solve the problem. In transifex the problem was solved quite some time ago: 
![grafik](https://user-images.githubusercontent.com/8202922/149995207-b93d8f9f-5512-440f-bab6-14c2815d5ecc.png)

The corresponding file in `master` is currently over 10 months old.

Should we reopen this issue or stick with #7658?
