### ISSUE TITLE
Nextcloud in a subdir of NGinx when different machines

### ISSUE THREAD

**Issue by zarmhast** [nextcloud/documentation#795]
`admin_manual/installation/nginx.html` has a section about using php-fpm with NGinx while the site is installed in a subdir. There are a few issues:
### Original ###
```
        location ~ ^/nextcloud/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on;
            #Avoid sending the security headers twice
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
        }
```

- `fastcgi_split_path_info` - requires a trailing slash breaking the split_path logic in cases that there is no trailing slash. Fix: `fastcgi_split_path_info ^(.+?\.php)(/.*)?$;` (question mark at the end) But in case that the php-fpm and nginx server have the files installed to different paths (e.g. when using docker) if should be `fastcgi_split_path_info ^/nextcloud(.+?\.php)(/.*)?$;`
- Missing `SCRIPT_NAME` param. This is used to detect the path prefix. There is an issue serving css and js files otherwise. `fastcgi_param SCRIPT_NAME /nextcloud$fastcgi_script_name;`
- In case that NGinx and FPM paths are different should not use `$document_root`. `fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;` - worked for me.
- Initial setup takes a long time as well as some cases with big lists of files over WebDav, resulting in 504 error code from NGinx. Fix: `fastcgi_read_timeout 300;`

### Suggested ###
```
        location ~ ^/nextcloud/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
            fastcgi_split_path_info ^/nextcloud(.+?\.php)(/.*)?$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME /nextcloud$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on;
            #Avoid sending the security headers twice
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_read_timeout 300;
            fastcgi_pass next-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
        }
```
This config works for the case when NGinx has static assets under /nextcloud/, yet php-fpm still has all the scripts under /var/www/html (e.g. remote host or docker nextcloud:fpm image)

**Comment by zarmhast** [comment]
Used OwnCloud documentation for inspiration.

**Comment by MorrisJobke** [comment]
cc @josh4trunks

**Comment by josh4trunks** [comment]
Thank you for the suggestions.
Here are my comments on your individual points.

* **fastcgi_split_path_info**
That slash is not to catch trailing slashes, it is a method Nextcloud uses to specify a specific data / asset file as PATH_INFO. For example, `/nextcloud/index.php/my_files/picture.jpg`
If there is no forward slashes after a .php there is no need to split the path to capture the correct SCRIPT_FILENAME and PATH_INFO
Also see the note on **document_root** below.

* **SCRIPT_NAME**
NGINX's default `fastcgi_params` has `fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;`
As long as `fastcgi_split_path_info` is properly used or not needed to be used, the correct SCRIPT_NAME shall be passed to PHP-FPM

* **document_root**
I think the scenario you are configuring for is more complicated then we need to document for. If an admin is installing Nextcloud on a system with different paths to the source files, they should be able to make the few modifications needed so that PHP-FPM is passed the correct location.
My production server has a similar configuration as yours, I have PHP execute in a FreeBSD jail, while nginx executes on the host. I only had to modify the `SCRIPT_FILENAME`, which I realized by reading PHP-FPM's logs. If you think this deserves mentioning you can propose a note, but I have never heard anyone other than you or I needing to make this change. I assume anyone with this complex a setup has the ability to make this update without asking for help, as you and I did.

* **fastcgi_read_timeout**
I think mentioning this could go under "Tips and tricks", or somehow integrated in the "Uploading big files > 512MB" page which already has notes on working around timeouts. At a certain point this is more NGINX specific not specific the Nextcloud.

**Comment by bulzipke** [comment]
Neither can I run nextcloud with subdir.

I am running the nextcloud and nginx with the following options.
`docker run --link mariadb:mysql --name nextcloud -v /sharedfolders/Docker/nextcloud/data:/var/www/html -d nextcloud:fpm`

`docker run -p 80:80 -p 443:443 --link nextcloud:nextcloud --name nginx -v /sharedfolders/Docker/nginx/data/www:/usr/share/nginx/html -v /sharedfolders/Docker/nginx/data/nginx.conf:/etc/nginx/nginx.conf:ro -v /sharedfolders/Docker/nginx/data/ssl:/etc/nginx/ssl -d nginx:latest
`

https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html
In the above site, I set up the subdir. And I connect to 'https://myserver.org/nextcloud' nginx log tell me 
`2018/07/22 17:27:11 [error] 5#5: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.155.1, server: myserver.org, request: "GET /nextcloud HTTP/2.0", upstream: "fastcgi://172.17.0.4:9000", host: "myserver.org"
172.18.155.1 - - [22/Jul/2018:17:27:11 +0000] "GET /nextcloud HTTP/2.0" 404 36 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"`

And here is my question.
**fastcgi_split_path_info ^(.+?\.php)(/.*)$;** finally tries /var/www/html/nextcloud
So the following expression is correct?
**fastcgi_split_path_info ^/nextcloud(.+?\.php)(/.*)$;** finally tries /var/www/html
And I can connect to nextcloud first welcome page with subdir (/nextcloud, but without correct image)

I do not have an exact knowledge of nginx, but I think the subdir description needs to be modified or explained in more detail.

**Comment by zarmhast** [comment]
@josh4trunks 
- **SCRIPT_NAME**`
The problem with the script name is that sometimes nextcloud redirects to `some_page.php` (e.g. `index.php` during the initial configuration) and in that case there is going to be no trailing slash, meaning that the regex will not match and the path will not be corrected before invoking fpm.

- **fastcgi_read_timeout**
Might be NGinx specific, but I was not expecting Nextcloud to take that long to set itself up, so I think this parameter is worth mentioning in the nginx.conf section, since it is talking about everything else.

@josh4trunks, I hear you. Experienced admins should have no problem pinpointing what changes need to be made and not many would have the need to use such a sophisticated setup. Yet as a time saver I think it is worth changing the default regex to include the question mark at the end and mentioning to check the `SCRIPT_NAME` variable in case of problems with CSS.

In any case this ticket can be closed.

**Comment by zarmhast** [comment]
@bulzipke, you also need to mount the nextcloud html folder into NGinx, since fpm does not handle static resources (e.g. css). And you need to keep in mind which server is using which paths and which server is handling which requests.

**Comment by bulzipke** [comment]
@zarmhast, oh... I had completely forgotten to place the nextcloud in the nginx path.
Also, your configuration file has also helped me a lot. Thank you so very much :)

**Comment by josh4trunks** [comment]
@zarmhast sorry for taking a while to respond.

Hmm, I don't fully understand.
If the path is "/index.php/something" then **fastcgi_split_path_info** will be used.
If it is "/index.php" then what path would even need to be split?

**Comment by zarmhast** [comment]
@josh4trunks, in my case to the outside world nextcloud is in a subfolder:
```
GET /subdir/index.php HTTP/1.1
```

Whilst fpm has no subdir, hence it should only be
```
GET /index.php HTTP/1.1
```
And yet, in order to do the path math correctly and render pages with the correct links it is also required to pass in the script name of `/var/www/html/index.php` vs `/var/www/html/subdir/index.php` that you would end up without the `fastgi_split_path_info ^/subdir(.+?\.php)` (removing the *subdir* prefix)

I do not know of a more suitable way to remove the prefix from the request path prior to passing it through to fpm.

**Comment by josh4trunks** [comment]
@zarmhast Ahh, I understand. You are using **fastcgi_split_path** for more than it's originally intended purpose, which works fine. I have solved a similar issue before, and I think this should also work for your situation without always having to invoke **fastcgi_split_path_info**, just capture the location when matching it and use it.

```
location ~ ^/nextcloud/(index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param SCRIPT_NAME /nextcloud/$1.php;
```

**Comment by cfelder** [comment]
see also: https://github.com/nextcloud/docker/issues/1055
