### ISSUE TITLE
References to unknown pim directory

### ISSUE THREAD

**Issue by 35am** [nextcloud/documentation#7962]
While making the fix https://github.com/nextcloud/documentation/pull/7961 I saw that there was a lot of other references to the _pim_ directory even though it doesn't exist anymore.

Those references are all in _.pot_ files under the _locale_ directory. See https://github.com/nextcloud/documentation/search?l=Gettext+Catalog&q=pim

For the French locale there's the following example : https://github.com/nextcloud/documentation/blob/77cf0e1c843ee19987dc1d5ec11b7941bf3e7b27/user_manual/locale/fr/LC_MESSAGES/groupware/sync_ios.pot#L25

The locale file for _/groupware/sync_ios.rst_ makes references to _/pim/sync_ios.rst_. But only the first one exists since the _pim_ directory has been removed.

I don't know how the I18n here works so I can't say exactly what happens because it seems to be working, but I guess it still can be problematic to make references to things that no longer exists.

I picked the _fr_ locale because it's my main language, but I saw this issue on other locales like it can be seen here : https://github.com/nextcloud/documentation/search?l=Gettext+Catalog&q=pim

**Comment by nickvergessen** [comment]
> The locale file for /groupware/sync_ios.rst makes references to /pim/sync_ios.rst. But only the first one exists since the pim directory has been removed.

It's still there for the old versions, so it will be in there as long as stable22 and stable21 are translated/supported

**Comment by 35am** [comment]
Thank you for the explanations! I guess there's nothing to see here then.
