### ISSUE TITLE
warning/note-layout

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/documentation#799]
**How it is:**
<img width="859" alt="bildschirmfoto 2018-07-04 um 09 38 19" src="https://user-images.githubusercontent.com/19711361/42263507-856ad742-7f6e-11e8-8139-4581dc75d91e.png">

**How it should be:**
<img width="863" alt="bildschirmfoto 2018-07-04 um 09 39 34" src="https://user-images.githubusercontent.com/19711361/42263515-89e5770a-7f6e-11e8-92f9-d55fe8025406.png">
<img width="856" alt="bildschirmfoto 2018-07-04 um 09 41 10" src="https://user-images.githubusercontent.com/19711361/42263530-94f77be8-7f6e-11e8-976e-195ffc389c56.png">

Why was this broken? @MorrisJobke

**Comment by MorrisJobke** [comment]
> Why was this broken? @MorrisJobke

No idea ... maybe during the big restyling by @jospoortvliet earlier this year :/ 🤷‍♂️

**Comment by MariusBluem** [comment]
Was not able to fix this ... @jospoortvliet any idea 🤔

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers
