### ISSUE TITLE
System requirements, missing table of supported versions

### ISSUE THREAD

**Issue by schiessle** [nextcloud/documentation#8034]
I just noticed that here we have a table of supported operating systems, databases, etc: https://docs.nextcloud.com/server/23/admin_manual/installation/system_requirements.html but the table disappears if you open this URL: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

If you look here the table is also not rendered: 
https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst

While if you look at the raw file it is still there: https://raw.githubusercontent.com/nextcloud/documentation/master/admin_manual/installation/system_requirements.rst

Can someone check why the table is broken and how to bring it back?

Thanks!

**Comment by tflidd** [comment]
For me the tables work now, probably fixed by: https://github.com/nextcloud/documentation/commit/63d86393e007fcca59b7c2159f92c35a4bffc00f

If you still see the issue feel free to reopen.
