### ISSUE TITLE
'Synchronizing with KDE Kontact' page has a broken link

### ISSUE THREAD

**Issue by sh44rg** [nextcloud/documentation#8077]
https://docs.nextcloud.com/server/stable/user_manual/en/groupware/sync_kde.html links to https://docs.nextcloud.com/server/stable/user_manual/session_management.html#managing-devices under
3: Enter your username. As password, you need to generate an app-password/token ([Learn more](https://docs.nextcloud.com/server/stable/user_manual/session_management.html#managing-devices)):
which is a broken link.

**Comment by joshtrichards** [comment]
Thanks. This has since been fixed in >=NC20 iteration of the docs.
