### ISSUE TITLE
Remove link to oc repo

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/documentation#8138]
https://github.com/nextcloud/documentation/blame/c63d4ac7c77862aabda0879f51ae2498fbdea002/developer_manual/digging_deeper/performance.rst#L60

**Comment by tflidd** [comment]
Just remove? Or do you have a copy in the Nextcloud repo or something simliar?

**Comment by nickvergessen** [comment]
I guess so

**Comment by iamkkushal** [comment]
Can you please explain me what needs to be done?

**Comment by kesselb** [comment]
Hi @iamkkushal,

remove the section below from https://github.com/nextcloud/documentation/blob/master/developer_manual/digging_deeper/performance.rst 
```
There are a `few nice small scripts <https://github.com/owncloud/administration/tree/master/performance-tests>`_ that can be used for this.
```
