### ISSUE TITLE
php_value statements with '=' in big_file_upload_configuration

### ISSUE THREAD

**Issue by NlL5** [nextcloud/documentation#818]
Hi,
there are equal signs in the php_value statement in [this section](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=big%20file%20upload#configuring-your-web-server) of the big_file_upload_configuration page:

> php_value upload_max_filesize = 16G
> php_value post_max_size = 16G

According to the [php.net manual](http://php.net/manual/de/configuration.changes.php), php_value statements must be without equal signs. Simply copying the statements provided in the documentation to a .htaccess or to an Apache config file will lead to a server error.

The corrected statements should be:

> php_value upload_max_filesize 16G
> php_value post_max_size 16G

This is the case in the Nextcloud 12 as well as the 11 documentation.

**Comment by MorrisJobke** [comment]
@NlL5 Could I ask you to provide this as changes to the files in the repository and those then as pull request here on GitHub?

**Comment by NlL5** [comment]
@MorrisJobke I will!

**Comment by J0WI** [comment]
Fixed in #819
