### ISSUE TITLE
Shortcut links go.php?to= not working in NC 24 [NC 24 RC3]

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#8192]
![grafik](https://user-images.githubusercontent.com/8111200/163732753-77ac2543-bb20-4e29-b20c-df6964b96c41.png)

Link goes to: https://docs.nextcloud.com/server/24/go.php?to=admin-php-opcache

it just says:

> File not found.

**Comment by tflidd** [comment]
Update: None of the go-to-links is working!
https://docs.nextcloud.com/server/24/go.php?to=admin-install

For the latest links and for other versions, it is working:
https://docs.nextcloud.com/server/latest/go.php?to=admin-install
https://docs.nextcloud.com/server/23/go.php?to=admin-install

It would be important to fix this before the release of NC 24!

@MorrisJobke @nickvergessen @jospoortvliet

**Comment by nickvergessen** [comment]
It's on the release todo.

**Comment by nickvergessen** [comment]
partly fixed by https://github.com/nextcloud/documentation/pull/8227
please review
