### ISSUE TITLE
Update example Ubuntu instructions for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by nathanhaines** [nextcloud/documentation#8194]
Hello! As Nextcloud 24 is the first version that supports Ubuntu 22.04 LTS, I thought I would bring the example Ubuntu installation instructions forward to that version. I have tested these instructions twice on Ubuntu 22.04 beta virtual machines and am happy to confirm that with copying and pasting, they result in a working Nextcloud system once an Apache2 conf file is created as per the example Apache configuration page that is linked to at the end of the instructions.

I've created a pull request here: https://github.com/nextcloud/documentation/pull/8186

**Comment by tflidd** [comment]
Fixed here: https://github.com/nextcloud/documentation/pull/8186
