### ISSUE TITLE
Add instructions to use OCP\Notification in Developer Manual

### ISSUE THREAD

**Issue by pellaeon** [nextcloud/documentation#828]
As title, currently there is no documentation on how to use the notification API

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by MorrisJobke** [comment]
@pellaeon Please check out the linked docs in https://github.com/nextcloud/notifications#developers

**Comment by nickvergessen** [comment]
Yeah, docs are in the repository.
We decided to not duplicate them in a second place

**Comment by pellaeon** [comment]
Maybe as least a link to the paragraph in the official documentation? A new developer wouldn't know where to look for that information.

**Comment by juliushaertl** [comment]
Fixed with #895
