### ISSUE TITLE
No links to Nextcloud 21 available

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/documentation#8292]
As Nextcloud 21 is end of life, its documentation should be listed here: https://docs.nextcloud.com/#nextcloud-older

But the last version listed there is Nextcloud 20. 

Seems, that the entries for Nextcloud 21 got lost somewhere...

**Comment by tflidd** [comment]
I created a PR for your issue: https://github.com/nextcloud/documentation/pull/8311
