### ISSUE TITLE
Links on docs.nextcloud.com all lead to "file not found"

### ISSUE THREAD

**Issue by martin21** [nextcloud/documentation#8445]
All links I tried on

https://docs.nextcloud.com/

lead to file not found in several browsers. Including the links for the current Nextcloud 24 release.

Expected result: The links point to the actual documentation.

**Comment by villivateur** [comment]
Same here for me.

**Comment by tstivers1990** [comment]
Amateur hour

**Comment by Idesmi** [comment]
This issue occurs to me too.

If anyone has a mirror / PDF of the admin documentation, please share.

**Comment by newhinton** [comment]
For now you can try using web archive:
https://web.archive.org/web/20220414105746/https://docs.nextcloud.com/server/latest/developer_manual/

**Comment by nickvergessen** [comment]
24, 23 and 22 are back.
latest is still being build
