### ISSUE TITLE
No Referrer-Policy header in nginx configuration example

### ISSUE THREAD

**Issue by fa-ribeiro** [nextcloud/documentation#845]
Nextcloud 14 checks in the setupchecks if the Referrer-Policy header is set (See: https://github.com/nextcloud/server/issues/9122).
However, there is no reference to it in the nginx configuration example (https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst).

**Comment by familyman-131** [comment]
here's options for nginx virtualhost
>     add_header X-Content-Type-Options nosniff;
>     add_header X-XSS-Protection "1; mode=block";
>     add_header X-Robots-Tag none;
>     add_header X-Download-Options noopen;
>     add_header X-Permitted-Cross-Domain-Policies none;
>     add_header Referrer-Policy no-referrer;
>     # Remove X-Powered-By, which is an information leak
>     fastcgi_hide_header X-Powered-By;

**Comment by J0WI** [comment]
Fixed in #856
