### ISSUE TITLE
Remove unnecessary text on docs.nextcloud.com

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/documentation#8456]
In the section with the older versions: https://docs.nextcloud.com/#nextcloud-older

The first sentence says it all: "This documents the **older** versions of Nextcloud. "

Therefore I suggest to remove the sentence "This documents a **previous** version of Nextcloud." in all the following subsections. 
In the subsection of [Nextcloud 14](https://docs.nextcloud.com/#nextcloud-14) and older the sentence is not there at all.

**Comment by iamkkushal** [comment]
I have submitted a PR, can someone please review.
