### ISSUE TITLE
Nextcloud Broadcast Messages for only Admin Users

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/documentation#8458]
I want to know how to broadcast messages from the talk application and I don’t want the users to send messages in the group only the admin should send a message in the groups.
How Can I give permissions so that only the admin can send a message in a talk group conversation?
It is quite an emergency for me to know how can we able to achieve this in the talk application. Kindly Help me as quickly as possible.

**Comment by joshtrichards** [comment]
Hi @Gowtham-eng - This is a channel for reporting mistakes or enhancements for the documentation. It's not a general support channel. I suggest taking your question to the Nextcloud Help Forum (https://help.nextcloud.com).
