### ISSUE TITLE
.htaccess invalid has file integrity check

### ISSUE THREAD

**Issue by rladelman771** [nextcloud/documentation#8462]
Upgraded from 23.0.3 to 24.0.1.  Had this problem before.
Solved it originally by https://help.nextcloud.com/t/integrity-check-htaccess/136897/4

This time the hash is different and can't seem to figure out how to fix.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => d9cab0f077161bf043d6d85f5bcacbdfaf82913968b7706df9cf7e6f98b11af363f3843b455175ae775567916822fec8f6ab95000ba064c71e05c86a02196d95
                            [current] => aab002636038627a549cdc33b749fe7ef74fcbb2a52decf1af0b4c90394d869d982dd7a2d3ce72d1d5114b21aa73cb35ddb6c8b54760ca0e7347e7b26760d6ab
                        )

                )

        )

)

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/issues/code_signing.html#fixing-invalid-code-integrity-messages

This is generally a local environment/configuration issue. The Help Forum (https://help.nextcloud.com) is the best spot for these types of matters.
