### ISSUE TITLE
No documentation of Referrer-Policy header for lighttpd available

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/documentation#851]
Nextcloud 14 checks in the setup checks if the Referrer-Policy header is set 
However, there is no sample configuration for lighttpd available!

regards, hitam

**Comment by JayGatsby7** [comment]
> Nextcloud 14 checks in the setup checks if the Referrer-Policy header is set
> However, there is no sample configuration for lighttpd available!
> 
> regards, hitam

I am also impacted by this -- would appreciate guidance

**Comment by MorrisJobke** [comment]
> However, there is no sample configuration for lighttpd available!

We do not recommend to use lighttpd - see the section in http://sabre.io/dav/webservers/ for the reasons. Because of this we will also not provide an example configuration in our manual.
