### ISSUE TITLE
`objectstore_multibucket` - wrong class

### ISSUE THREAD

**Issue by damianbobrowski** [nextcloud/documentation#8575]
At file https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/primary_storage.rst
```
'objectstore_multibucket' => [
        'class' => 'Object\\Storage\\Backend\\Class',
        'arguments' => [
                // optional, defaults to 64
                'num_buckets' => 64,
                // will be postfixed by an integer in the range from 0 to (num_nuckets-1)
                'bucket' => 'nextcloud_',
                ...
        ],
],
```

Is:  
`'class' => 'Object\\Storage\\Backend\\Class',`

Seem to be be: 
 `'class' => 'OC\\Files\\ObjectStore\\S3',`

"Confirmation" at of github action:
https://github.com/nextcloud/server/runs/6952720438?check_suite_focus=true
```
 echo '<?php $CONFIG=["objectstore_multibucket" => ["class" => "OC\Files\ObjectStore\S3", "arguments" => ["bucket" => "nextcloud", "autocreate" => true, "key" => "minio", "secret" => "minio123", "hostname" => "localhost", "port" => 9000, "use_ssl" => false, "use_path_style" => true, "uploadPartSize" => 52428800]]];' > config/config.php
 ``

**Comment by kesselb** [comment]
Hi, 

`'Object\\Storage\\Backend\\Class'` is a placeholder. If you read the complete article it makes more sense. First section uses the same placeholder to explain the configuration array. Second section are the concrete object store providers (s3 or swift) and the third section shows how to extend section 1 and section 2 to use a multi bucket. 

We are always open for pull requests to improve the documentation. When you have a good idea go ahead.

Closing the issue as it's not the wrong class.
