### ISSUE TITLE
Docs don't build anymore on our server

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/documentation#858]
stable14 and master break because of the dev-api stuff:
```
cd build && composer install && composer update
Repository type is not registered: github
Makefile:43: recipe for target 'api-docs' failed
make: *** [api-docs] Error 1
```

The problem is there is composer installed in a weird way and it's still running version `1.0.0-beta2`

@MorrisJobke should have a look at it and try to get rid of this old composer and install a proper new version

**Comment by nickvergessen** [comment]
For the record, I did:
`sudo apt remove composer` and followed: https://getcomposer.org/download/ to install 1.7.2

**Comment by juliushaertl** [comment]
I'll look into that.

**Comment by nickvergessen** [comment]
well, it's building again now. The question is, if my removal of composer was complete and correct, so I think it would be better if @MorrisJobke has a look.

**Comment by juliushaertl** [comment]
OK, i got that wrong. I thought the build was still broken with that.

**Comment by MorrisJobke** [comment]
> well, it's building again now. The question is, if my removal of composer was complete and correct, so I think it would be better if @MorrisJobke has a look.

It worked because it was already installed, but once we have a fresh instance it will fail 🙈

**Comment by MorrisJobke** [comment]
Fixed
