### ISSUE TITLE
Header is missing some menu entries

### ISSUE THREAD

**Issue by oparoz** [nextcloud/documentation#86]
This is the header when browsing the documentation

<img width="880" alt="header_doc" src="https://cloud.githubusercontent.com/assets/323220/17173640/4e7facca-53fc-11e6-87c3-e6c90ae9e4d4.png">

And this is the one when browsing the website

<img width="905" alt="header_site" src="https://cloud.githubusercontent.com/assets/323220/17173646/56f4f838-53fc-11e6-9f7c-3ca131fdce8a.png">

Can you fix it @jospoortvliet ?

**Comment by MorrisJobke** [comment]
Fix is in #88

**Comment by oparoz** [comment]
Thanks @MorrisJobke!
