### ISSUE TITLE
overwrite.cli.url requires a trailing "/" in NC 14.0.0

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/documentation#863]
NC 14 seems to require a trailing slash in the specification of overwrite.cli.url in config/config.php

```
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess
```

Without a trailing slash:
> Error updating .htaccess file, not enough permissions or "overwrite.cli.url" set to an invalid URL?

With a trailing slash:
> .htaccess has been updated

If this is a permanent situation, then these two files need updating:

- [Installation on Linux](https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/source_installation.rst) ([Pretty URLs](https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html?highlight=pretty#pretty-urls))
- [config.sample.php](https://github.com/nextcloud/server/blob/master/config/config.sample.php) ([Line 464](https://github.com/nextcloud/server/blob/master/config/config.sample.php#L464))

**Comment by nickvergessen** [comment]
We should additionally fix this, to allow both.

**Comment by b3** [comment]
On my 14.0.1.1 installed version none of the two (with or without trailing slash) work. Using the `maintenance:update:htaccess` command of `occ` always gives me the cited error.

Pretty URL are not working anymore at that stage.

**Comment by Linutux** [comment]
I also have this problem with and without a trailing slash. File .htaccess is owned by the right user, permissions are OK, but problem persists. Nextcloud 14.0.1.1.

**Comment by juliushaertl** [comment]
This has been fixed with https://github.com/nextcloud/server/pull/11446.

**Comment by b3** [comment]
My trouble was due to the ownership of the `.htaccess` file (owned by `root` and in the webserver user group instead of owned by the webserver user) because I still used/fixed access granting through a script created when I installed Nextcloud 9.
That was my mistake (did not reread full documentation when upgrading).
