### ISSUE TITLE
Fix incorrect _group_commands_label anchor

### ISSUE THREAD

**Issue by denismosolov** [nextcloud/documentation#865]
![selection_020](https://user-images.githubusercontent.com/3057626/45642403-bc462180-bac0-11e8-9cab-4b90f59ab9fa.png)

**Comment by denismosolov** [comment]
Weird, it looks good when I build it locally via `make admin-manual-html`
![selection_025](https://user-images.githubusercontent.com/3057626/45713967-0995c200-bb99-11e8-980f-6592f7e5c3d7.png)

**Comment by MorrisJobke** [comment]
Fix is in #882
