### ISSUE TITLE
3 mistakes in developer_manual/client_apis/index.rst

### ISSUE THREAD

**Issue by euku** [nextcloud/documentation#879]
[developer_manual/client_apis/index.rst](https://github.com/nextcloud/documentation/blob/master/developer_manual/client_apis/index.rst)
1. "Client API's" -> "Client APIs". Also the other 2 occurrences of "api's"...
2. "downloading an uploading files" -> "downloading an**d** uploading files" (d is missing)
3. "information that are not available" -> "information that is not available" (uncountable)

**Comment by MorrisJobke** [comment]
@euku Could I ask you to hand this in as a pull request right here on GitHub? Just click the little pencil icon to edit the file 😉

**Comment by euku** [comment]
Oh, I didn't know this can be done that easy.. :-)
Done.
