### ISSUE TITLE
Use of the the built in php mailer is no longer supported

### ISSUE THREAD

**Issue by dt64** [nextcloud/documentation#896]
after upgrading from NC 13.0.6 to NC14.0.1 the installation comes back with all sorts of unexpected issues.

One of these issues is:
Use of the the built in php mailer is no longer supported. [Please update your email server settings :arrow_upper_right:]

on one hand this is annoying since php mailer was working in all versions before and there might be good reasons to use it instead of a SMTP server.

on the other hand… the updater is checking all kinds of stuff before upgrade (or pretends to do so) but there isn’t even a warning that a core feature will be disabled by upgrading.

Further: the manual clearly states (https://docs.nextcloud.com/server/14/admin_manual/configuration_server/email_configuration.html 1):
Supported methods are php, smtp, sendmail

Nextcloud version (eg, 12.0.2): 14.0.1
Operating system and version (eg, Ubuntu 17.04): 18.04
Apache or nginx version (eg, Apache 2.4.25): Nginx 1.14.0
PHP version (eg, 7.1): 7.2

The issue you are facing:
Use of the the built in php mailer is no longer supported

Is this the first time you’ve seen this error? (Y/N): y

Steps to replicate it:

    run Nextcloud 13
    upgrade to NC14.0.1 using updater app
    face issue

https://help.nextcloud.com/t/use-of-the-the-built-in-php-mailer-is-no-longer-supported/38459

**Comment by MorrisJobke** [comment]
@MariusBluem Mind to remove it?

**Comment by MorrisJobke** [comment]
See also https://github.com/nextcloud/server/issues/11377 for more details.

**Comment by MorrisJobke** [comment]
I just noticed that this is already available as a ticket: #854

let's continue there then.
