### ISSUE TITLE
Documentation for file drop feature needed

### ISSUE THREAD

**Issue by schiessle** [nextcloud/documentation#90]
From Nextcloud 9 on people can allow users to upload files to a public link without seeing the files stored in the folder.

To do this you have to create a public link for a folder, check "can upload" and then "hide file listing"

**Comment by hagengraf** [comment]
fixed with #96

**Comment by mar1u5** [comment]
It was not 😒 ... As discussed we've reverted all these changes #101 #102 #103 and #104 😉 
There is a documentation already 😉 

THX anyway.

**Comment by MorrisJobke** [comment]
> It was not 😒 ...

Reopen then?

**Comment by mar1u5** [comment]
as discussed 😅
