### ISSUE TITLE
"Domain Change" in admin manual outdated or unclear

### ISSUE THREAD

**Issue by andreagualandi** [nextcloud/documentation#9115]
In your [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/domain_change.rst) it’s specified that domain change is not supported, but some of the users on the “Help” forum have been able to do a domain change without any problem (editing trusted_domains and overwrite.cli.url).
I’ve also tried locally on my docker, and no problems were encountered.

Is there something I’m missing or the doc is out of date?

Thanks

**Comment by kesselb** [comment]
> Is there something I’m missing

The documentation is up to date. For example the activity app is using absolute url's sometime. Take a look at the database table's and search for your old domain. It depends on the installed apps.
