### ISSUE TITLE
binding to AD with mail creation

### ISSUE THREAD

**Issue by tach-tm** [nextcloud/documentation#9138]
When connecting to AD, is it possible to create a mail and bind it to the nextcloud login according to the template "sAMAccountName@mail.com"? Since the user does not have mail or mail is not set in AD in the attributes.

**Comment by joshtrichards** [comment]
Hi @tach-tm - This isn't a general technical support channel. Your query is probably better suited for the [Nextcloud Help Forum](https://help.nextcloud.com). Have a wonderful day!
