### ISSUE TITLE
Nextcloud 14 administration Manual, Installation wizard enhancement 

### ISSUE THREAD

**Issue by yugofire** [nextcloud/documentation#917]
Hi,

 I wanted to know if it was possible to replace the next line in the documentation for the installation wizard Line 67: 

"You will need the root database login, or any administrator login that has permissions to create and modify databases, and then enter any name you want for your Nextcloud database."

By : 
"You will need the root database login, or any administrator login , and then enter any name you want for your Nextcloud database.
Be careful your administrator login needs to have the permissions to create
and modify databases and he needs to have the permissions to grant permissions
to other users."

Cause I got stuck in the installation wizard just because of this little mistake and I believe that I'm not the only one.

I hope that helps someone.

**Comment by MorrisJobke** [comment]
@yugofire Sure - best is to hand this in as pull request. I guess you are referring to https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/installation_wizard.rst? Just click the little pencil and propose your change. We then can comment and accept it. 👍

**Comment by tflidd** [comment]
Thanks, you did it here and it was merged:
https://github.com/nextcloud/documentation/pull/920
