### ISSUE TITLE
The trusted-domains URL Documentation not working on NextCloud 25

### ISSUE THREAD

**Issue by pablolucas890** [nextcloud/documentation#9181]
When I'm start server in a different domain, the untrustedDomain message open to me, the message are ok, but the documentation link isn't working

I check old versions changing the version name on url and olds versions working, but the version 25 opem a error on web (File not found.)

![image](https://user-images.githubusercontent.com/56566628/191975003-46eeb93e-12dd-4312-9a6c-c982af1bfa83.png)
![image](https://user-images.githubusercontent.com/56566628/191975129-101489ce-732b-441f-8be6-e7b621f3f6c9.png)

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Documentation is available again.
