### ISSUE TITLE
`file not found` and `access forbidden` when attempting to access documentation on docs.nextcloud.com

### ISSUE THREAD

**Issue by sunjam** [nextcloud/documentation#9182]
User Manuals, Administrator Manuals and Developer Manuals are all inaccessible from the United States for some reason.  Never encountered this issue before.

Probably related to #9181

**Comment by isdnfan** [comment]
was the same in CH (likely everywhere), but works again now.

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Documentation is available again.

**Comment by plague69** [comment]
Down again?

**Comment by sunjam** [comment]
Yep, not working for me either
