### ISSUE TITLE
Document new share attributes and the "download" permission

### ISSUE THREAD

**Issue by PVince81** [nextcloud/documentation#9186]
Ref https://github.com/nextcloud/server/pull/32482

```
curl -u admin:admin 'https://domain.tld/ocs/v2.php/apps/files_sharing/api/v1/shares/$shareId` \
  -X 'PUT' \
  -H 'OCS-APIRequest: true' \
-H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"attributes":[{"scope": "permissions", "key": "download", "enabled": "false"}]}'
```

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/documentation/pull/9518

**Comment by xeruf** [comment]
Is there any way to create a link with this attribute set via curl and not have to make a separate PUT request?
Checked the docs but got nothing the like to work:

    curl ... -X POST -d 'path=/DIR&shareType=3&permissions=1&publicAccess=1&expireDate=2023-04-15&attributes=[{"scope":"permissions","key":"download","enabled":false}]'

https://docs.nextcloud.com/server/stable/developer_manual/client_apis/OCS/ocs-share-api.html#share-attributes

**Comment by xeruf** [comment]
any comments?

**Comment by xeruf** [comment]
hi? @PVince81
