### ISSUE TITLE
simpleSignUpLink.shown from config.php not documented

### ISSUE THREAD

**Issue by GAS85** [nextcloud/documentation#927]
Hello, 'simpleSignUpLink.shown' parameter is missing in documentation. Please added it at least as it done in [config.sample.php](https://github.com/nextcloud/server/blob/159d75945a57be7a391cc16a17744adfd4376473/config/config.sample.php#L1665).

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/MorrisJobke/nextcloud-config-converter/commit/0600adb90cba7fc0c714580530f313a225044377

The next sync (it's currently running) will bring this also to the 14 docs.

Thanks for pointing this out.
