### ISSUE TITLE
Missing infomration about: appstore.experimental.enabled

### ISSUE THREAD

**Issue by GAS85** [nextcloud/documentation#931]
Hi all, just saw in [forum ](https://help.nextcloud.com/t/apps-not-working-in-nextcloud-14/41455)in config sample option `'appstore.experimental.enabled' => true,` but I could not find any information about it. Also in config.sample.php. Could you please update documentation? Or was it depreciated?

**Comment by MorrisJobke** [comment]
This option was removed a long while ago in Nextcloud 11: https://github.com/nextcloud/server/pull/1940

This setting just does nothing anymore.
