### ISSUE TITLE
Documentation for `latest` does not point to latest version

### ISSUE THREAD

**Issue by susnux** [nextcloud/documentation#9328]
I noticed that the documentation for `latest` still points to NC24 instead of NC25.
I would expect `stable` to point to NC24 (as thats where the docker `stable` tag points to) but `latest` to point to either the current master or at least the latest release (NC25).

Noticed this while reading the calendar section which has a breaking change between NC24 and NC25: https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/groupware/calendar.html#calendar-providers

**Comment by kesselb** [comment]
cc @blizzz

**Comment by blizzz** [comment]
latest  goes against master, and stable against 25. And i don't see it working wrongly. For example, here in latest 26 is shown: https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/index.html while earlier versions don't have 26 obviously.
