### ISSUE TITLE
"fastcgi_hide_header X-Powered-By" twice in Nextcloud 14 Documentation

### ISSUE THREAD

**Issue by timm2k** [nextcloud/documentation#933]
Hi,

the clause 
```
    # Remove X-Powered-By, which is an information leak
    fastcgi_hide_header X-Powered-By;
```
appears twice in [Documentation of Nextcloud 14](https://docs.nextcloud.com/server/14/admin_manual/installation/nginx.html?highlight=nginx).

Regards
Timm

**Comment by MorrisJobke** [comment]
@timm2k Do you mind to send a pull request with this change? You could directly edit here on GitHub by clicking the little pencil in https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst

**Comment by timm2k** [comment]
Thanks for the hint :-)
This is already fixed in master. I've created #934 for stable14.

Regards
Timm
