### ISSUE TITLE
admin docs: trystack.org seems to be dead project

### ISSUE THREAD

**Issue by p-bo** [nextcloud/documentation#9400]
In file

https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/config_sample_php_parameters.rst

of chapter

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html

There is referenced (and linked site of) project trystack.org. But this site seems to be offline and also repositories of it are confirming its fate:

https://github.com/trystack

(last changes before realy long time)

Maybe it would be wise to remove this topic from text of manual due its obsolescence.

**Comment by gitoffmyln** [comment]
You are proposing removing the whole topic, "Using Object Store with Nextcloud"?

I would disagree.  While trystack.org and it's repo are lifeless, OpenStack Swift remains a good option for storage in Nextcloud.  It's documented here for object store mode (primary storage), and elsewhere for external storage (secondary).

My suggestions:
- Delete references to trystack.org, including the 1st config example.
- Review the 2nd example config.  (or not)
- Re-evaluate the compatibility warning about any app using direct file I/O  (eg: Encryption and Gallery)  Still correct**?**  Or do apps now use virtual filesystem reliably**?**
- Does the multi-bucket object store for preview still exist now, as it was in Nextcloud 19**?**
- Bonus round: Consider an S3 compatible storage example.

Or, if nobody's interested, I'd suggest only the first one.

**Comment by joshtrichards** [comment]
Fixed in nextcloud/server#39978.
