### ISSUE TITLE
Docs not available

### ISSUE THREAD

**Issue by adrianhiller** [nextcloud/documentation#9423]
The docs at https://docs.nextcloud.com/ are not available.

**Comment by mikolfaro** [comment]
[Latest)](https://docs.nextcloud.com/server/latest/user_manual/) version docs are broken.
[Stable](https://docs.nextcloud.com/server/stable/user_manual/en/) docs work for me.

**Comment by meonkeys** [comment]
I got a 404 for all the links I tried on `docs.nextcloud.com` just now.

**Comment by kesselb** [comment]
Seems to work again :partying_face:
