### ISSUE TITLE
config:app:set The "--type" option does not exist.

### ISSUE THREAD

**Issue by unnilennium** [nextcloud/documentation#9494]
documentation for NC 23, 24 , latest tells
```

sudo -u www-data php occ config:app:set files_sharing
incoming_server2server_share_enabled --value="yes"
Config value incoming_server2server_share_enabled for app files_sharing set to yes
```

here is the actual result using NC 24 
```

# occ config:app:set --value="true" --type=boolean duplicatefinder ignore_mounted_files 

                                       
  The "--type" option does not exist.  
                                       

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

and here is the output of the command help

```
# occ config:app:set --help
Description:
  Set an app config value

Usage:
  config:app:set [options] [--] <app> <name>

Arguments:
  app                    Name of the app
  name                   Name of the config to set

Options:
      --output[=OUTPUT]  Output format (plain, json or json_pretty, default is plain) [default: "plain"]
      --value=VALUE      The new value of the config
      --update-only      Only updates the value, if it is not set before, it is not being added
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
      --no-warnings      Skip global warnings, show command output only
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

```

please fix the documentation

also as a result when seeing this https://github.com/PaulLereverend/NextcloudDuplicateFinder 
Setting | Type | Default
ignore_mounted_files | boolean | false

without type option should I do 

```
occ config:app:set --value="true"  duplicatefinder ignore_mounted_files 
#or
occ config:app:set --value="1"  duplicatefinder ignore_mounted_files 
```

**Comment by kesselb** [comment]
Hi and thanks for your report :+1: 

The --type option is available for `occ config:system:set`. 
system means the command will modify config.php.

`occ config:app:set` will alter the oc_appconfig database table. 
A --type option is not available here. 

NextcloudDuplicateFinder seems to use a wrapper around our app configuration code: https://github.com/PaulLereverend/NextcloudDuplicateFinder/blob/dc64f8240eab29388c2fae62136983f5801392e6/lib/Service/ConfigService.php#L29

`occ config:app:set --value="true"  duplicatefinder ignore_mounted_files` looks like the correct command. 

Would you mind sending a pull request for the Duplicate finder app to improve the documentation?
