### ISSUE TITLE
Memcache documentation inadequate and dangerous

### ISSUE THREAD

**Issue by seatrout** [nextcloud/documentation#953]
The recommendation to use php-apcu is outdated. It suggests adding 
`'memcache.local' => '\OC\Memcache\APCu',`
to the config.php file. This breaks everything. I assume it hasn't been edited since these were owncloud docs. 
It also - less seriously - assumes people are using PHP5* and not 7*. 
But the urgent issue is that adding the suggested line to config.php will break nextcloud in a cascade of 500 errors which are very difficult to debug.

**Comment by MorrisJobke** [comment]
> to the config.php file. This breaks everything. I assume it hasn't been edited since these were owncloud docs.

It is not wrong itself. Could you check you have enabled the php module apcu? Because otherwise it fails because of this (logged to webserver error log because it can't log to nextcloud log because of missing module)

**Comment by seatrout** [comment]
I'm pretty certain I have enabled the module:
I have certainly installed it. 
`pi@owncloud:~% _ ls -l /etc/php/7.2/mods-available
total 80
-rw-r--r-- 1 root root 18 Oct 16 10:11 apcu.ini
-rw-r--r-- 1 root root 74 Aug 19 07:56 calendar.ini
-rw-r--r-- 1 root root 71 Aug 19 07:56 ctype.ini
-rw-r--r-- 1 root root 70 Aug 19 07:56 exif.ini
-rw-r--r-- 1 root root 74 Aug 19 07:56 fileinfo.ini
-rw-r--r-- 1 root root 69 Aug 19 07:56 ftp.ini
-rw-r--r-- 1 root root 73 Aug 19 07:56 gettext.ini
-rw-r--r-- 1 root root 71 Aug 19 07:56 iconv.ini
-rw-r--r-- 1 root root 68 Aug 19 07:56 json.ini
-rw-r--r-- 1 root root 79 Aug 19 07:56 opcache.ini
-rw-r--r-- 1 root root 69 Aug 19 07:56 pdo.ini
-rw-r--r-- 1 root root 70 Aug 19 07:56 phar.ini
-rw-r--r-- 1 root root 71 Aug 19 07:56 posix.ini
-rw-r--r-- 1 root root 76 Aug 19 07:56 readline.ini
-rw-r--r-- 1 root root 71 Aug 19 07:56 shmop.ini
-rw-r--r-- 1 root root 73 Aug 19 07:56 sockets.ini
-rw-r--r-- 1 root root 73 Aug 19 07:56 sysvmsg.ini
-rw-r--r-- 1 root root 73 Aug 19 07:56 sysvsem.ini
-rw-r--r-- 1 root root 73 Aug 19 07:56 sysvshm.ini
-rw-r--r-- 1 root root 75 Aug 19 07:56 tokenizer.ini
`
but then

**Comment by MorrisJobke** [comment]
Could you run php info on the webserver? https://secure.php.net/manual/en/function.phpinfo.php

Basically place a file:

```
<?php
phpinfo();
```

and then open it on the web server.

**Comment by seatrout** [comment]
I can't, because I tried to apt-get upgrade to get apcu working on php.7.2,
and it stopped, emitted some terrifying messages about systemd and now
won't reboot.

Currently copying off everything in /var/www, /etc/nginx and similar places
so that I can start with a fresh install and then copy back the stuff I
know works.




-------------------
Andrew Brown
Leader writer,
The Guardian
mobile: +44-(0)7968-945618

**Comment by MorrisJobke** [comment]
Sorry, but as this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
