### ISSUE TITLE
Lock dependencies and enable dependabot

### ISSUE THREAD

**Issue by st3iny** [nextcloud/documentation#9546]
Currently, the documentation does not allow reproducible builds because the dependecies are not locked. 

We should lock the dependencies using pipenv (`Pipfile.lock`) and enable dependabot to update our dependencies in a traceable way. Otherwise, each developer will have a slightly different environment depending on the time of dependency installation.

I also suggest getting rid of `requirements.txt` to have a single source of truth for our dependencies (`Pipfile`)

**Comment by ChristophWurst** [comment]
From https://github.com/nextcloud/documentation/pull/9551#issuecomment-1380619775

> Maybe we should use requirements.txt after all and maintain it properly in case of issues like the missing jquery incident.

I came to the same conclusion. We can use `pip freeze --local > requirements.txt ` to lock deps in requirements.txt. Possibly only for the direct dependencies, though, to avoid having to maintain too many Dependabot bumps.
