### ISSUE TITLE
Document new Symfony Mailer behaviour

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/documentation#9600]
- [x] Document debug option
- [x] Document new STARTTLS behaviour
- [x] Document new recipients behaviour - partial sending is no longer supported, all recipients (including cc and bcc) will be returned in the `$failedRecipients` array

**Comment by ChristophWurst** [comment]
NTLM support existed in Swiftmailer but is missing in symfony mailer

https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/Esmtp/Auth/NTLMAuthenticator.php 
https://github.com/symfony/symfony/issues/46337
https://github.com/symfony/symfony/pull/48267
