### ISSUE TITLE
occ offers more than three commands to manage files

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/documentation#9630]
https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst#file-operations

![image](https://user-images.githubusercontent.com/7427347/218724417-d80f0872-2f29-4317-bfbf-dea09009fb87.png)

**Comment by gitoffmyln** [comment]
I'd suggest removing "has three ".

Observations:

1. There are 6 `occ files:` commands.  5 are documented.  

2. `files:recommendations:recommend` appears to be missing, or there could be a reason not to document it yet.  It is mentioned by name in https://help.nextcloud.com/t/occ-ncc-command/127603  (I didn't find the repository for this other doc.)

3. The title "File operations" is not consistent with the command "files:".  As it is, users might type `file` without the s.  Suggest: "Files command" or "Files commands" even if it's awkward sounding.  (The `app:` command also has an inconsistent "Apps commands" heading.)

I'm new, never participated in a PR, but willing to contribute.

**Comment by joshtrichards** [comment]
@gitoffmyln Great ideas. You're in charge! 😊

The easiest way to get started with light doc edits is doing them directly in the GitHub interface in your own fork of the documentation repository. PRs can be directly submitted from there. 

Feel free to reach out if you get stuck. I'm happy to help.

**Comment by joshtrichards** [comment]
> There are 6 occ files: commands. 5 are documented.

Fix pending #12387

> files:recommendations:recommend appears to be missing, or there could be a reason not to document it yet

Fix pending nextcloud/recommendations#821

> The title "File operations" is not consistent with the command "files:". As it is, users might type file without the s. Suggest: "Files command" or "Files commands" even if it's awkward sounding. (The app: command also has an inconsistent "Apps commands" heading.)

Agreed this is confusing. But I think this will have to be tackled by restructuring the entire `occ` chapter. For example, we can make it a real command directory, and index everything by the namespace (e.g. `files`). Maybe we can then, if still useful, have a cross-index (by topic like "File operations") to the relevant namespaces.
