### ISSUE TITLE
Broken link in user manual Groupware/Synchronizing with macOS

### ISSUE THREAD

**Issue by hamza221** [nextcloud/documentation#9651]
The Learn more link [here](https://docs.nextcloud.com/server/latest/user_manual/en/groupware/sync_osx.html#setup-your-accounts) is broken 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/40746210/220385884-6f9cd2b5-acdb-4ffe-904e-239bfb94a7da.png">

**Comment by ChristophWurst** [comment]
seems to work now?
