### ISSUE TITLE
Check if all custom webDAV properties and headers are documented

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/documentation#9659]
see https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties

Check if all are documented and if not create a separate issue with the missing, to-be-documented ones and add it for planning.

We did add afaik aspect-ratio of images as well as location data (photos 26 @artonge) as webDAV properties.
Also for example there is a header X-OC-Mtime that can be sent when uploading a file for preserving the last modified date but isn't documented anywhere.

**Comment by provokateurin** [comment]
> But I do not remember if it is limited to bulk upload or if global to the webDAV API

The header works on the WebDAV API.

**Comment by DaphneMuller** [comment]
Aligned with @artonge , he estimates 1 day of work to finish, clean, and enhance the WebDAV documentation. But it's not scheduled or no timeline is given yet. @AndyScherzinger could you give me a timeline?

**Comment by AndyScherzinger** [comment]
I would need to ask @artonge that question myself tbh.

So @artonge what do you think? Given that E2EE release needs to come first, then Social prio 1 issues / release for review then this issue we are currently commenting in/on. So I guess the week of 1th April should be save, no?

**Comment by AndyScherzinger** [comment]
The issue is scheduled in general but no ETA, well it had an ETA we missed due to the mentioned apps.

**Comment by DaphneMuller** [comment]
thanks to you both! ❤️

**Comment by AndyScherzinger** [comment]
> I would say the week of the 10th

Thanks and yes, that is what I also meant but typo, so 1th lacked the trailing zero...

**Comment by provokateurin** [comment]
Since we also want the special headers documented, shouldn't we update the title?

**Comment by artonge** [comment]
> Since we also want the special headers documented, shouldn't we update the title?

Yes, please list any header that is not listed here, not sure that I am aware of all of them :)

**Comment by provokateurin** [comment]
> Yes, please list any header that is not listed here, not sure that I am aware of all of them :)

I don't know about all the headers, I just know about this one header. I think part of this task is to figure out all the headers that are not documented right now?

**Comment by artonge** [comment]
WIP PR: https://github.com/nextcloud/documentation/pull/10040
