### ISSUE TITLE
Nextcloud 15 Update

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/documentation#967]
- [x] Remove outdated db schema @rullzer 
- [x] Update outdated DI @rullzer 
- [x] Update app tutorial @juliushaertl 
- [ ] Getting started bump @jancborchardt
- [ ] App structure 
- [ ] Makefile/npm standard @ChristophWurst 
- [ ] VueJS intro and explanations
- [ ] Rework the order of the app tutorial https://github.com/nextcloud/documentation/blob/NC15-cleanup/developer_manual/app/index.rst @jancborchardt

**Comment by ChristophWurst** [comment]
>     * Remove outdated db schema @rullzer

We should also document how to get from database.xml to migrations

**Comment by skjnldsv** [comment]
Well, is it done? :grin:

**Comment by juliushaertl** [comment]
I think most of it actually. Let's close and track issues individually as I tend to say those overview issues don't help much and smaller issues are easier to tackle and keep track of the progress.
