### ISSUE TITLE
Migrate Android user manual to user manual

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#978]
Move the docs from https://docs.nextcloud.com/android/android_app.html / https://github.com/nextcloud/android/blob/master/user_manual/android_app.rst into the user manual here.

cc @TobiasKaminsky @MariusBluem

**Comment by tobiasKaminsky** [comment]
Fine by me :+1: 
@MariusBluem can you give it a first shot and I'll review it?

**Comment by MariusBluem** [comment]
> @MariusBluem can you give it a first shot and I'll review it?

Yes.

**Comment by joshtrichards** [comment]
It appears this issue should be closed out since the decision was made not to move the Android user guide here in [#2027](https://github.com/nextcloud/documentation/pull/2027).
