### ISSUE TITLE
Developer Manual: Merge documentation about localization

### ISSUE THREAD

**Issue by korelstar** [nextcloud/documentation#979]
Currently, there are two pages adressing the localization of strings in the developer manual:
- https://github.com/nextcloud/documentation/blob/master/developer_manual/app/view/l10n.rst
- https://github.com/nextcloud/documentation/blob/master/developer_manual/core/translation.rst

The first is for translating in an app, the second for translating in the core. However, most of the content applies for both situations. Unfortunately, some information is in one of them, only (e.g. variables in strings).

Therefore, I propose to merge the content into one single page and list differences for translating in core or in an app.

**Comment by MorrisJobke** [comment]
> Therefore, I propose to merge the content into one single page and list differences for translating in core or in an app.

:+1: full ack - do you want to prepare this?

**Comment by korelstar** [comment]
My English is not perfect and I don't know
- if the section about `l10n.pl` is still needed (is it sill used somewhere?) - or if we should completely switch to `translationtool.phar`, for both apps and server development,
- where to place the merged file: in app development **or** in server development doesn't seem to be sufficient. Maybe we need a reference from app development to core development or the other way around.

Hence, I would need some help and some time ... Maybe someone else would be faster ...

**Comment by MorrisJobke** [comment]
> * if the section about `l10n.pl` is still needed (is it sill used somewhere?) - or if we should completely switch to `translationtool.phar`, for both apps and server development,

`l10n.pl` is not there anymore. Everything should use the translationtool.

**Comment by MorrisJobke** [comment]
> * where to place the merged file: in app development **or** in server development doesn't seem to be sufficient. Maybe we need a reference from app development to core development or the other way around.

Good question. I guess it's fine to only document it in app development and say then in the server that it works the same as the translation for all apps with a link to it.

**Comment by korelstar** [comment]
... on the other hand, https://docs.nextcloud.com/server/15/developer_manual/core/translation.html is on the first level in the doc's navigation. Maybe, this should be changed if it's only a reference.

**Comment by MorrisJobke** [comment]
> ... on the other hand, https://docs.nextcloud.com/server/15/developer_manual/core/translation.html is on the first level in the doc's navigation. Maybe, this should be changed if it's only a reference.

Yes - the menu structure needs to be improved.
