### ISSUE TITLE
Per-user invocation example of occ versions:cleanup is missing users list

### ISSUE THREAD

**Issue by uusijani** [nextcloud/documentation#981]
["Using the occ command"](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst) documents using `versions:cleanup` either globally or for specific users, with example invocations for both cases. However, said examples are identical in [the current revision](https://github.com/nextcloud/documentation/blob/a22f1055520dac2d6537fb77a6ad059b0439c2ac/admin_manual/configuration_server/occ_command.rst):

> This example deletes all versions for all users:
> 
>     sudo -u www-data php occ versions:cleanup
>     Delete all versions
>     Delete versions for users on backend Database
> 
>     […]
> 
> You can delete versions for specific users in a space-delimited list:
> 
>     sudo -u www-data php occ versions:cleanup
>     Delete versions of   freda
>     Delete versions of   molly

Unless I'm misinterpreting this, the latter example should have the space-delimited list of users following the invocation, like so:

>     sudo -u www-data php occ versions:cleanup freda molly

**Comment by tflidd** [comment]
Yes, and it was fixed in https://github.com/nextcloud/documentation/commit/f22f40b57b40aceec320bd59d6f95f0569b08058
