### ISSUE TITLE
Redis Information Confusing

### ISSUE THREAD

**Issue by stone212** [nextcloud/documentation#982]
### Steps to reproduce

1.  Navigate to https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#ubuntu-installation-label

2. See the section that mentions adding this to config.php

```
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\APCu',
'redis' => array(
  'host' => 'localhost',
  'port' => 6379,
    ),
```

3. See the ambiguity because this is under the `SELinux` section but if it only applies to SELinux servers then what implications do I have to know for making redis work on my server without SELinux?

### Expected behaviour
The page should make two things clear:

A. is this config for SELinux installations only?  Or for all server using redis?

B. What is the context to put this into the config.php file (because appending between `maintenance' => false,` and final `);` leads to `Internal Server Error`

### Actual behaviour
Reader does not know if he should use these instructions.  (And when he tries to he gets `Internal Server Error` and then remove these lines from `config.php` and now he does not know if redis is being used or not).

UPDATE:  The doc still sucks for the reasons I say above but the fix for this problem was:

1. `# apt-get install php-apcu`

2. YES add these lines before the final `);` in config.php:

```
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\APCu',
'redis' => array(
  'host' => 'localhost',
  'port' => 6379,
    ),
```

This means that the doc should NOT have this info look like it exists under `SELinux`

**Comment by MorrisJobke** [comment]
We are currently doing a bit of restructuring on the docs. Best is to include this feedback into the ticket #984

**Comment by cbondurant** [comment]
I don't know if this needs to be made under a new issue, but The redis integration docs seems to have at least one typo in the form of stating to use `'\OC\Memcache\APCu'` for `memcache.local` as when attempting to use that setting the server only would return silents 500 errors. Switching `memcache.local` to `\OC\Memcache\Redis` resolved the issue and considered in the overview the memcache warning is now gone. 

If needed I can create a new issue for this.

**Comment by skjnldsv** [comment]
My config is: 
```
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
```

works fine :)

**Comment by cbondurant** [comment]
Looking into the logs, it seems to be related to this error?

```
[core] Error: OC\HintException: Memcache \OC\Memcache\ACPu not available for local cache at <<closure>>
```
 Traceback not included for readability

Would this imply a configuration error of my system?

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com :)

Quick check though, verify you have all the proper php modules and that they are enabled
