### ISSUE TITLE
Re-organize structure of "install steps" in admin manual

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#984]
There is another idea in my head to better organize the admin manual (see screenshots in next comment):

* move "Server configuration"/"Server tuning" to "Installation"
* move "Server configuration"/"Hardening and security guidance" to "Installation"
* rename "Installation" to "Installation and server configuration" because it holds only the installation and configuration of the stack
* rename "Server configuration" to "Nextcloud configuration" because it holds then the configuration of Nextcloud itself

@rakekniven @tflidd @danielkesselberg @michag86 @hanserasmus @jasonbayton Does that make sense? I'm for myself often confused where to find what part. Especially the mix of Nextcloud config vs stack config (PHP, DB, webserver, ...) is confusing me.

<img width="300" alt="bildschirmfoto 2018-11-30 um 19 00 54" src="https://user-images.githubusercontent.com/245432/49306376-4bfd4880-f4d2-11e8-80c3-e55cb232a127.png">
<img width="301" alt="bildschirmfoto 2018-11-30 um 19 00 59" src="https://user-images.githubusercontent.com/245432/49306378-4c95df00-f4d2-11e8-80fd-8705b358b975.png">

Obviously also feedback from others like @nickvergessen @MariusBluem @jospoortvliet @rullzer @skjnldsv or @blizzz is welcome. (just to mention a few)

This re-org should also cause the web server to return the manual landing page in case one page is not available anymore. Currently it just shows a 404.

**Comment by MorrisJobke** [comment]
See also the comments by @tflidd and @hanserasmus in https://github.com/nextcloud/documentation/pull/980#issuecomment-443429851

**Comment by skjnldsv** [comment]
Really looks cleaner I'd say! :100:

**Comment by MorrisJobke** [comment]
> Really looks cleaner I'd say! 💯

Keep in mind, that the screenshots are the current way. You still need to apply my stated changes ;)

**Comment by blizzz** [comment]
The suggestions are reasonable. 

"Automatic configuration setup" is also a candidate for Installation, as it does not make sense to have it after you are already looking the admin panel.

**Comment by MorrisJobke** [comment]
I will have a look at this :)

**Comment by MorrisJobke** [comment]
> "Automatic configuration setup" is also a candidate for Installation, as it does not make sense to have it after you are already looking the admin panel.

Just thought about this and I would keep it where it is now, because it takes care of "once your webserver is configured you can continue with finishing the Nextcloud installation".

**Comment by MorrisJobke** [comment]
I did this in #1214
