### ISSUE TITLE
Search doesn't work due to missing jQuery

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/documentation#9905]
1) Open https://docs.nextcloud.com/server/latest/developer_manual/search.html?q=kaboom

![Bildschirmfoto vom 2023-03-16 12-24-47](https://user-images.githubusercontent.com/1374172/225602651-1a0211fc-4bec-4be2-a2f4-bef16c16aecd.png)

**Comment by ChristophWurst** [comment]
This isn't the first time. https://github.com/nextcloud/documentation/pull/9542 addressed the same bug before.

**Comment by skjnldsv** [comment]
The CI generated builds does have jquery in them.
Something is broken on the server

**Comment by ChristophWurst** [comment]
Are CI builds and deployment identical in terms of dependency installation?

**Comment by szaimen** [comment]
Possibly https://github.com/nextcloud/documentation/commit/60b00a39256a714395c514cb5ccedc6a1a60b100 broke it?

**Comment by skjnldsv** [comment]
> Possibly [60b00a3](https://github.com/nextcloud/documentation/commit/60b00a39256a714395c514cb5ccedc6a1a60b100) broke it?

No, it happened after it was broken. As a tentative to fix it

**Comment by szaimen** [comment]
> No, it happened after it was broken. As a tentative to fix it

Ah I see...
