### ISSUE TITLE
S3 region is a *required* setting

### ISSUE THREAD

**Issue by aentwist** [nextcloud/documentation#9934]
The documentation suggests,

> Not all configuration options are required for all S3 servers. Overriding the hostname, port and region of your S3 server is only required for non-Amazon implementations, which in turn usually don’t require the region to be set.

See https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html#simple-storage-service-s3

First of all this is confusing -

> Overriding the hostname, port and region of your S3 server is only required for non-Amazon implementations, which in turn usually don’t require the region to be set.

But mostly, region is *required* for AWS S3. If not set it randomly defaults to eu-west-1.

**Comment by joshtrichards** [comment]
I encountered the same issue too the first time I read that. Thanks for the reminder!

Also some similar/related cleanup here possibly too: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/amazons3.html
